// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type AudioIsolationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (a *AudioIsolationResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}
