// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type DeleteInviteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DeleteWorkspaceInviteResponseModel *components.DeleteWorkspaceInviteResponseModel
}

func (d DeleteInviteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteInviteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteInviteResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteInviteResponse) GetDeleteWorkspaceInviteResponseModel() *components.DeleteWorkspaceInviteResponseModel {
	if d == nil {
		return nil
	}
	return d.DeleteWorkspaceInviteResponseModel
}
