// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type DeleteMcpServerRouteRequest struct {
	// ID of the MCP Server.
	McpServerID string `pathParam:"style=simple,explode=false,name=mcp_server_id"`
}

func (d *DeleteMcpServerRouteRequest) GetMcpServerID() string {
	if d == nil {
		return ""
	}
	return d.McpServerID
}

type DeleteMcpServerRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (d *DeleteMcpServerRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteMcpServerRouteResponse) GetAny() any {
	if d == nil {
		return nil
	}
	return d.Any
}
