// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type DeleteSecretRouteRequest struct {
	SecretID string `pathParam:"style=simple,explode=false,name=secret_id"`
}

func (d *DeleteSecretRouteRequest) GetSecretID() string {
	if d == nil {
		return ""
	}
	return d.SecretID
}

type DeleteSecretRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSecretRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
