// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type DubRequest struct {
	// ID of the dubbing project.
	DubbingID string `pathParam:"style=simple,explode=false,name=dubbing_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string]                                         `header:"style=simple,explode=false,name=xi-api-key"`
	Body     components.BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDDubPost `request:"mediaType=application/json"`
}

func (d *DubRequest) GetDubbingID() string {
	if d == nil {
		return ""
	}
	return d.DubbingID
}

func (d *DubRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.XiAPIKey
}

func (d *DubRequest) GetBody() components.BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDDubPost {
	if d == nil {
		return components.BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDDubPost{}
	}
	return d.Body
}

type DubResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SegmentDubResponse *components.SegmentDubResponse
}

func (d DubResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DubResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DubResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DubResponse) GetSegmentDubResponse() *components.SegmentDubResponse {
	if d == nil {
		return nil
	}
	return d.SegmentDubResponse
}
