// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type EditVoiceRequest struct {
	// Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
	VoiceID string                                          `pathParam:"style=simple,explode=false,name=voice_id"`
	Body    components.BodyEditVoiceV1VoicesVoiceIDEditPost `request:"mediaType=multipart/form-data"`
}

func (e *EditVoiceRequest) GetVoiceID() string {
	if e == nil {
		return ""
	}
	return e.VoiceID
}

func (e *EditVoiceRequest) GetBody() components.BodyEditVoiceV1VoicesVoiceIDEditPost {
	if e == nil {
		return components.BodyEditVoiceV1VoicesVoiceIDEditPost{}
	}
	return e.Body
}

type EditVoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EditVoiceResponseModel *components.EditVoiceResponseModel
}

func (e EditVoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EditVoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EditVoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EditVoiceResponse) GetEditVoiceResponseModel() *components.EditVoiceResponseModel {
	if e == nil {
		return nil
	}
	return e.EditVoiceResponseModel
}
