// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetAgentLlmExpectedCostCalculationRequest struct {
	AgentID string                                    `pathParam:"style=simple,explode=false,name=agent_id"`
	Body    components.LLMUsageCalculatorRequestModel `request:"mediaType=application/json"`
}

func (g *GetAgentLlmExpectedCostCalculationRequest) GetAgentID() string {
	if g == nil {
		return ""
	}
	return g.AgentID
}

func (g *GetAgentLlmExpectedCostCalculationRequest) GetBody() components.LLMUsageCalculatorRequestModel {
	if g == nil {
		return components.LLMUsageCalculatorRequestModel{}
	}
	return g.Body
}

type GetAgentLlmExpectedCostCalculationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	LLMUsageCalculatorResponseModel *components.LLMUsageCalculatorResponseModel
}

func (g GetAgentLlmExpectedCostCalculationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentLlmExpectedCostCalculationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentLlmExpectedCostCalculationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentLlmExpectedCostCalculationResponse) GetLLMUsageCalculatorResponseModel() *components.LLMUsageCalculatorResponseModel {
	if g == nil {
		return nil
	}
	return g.LLMUsageCalculatorResponseModel
}
