// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

// GetDubbedTranscriptFileFormatType - Format to return transcript in. For subtitles use either 'srt' or 'webvtt', and for a full transcript use 'json'. The 'json' format is not yet supported for Dubbing Studio.
type GetDubbedTranscriptFileFormatType string

const (
	GetDubbedTranscriptFileFormatTypeSrt    GetDubbedTranscriptFileFormatType = "srt"
	GetDubbedTranscriptFileFormatTypeWebvtt GetDubbedTranscriptFileFormatType = "webvtt"
	GetDubbedTranscriptFileFormatTypeJSON   GetDubbedTranscriptFileFormatType = "json"
)

func (e GetDubbedTranscriptFileFormatType) ToPointer() *GetDubbedTranscriptFileFormatType {
	return &e
}
func (e *GetDubbedTranscriptFileFormatType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "srt":
		fallthrough
	case "webvtt":
		fallthrough
	case "json":
		*e = GetDubbedTranscriptFileFormatType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDubbedTranscriptFileFormatType: %v", v)
	}
}

type GetDubbedTranscriptFileRequest struct {
	// ID of the dubbing project.
	DubbingID string `pathParam:"style=simple,explode=false,name=dubbing_id"`
	// ISO-693 language code to retrieve the transcript for. Use 'source' to fetch the transcript of the original media.
	LanguageCode string `pathParam:"style=simple,explode=false,name=language_code"`
	// Format to return transcript in. For subtitles use either 'srt' or 'webvtt', and for a full transcript use 'json'. The 'json' format is not yet supported for Dubbing Studio.
	FormatType *GetDubbedTranscriptFileFormatType `default:"srt" queryParam:"style=form,explode=true,name=format_type"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
}

func (g GetDubbedTranscriptFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDubbedTranscriptFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDubbedTranscriptFileRequest) GetDubbingID() string {
	if g == nil {
		return ""
	}
	return g.DubbingID
}

func (g *GetDubbedTranscriptFileRequest) GetLanguageCode() string {
	if g == nil {
		return ""
	}
	return g.LanguageCode
}

func (g *GetDubbedTranscriptFileRequest) GetFormatType() *GetDubbedTranscriptFileFormatType {
	if g == nil {
		return nil
	}
	return g.FormatType
}

func (g *GetDubbedTranscriptFileRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XiAPIKey
}

type ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType string

const (
	ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeDubbingTranscriptResponseModel ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType = "DubbingTranscriptResponseModel"
	ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeStr                            ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType = "str"
	ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown                        ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType = "Unknown"
)

// ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet - Successful Response
type ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet struct {
	DubbingTranscriptResponseModel *components.DubbingTranscriptResponseModel `queryParam:"inline" union:"member"`
	Str                            *string                                    `queryParam:"inline" union:"member"`
	UnknownRaw                     json.RawMessage                            `json:"-" union:"unknown"`

	Type ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType
}

func CreateResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetDubbingTranscriptResponseModel(dubbingTranscriptResponseModel components.DubbingTranscriptResponseModel) ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet {
	typ := ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeDubbingTranscriptResponseModel

	return ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet{
		DubbingTranscriptResponseModel: &dubbingTranscriptResponseModel,
		Type:                           typ,
	}
}

func CreateResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetStr(str string) ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet {
	typ := ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeStr

	return ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet{
		Str:  &str,
		Type: typ,
	}
}

func CreateResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetUnknown(raw json.RawMessage) ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet {
	return ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet{
		UnknownRaw: raw,
		Type:       ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown,
	}
}

func (u ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet) IsUnknown() bool {
	return u.Type == ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown
}

func (u *ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var dubbingTranscriptResponseModel components.DubbingTranscriptResponseModel = components.DubbingTranscriptResponseModel{}
	if err := utils.UnmarshalJSON(data, &dubbingTranscriptResponseModel, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeDubbingTranscriptResponseModel,
			Value: &dubbingTranscriptResponseModel,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetType)
	switch best.Type {
	case ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeDubbingTranscriptResponseModel:
		u.DubbingTranscriptResponseModel = best.Value.(*components.DubbingTranscriptResponseModel)
		return nil
	case ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGetTypeUnknown
	return nil
}

func (u ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet) MarshalJSON() ([]byte, error) {
	if u.DubbingTranscriptResponseModel != nil {
		return utils.MarshalJSON(u.DubbingTranscriptResponseModel, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet: all fields are null")
}

type GetDubbedTranscriptFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet *ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet
	// Successful Response
	Res *string
}

func (g *GetDubbedTranscriptFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetDubbedTranscriptFileResponse) GetResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet() *ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet {
	if g == nil {
		return nil
	}
	return g.ResponseGetDubbedTranscriptV1DubbingDubbingIDTranscriptLanguageCodeGet
}

func (g *GetDubbedTranscriptFileResponse) GetRes() *string {
	if g == nil {
		return nil
	}
	return g.Res
}
