// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetProjectSnapshotEndpointRequest struct {
	// The ID of the Studio project.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The ID of the Studio project snapshot.
	ProjectSnapshotID string `pathParam:"style=simple,explode=false,name=project_snapshot_id"`
}

func (g *GetProjectSnapshotEndpointRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetProjectSnapshotEndpointRequest) GetProjectSnapshotID() string {
	if g == nil {
		return ""
	}
	return g.ProjectSnapshotID
}

type GetProjectSnapshotEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProjectSnapshotExtendedResponseModel *components.ProjectSnapshotExtendedResponseModel
}

func (g GetProjectSnapshotEndpointResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectSnapshotEndpointResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectSnapshotEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectSnapshotEndpointResponse) GetProjectSnapshotExtendedResponseModel() *components.ProjectSnapshotExtendedResponseModel {
	if g == nil {
		return nil
	}
	return g.ProjectSnapshotExtendedResponseModel
}
