// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetProjectMutedTracksEndpointRequest struct {
	// The ID of the Studio project.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (g *GetProjectMutedTracksEndpointRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

type GetProjectMutedTracksEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProjectMutedTracksResponseModel *components.ProjectMutedTracksResponseModel
}

func (g GetProjectMutedTracksEndpointResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectMutedTracksEndpointResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectMutedTracksEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectMutedTracksEndpointResponse) GetProjectMutedTracksResponseModel() *components.ProjectMutedTracksResponseModel {
	if g == nil {
		return nil
	}
	return g.ProjectMutedTracksResponseModel
}
