// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetProjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetProjectsResponseModel *components.GetProjectsResponseModel
}

func (g GetProjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectsResponse) GetGetProjectsResponseModel() *components.GetProjectsResponseModel {
	if g == nil {
		return nil
	}
	return g.GetProjectsResponseModel
}
