// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetPvcVoiceCaptchaRequest struct {
	// Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
	VoiceID string `pathParam:"style=simple,explode=false,name=voice_id"`
}

func (g *GetPvcVoiceCaptchaRequest) GetVoiceID() string {
	if g == nil {
		return ""
	}
	return g.VoiceID
}

type GetPvcVoiceCaptchaResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (g *GetPvcVoiceCaptchaResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}
