// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetPvcSampleSpeakersRequest struct {
	// Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
	VoiceID string `pathParam:"style=simple,explode=false,name=voice_id"`
	// Sample ID to be used
	SampleID string `pathParam:"style=simple,explode=false,name=sample_id"`
}

func (g *GetPvcSampleSpeakersRequest) GetVoiceID() string {
	if g == nil {
		return ""
	}
	return g.VoiceID
}

func (g *GetPvcSampleSpeakersRequest) GetSampleID() string {
	if g == nil {
		return ""
	}
	return g.SampleID
}

type GetPvcSampleSpeakersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SpeakerSeparationResponseModel *components.SpeakerSeparationResponseModel
}

func (g GetPvcSampleSpeakersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPvcSampleSpeakersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPvcSampleSpeakersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPvcSampleSpeakersResponse) GetSpeakerSeparationResponseModel() *components.SpeakerSeparationResponseModel {
	if g == nil {
		return nil
	}
	return g.SpeakerSeparationResponseModel
}
