// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type GetServiceAccountAPIKeysRouteRequest struct {
	ServiceAccountUserID string `pathParam:"style=simple,explode=false,name=service_account_user_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
}

func (g *GetServiceAccountAPIKeysRouteRequest) GetServiceAccountUserID() string {
	if g == nil {
		return ""
	}
	return g.ServiceAccountUserID
}

func (g *GetServiceAccountAPIKeysRouteRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XiAPIKey
}

type GetServiceAccountAPIKeysRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	WorkspaceAPIKeyListResponseModel *components.WorkspaceAPIKeyListResponseModel
}

func (g GetServiceAccountAPIKeysRouteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetServiceAccountAPIKeysRouteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetServiceAccountAPIKeysRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetServiceAccountAPIKeysRouteResponse) GetWorkspaceAPIKeyListResponseModel() *components.WorkspaceAPIKeyListResponseModel {
	if g == nil {
		return nil
	}
	return g.WorkspaceAPIKeyListResponseModel
}
