// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type GetSingleUseTokenRequest struct {
	TokenType components.SingleUseTokenType `pathParam:"style=simple,explode=false,name=token_type"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
}

func (g *GetSingleUseTokenRequest) GetTokenType() components.SingleUseTokenType {
	if g == nil {
		return components.SingleUseTokenType("")
	}
	return g.TokenType
}

func (g *GetSingleUseTokenRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XiAPIKey
}

type GetSingleUseTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SingleUseTokenResponseModel *components.SingleUseTokenResponseModel
}

func (g GetSingleUseTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSingleUseTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSingleUseTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSingleUseTokenResponse) GetSingleUseTokenResponseModel() *components.SingleUseTokenResponseModel {
	if g == nil {
		return nil
	}
	return g.SingleUseTokenResponseModel
}
