// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type GetToolRouteRequest struct {
	// ID of the requested tool.
	ToolID string `pathParam:"style=simple,explode=false,name=tool_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
}

func (g *GetToolRouteRequest) GetToolID() string {
	if g == nil {
		return ""
	}
	return g.ToolID
}

func (g *GetToolRouteRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XiAPIKey
}

type GetToolRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ToolResponseModel *components.ToolResponseModel
}

func (g GetToolRouteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetToolRouteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetToolRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetToolRouteResponse) GetToolResponseModel() *components.ToolResponseModel {
	if g == nil {
		return nil
	}
	return g.ToolResponseModel
}
