// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type GetWorkspaceAuditLogsRequest struct {
	// Maximum number of entries per page
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for the next page (from previous response)
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Only include entries at or after this time (ms since epoch)
	TimeFromUnixMs *int64 `queryParam:"style=form,explode=true,name=time_from_unix_ms"`
	// Only include entries at or before this time (ms since epoch)
	TimeToUnixMs *int64 `queryParam:"style=form,explode=true,name=time_to_unix_ms"`
	// Filter by actor user ID
	ActorUID *string `queryParam:"style=form,explode=true,name=actor_uid"`
	// Filter by OCSF event class name (e.g. Account Change)
	ClassName *string `queryParam:"style=form,explode=true,name=class_name"`
	// Filter by audit activity name (e.g. Subscription Creation)
	ActivityName *string `queryParam:"style=form,explode=true,name=activity_name"`
}

func (g GetWorkspaceAuditLogsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWorkspaceAuditLogsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWorkspaceAuditLogsRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetWorkspaceAuditLogsRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetWorkspaceAuditLogsRequest) GetTimeFromUnixMs() *int64 {
	if g == nil {
		return nil
	}
	return g.TimeFromUnixMs
}

func (g *GetWorkspaceAuditLogsRequest) GetTimeToUnixMs() *int64 {
	if g == nil {
		return nil
	}
	return g.TimeToUnixMs
}

func (g *GetWorkspaceAuditLogsRequest) GetActorUID() *string {
	if g == nil {
		return nil
	}
	return g.ActorUID
}

func (g *GetWorkspaceAuditLogsRequest) GetClassName() *string {
	if g == nil {
		return nil
	}
	return g.ClassName
}

func (g *GetWorkspaceAuditLogsRequest) GetActivityName() *string {
	if g == nil {
		return nil
	}
	return g.ActivityName
}

type GetWorkspaceAuditLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	WorkspaceAuditLogsPageResponse *components.WorkspaceAuditLogsPageResponse
}

func (g GetWorkspaceAuditLogsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWorkspaceAuditLogsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWorkspaceAuditLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWorkspaceAuditLogsResponse) GetWorkspaceAuditLogsPageResponse() *components.WorkspaceAuditLogsPageResponse {
	if g == nil {
		return nil
	}
	return g.WorkspaceAuditLogsPageResponse
}
