// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

// DubbingStatus1 - What state the dub is currently in.
type DubbingStatus1 string

const (
	DubbingStatus1Dubbing DubbingStatus1 = "dubbing"
	DubbingStatus1Dubbed  DubbingStatus1 = "dubbed"
	DubbingStatus1Failed  DubbingStatus1 = "failed"
)

func (e DubbingStatus1) ToPointer() *DubbingStatus1 {
	return &e
}
func (e *DubbingStatus1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dubbing":
		fallthrough
	case "dubbed":
		fallthrough
	case "failed":
		*e = DubbingStatus1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DubbingStatus1: %v", v)
	}
}

type DubbingStatus2 string

const (
	DubbingStatus2Queued    DubbingStatus2 = "queued"
	DubbingStatus2Preparing DubbingStatus2 = "preparing"
	DubbingStatus2Dubbing   DubbingStatus2 = "dubbing"
	DubbingStatus2Dubbed    DubbingStatus2 = "dubbed"
	DubbingStatus2Failed    DubbingStatus2 = "failed"
)

func (e DubbingStatus2) ToPointer() *DubbingStatus2 {
	return &e
}
func (e *DubbingStatus2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "queued":
		fallthrough
	case "preparing":
		fallthrough
	case "dubbing":
		fallthrough
	case "dubbed":
		fallthrough
	case "failed":
		*e = DubbingStatus2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DubbingStatus2: %v", v)
	}
}

type DubbingModel string

const (
	DubbingModelDubbingV1 DubbingModel = "dubbing_v1"
	DubbingModelDubbingV2 DubbingModel = "dubbing_v2"
)

func (e DubbingModel) ToPointer() *DubbingModel {
	return &e
}
func (e *DubbingModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dubbing_v1":
		fallthrough
	case "dubbing_v2":
		*e = DubbingModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DubbingModel: %v", v)
	}
}

type CreationSource string

const (
	CreationSourceFlowNode   CreationSource = "flow_node"
	CreationSourceDubbingUI  CreationSource = "dubbing_ui"
	CreationSourceDubbingAPI CreationSource = "dubbing_api"
)

func (e CreationSource) ToPointer() *CreationSource {
	return &e
}
func (e *CreationSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flow_node":
		fallthrough
	case "dubbing_ui":
		fallthrough
	case "dubbing_api":
		*e = CreationSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreationSource: %v", v)
	}
}

// FilterByCreator - Filters who created the resources being listed, whether it was the user running the request or someone else that shared the resource with them.
type FilterByCreator string

const (
	FilterByCreatorPersonal FilterByCreator = "personal"
	FilterByCreatorOthers   FilterByCreator = "others"
	FilterByCreatorAll      FilterByCreator = "all"
)

func (e FilterByCreator) ToPointer() *FilterByCreator {
	return &e
}
func (e *FilterByCreator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "personal":
		fallthrough
	case "others":
		fallthrough
	case "all":
		*e = FilterByCreator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterByCreator: %v", v)
	}
}

// OrderBy - The field to use for ordering results from this query.
type OrderBy string

const (
	OrderByCreatedAt OrderBy = "created_at"
	OrderByName      OrderBy = "name"
)

func (e OrderBy) ToPointer() *OrderBy {
	return &e
}
func (e *OrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "name":
		*e = OrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderBy: %v", v)
	}
}

// OrderDirection - The order direction to use for results from this query.
type OrderDirection string

const (
	OrderDirectionDescending OrderDirection = "DESCENDING"
	OrderDirectionAscending  OrderDirection = "ASCENDING"
)

func (e OrderDirection) ToPointer() *OrderDirection {
	return &e
}
func (e *OrderDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DESCENDING":
		fallthrough
	case "ASCENDING":
		*e = OrderDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderDirection: %v", v)
	}
}

type ListDubsRequest struct {
	// Used for fetching next page. Cursor is returned in the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// How many dubs to return at maximum. Can not exceed 200, defaults to 100.
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
	// What state the dub is currently in.
	DubbingStatus *DubbingStatus1 `queryParam:"style=form,explode=true,name=dubbing_status"`
	// Filter by dubbing status.
	DubbingStatuses []DubbingStatus2 `queryParam:"style=form,explode=true,name=dubbing_statuses"`
	// Filter by dubbing model generation.
	DubbingModels []DubbingModel `queryParam:"style=form,explode=true,name=dubbing_models"`
	// Filter by target language code.
	TargetLanguageCodes []string `queryParam:"style=form,explode=true,name=target_language_codes"`
	// Filter by dubbing creation source.
	CreationSources []CreationSource `queryParam:"style=form,explode=true,name=creation_sources"`
	// Filters who created the resources being listed, whether it was the user running the request or someone else that shared the resource with them.
	FilterByCreator *FilterByCreator `default:"all" queryParam:"style=form,explode=true,name=filter_by_creator"`
	// The field to use for ordering results from this query.
	OrderBy *OrderBy `default:"created_at" queryParam:"style=form,explode=true,name=order_by"`
	// The order direction to use for results from this query.
	OrderDirection *OrderDirection `default:"DESCENDING" queryParam:"style=form,explode=true,name=order_direction"`
}

func (l ListDubsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDubsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDubsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListDubsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListDubsRequest) GetDubbingStatus() *DubbingStatus1 {
	if l == nil {
		return nil
	}
	return l.DubbingStatus
}

func (l *ListDubsRequest) GetDubbingStatuses() []DubbingStatus2 {
	if l == nil {
		return nil
	}
	return l.DubbingStatuses
}

func (l *ListDubsRequest) GetDubbingModels() []DubbingModel {
	if l == nil {
		return nil
	}
	return l.DubbingModels
}

func (l *ListDubsRequest) GetTargetLanguageCodes() []string {
	if l == nil {
		return nil
	}
	return l.TargetLanguageCodes
}

func (l *ListDubsRequest) GetCreationSources() []CreationSource {
	if l == nil {
		return nil
	}
	return l.CreationSources
}

func (l *ListDubsRequest) GetFilterByCreator() *FilterByCreator {
	if l == nil {
		return nil
	}
	return l.FilterByCreator
}

func (l *ListDubsRequest) GetOrderBy() *OrderBy {
	if l == nil {
		return nil
	}
	return l.OrderBy
}

func (l *ListDubsRequest) GetOrderDirection() *OrderDirection {
	if l == nil {
		return nil
	}
	return l.OrderDirection
}

type ListDubsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DubbingMetadataPageResponseModel *components.DubbingMetadataPageResponseModel
}

func (l ListDubsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDubsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDubsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListDubsResponse) GetDubbingMetadataPageResponseModel() *components.DubbingMetadataPageResponseModel {
	if l == nil {
		return nil
	}
	return l.DubbingMetadataPageResponseModel
}
