// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type ListMcpServerToolsRouteRequest struct {
	// ID of the MCP Server.
	McpServerID string `pathParam:"style=simple,explode=false,name=mcp_server_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
}

func (l *ListMcpServerToolsRouteRequest) GetMcpServerID() string {
	if l == nil {
		return ""
	}
	return l.McpServerID
}

func (l *ListMcpServerToolsRouteRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XiAPIKey
}

type ListMcpServerToolsRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ListMCPToolsResponseModel *components.ListMCPToolsResponseModel
}

func (l ListMcpServerToolsRouteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMcpServerToolsRouteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListMcpServerToolsRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListMcpServerToolsRouteResponse) GetListMCPToolsResponseModel() *components.ListMCPToolsResponseModel {
	if l == nil {
		return nil
	}
	return l.ListMCPToolsResponseModel
}
