// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type ListSipMessagesRequest struct {
	// The phone number ID. This is returned when a phone number is imported.
	PhoneNumberID string `pathParam:"style=simple,explode=false,name=phone_number_id"`
	PageSize      *int64 `default:"20" queryParam:"style=form,explode=true,name=page_size"`
	// Used for fetching next page. Cursor is returned in the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListSipMessagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSipMessagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSipMessagesRequest) GetPhoneNumberID() string {
	if l == nil {
		return ""
	}
	return l.PhoneNumberID
}

func (l *ListSipMessagesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListSipMessagesRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListSipMessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetSIPLogMessagesResponse *components.GetSIPLogMessagesResponse
}

func (l ListSipMessagesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSipMessagesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSipMessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSipMessagesResponse) GetGetSIPLogMessagesResponse() *components.GetSIPLogMessagesResponse {
	if l == nil {
		return nil
	}
	return l.GetSIPLogMessagesResponse
}
