// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type PatchPronunciationDictionaryRequest struct {
	// The id of the pronunciation dictionary
	PronunciationDictionaryID string `pathParam:"style=simple,explode=false,name=pronunciation_dictionary_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string]                                                              `header:"style=simple,explode=false,name=xi-api-key"`
	Body     *components.BodyUpdatePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDPatch `request:"mediaType=application/json"`
}

func (p PatchPronunciationDictionaryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchPronunciationDictionaryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchPronunciationDictionaryRequest) GetPronunciationDictionaryID() string {
	if p == nil {
		return ""
	}
	return p.PronunciationDictionaryID
}

func (p *PatchPronunciationDictionaryRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.XiAPIKey
}

func (p *PatchPronunciationDictionaryRequest) GetBody() *components.BodyUpdatePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDPatch {
	if p == nil {
		return nil
	}
	return p.Body
}

type PatchPronunciationDictionaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetPronunciationDictionaryMetadataResponseModel *components.GetPronunciationDictionaryMetadataResponseModel
}

func (p PatchPronunciationDictionaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchPronunciationDictionaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchPronunciationDictionaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchPronunciationDictionaryResponse) GetGetPronunciationDictionaryMetadataResponseModel() *components.GetPronunciationDictionaryMetadataResponseModel {
	if p == nil {
		return nil
	}
	return p.GetPronunciationDictionaryMetadataResponseModel
}
