// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type PostAgentAvatarRouteRequest struct {
	// The id of an agent. This is returned on agent creation.
	AgentID string                                                        `pathParam:"style=simple,explode=false,name=agent_id"`
	Body    components.BodyPostAgentAvatarV1ConvaiAgentsAgentIDAvatarPost `request:"mediaType=multipart/form-data"`
}

func (p *PostAgentAvatarRouteRequest) GetAgentID() string {
	if p == nil {
		return ""
	}
	return p.AgentID
}

func (p *PostAgentAvatarRouteRequest) GetBody() components.BodyPostAgentAvatarV1ConvaiAgentsAgentIDAvatarPost {
	if p == nil {
		return components.BodyPostAgentAvatarV1ConvaiAgentsAgentIDAvatarPost{}
	}
	return p.Body
}

type PostAgentAvatarRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PostAgentAvatarResponseModel *components.PostAgentAvatarResponseModel
}

func (p PostAgentAvatarRouteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostAgentAvatarRouteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostAgentAvatarRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAgentAvatarRouteResponse) GetPostAgentAvatarResponseModel() *components.PostAgentAvatarResponseModel {
	if p == nil {
		return nil
	}
	return p.PostAgentAvatarResponseModel
}
