// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type RequestPvcManualVerificationRequest struct {
	// Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
	VoiceID string `pathParam:"style=simple,explode=false,name=voice_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string]                                  `header:"style=simple,explode=false,name=xi-api-key"`
	Body     components.BodyRequestManualVerificationV1VoicesPvcVoiceIDVerificationPost `request:"mediaType=multipart/form-data"`
}

func (r *RequestPvcManualVerificationRequest) GetVoiceID() string {
	if r == nil {
		return ""
	}
	return r.VoiceID
}

func (r *RequestPvcManualVerificationRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.XiAPIKey
}

func (r *RequestPvcManualVerificationRequest) GetBody() components.BodyRequestManualVerificationV1VoicesPvcVoiceIDVerificationPost {
	if r == nil {
		return components.BodyRequestManualVerificationV1VoicesPvcVoiceIDVerificationPost{}
	}
	return r.Body
}

type RequestPvcManualVerificationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RequestPVCManualVerificationResponseModel *components.RequestPVCManualVerificationResponseModel
}

func (r RequestPvcManualVerificationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestPvcManualVerificationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequestPvcManualVerificationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RequestPvcManualVerificationResponse) GetRequestPVCManualVerificationResponseModel() *components.RequestPVCManualVerificationResponseModel {
	if r == nil {
		return nil
	}
	return r.RequestPVCManualVerificationResponseModel
}
