// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type ResubmitTestsRouteRequest struct {
	// The id of a test invocation. This is returned when tests are run.
	TestInvocationID string `pathParam:"style=simple,explode=false,name=test_invocation_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
	Body     components.ResubmitTestsRequestModel      `request:"mediaType=application/json"`
}

func (r *ResubmitTestsRouteRequest) GetTestInvocationID() string {
	if r == nil {
		return ""
	}
	return r.TestInvocationID
}

func (r *ResubmitTestsRouteRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.XiAPIKey
}

func (r *ResubmitTestsRouteRequest) GetBody() components.ResubmitTestsRequestModel {
	if r == nil {
		return components.ResubmitTestsRequestModel{}
	}
	return r.Body
}

type ResubmitTestsRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (r *ResubmitTestsRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ResubmitTestsRouteResponse) GetAny() any {
	if r == nil {
		return nil
	}
	return r.Any
}
