// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"io"
)

type TextToDialogueAllowedOutputFormats string

const (
	TextToDialogueAllowedOutputFormatsMp32205032   TextToDialogueAllowedOutputFormats = "mp3_22050_32"
	TextToDialogueAllowedOutputFormatsMp32400048   TextToDialogueAllowedOutputFormats = "mp3_24000_48"
	TextToDialogueAllowedOutputFormatsMp34410032   TextToDialogueAllowedOutputFormats = "mp3_44100_32"
	TextToDialogueAllowedOutputFormatsMp34410064   TextToDialogueAllowedOutputFormats = "mp3_44100_64"
	TextToDialogueAllowedOutputFormatsMp34410096   TextToDialogueAllowedOutputFormats = "mp3_44100_96"
	TextToDialogueAllowedOutputFormatsMp344100128  TextToDialogueAllowedOutputFormats = "mp3_44100_128"
	TextToDialogueAllowedOutputFormatsMp344100192  TextToDialogueAllowedOutputFormats = "mp3_44100_192"
	TextToDialogueAllowedOutputFormatsPcm8000      TextToDialogueAllowedOutputFormats = "pcm_8000"
	TextToDialogueAllowedOutputFormatsPcm16000     TextToDialogueAllowedOutputFormats = "pcm_16000"
	TextToDialogueAllowedOutputFormatsPcm22050     TextToDialogueAllowedOutputFormats = "pcm_22050"
	TextToDialogueAllowedOutputFormatsPcm24000     TextToDialogueAllowedOutputFormats = "pcm_24000"
	TextToDialogueAllowedOutputFormatsPcm32000     TextToDialogueAllowedOutputFormats = "pcm_32000"
	TextToDialogueAllowedOutputFormatsPcm44100     TextToDialogueAllowedOutputFormats = "pcm_44100"
	TextToDialogueAllowedOutputFormatsPcm48000     TextToDialogueAllowedOutputFormats = "pcm_48000"
	TextToDialogueAllowedOutputFormatsUlaw8000     TextToDialogueAllowedOutputFormats = "ulaw_8000"
	TextToDialogueAllowedOutputFormatsAlaw8000     TextToDialogueAllowedOutputFormats = "alaw_8000"
	TextToDialogueAllowedOutputFormatsOpus4800032  TextToDialogueAllowedOutputFormats = "opus_48000_32"
	TextToDialogueAllowedOutputFormatsOpus4800064  TextToDialogueAllowedOutputFormats = "opus_48000_64"
	TextToDialogueAllowedOutputFormatsOpus4800096  TextToDialogueAllowedOutputFormats = "opus_48000_96"
	TextToDialogueAllowedOutputFormatsOpus48000128 TextToDialogueAllowedOutputFormats = "opus_48000_128"
	TextToDialogueAllowedOutputFormatsOpus48000192 TextToDialogueAllowedOutputFormats = "opus_48000_192"
	TextToDialogueAllowedOutputFormatsWav16000     TextToDialogueAllowedOutputFormats = "wav_16000"
	TextToDialogueAllowedOutputFormatsWav22050     TextToDialogueAllowedOutputFormats = "wav_22050"
	TextToDialogueAllowedOutputFormatsWav24000     TextToDialogueAllowedOutputFormats = "wav_24000"
	TextToDialogueAllowedOutputFormatsWav32000     TextToDialogueAllowedOutputFormats = "wav_32000"
	TextToDialogueAllowedOutputFormatsWav44100     TextToDialogueAllowedOutputFormats = "wav_44100"
	TextToDialogueAllowedOutputFormatsWav48000     TextToDialogueAllowedOutputFormats = "wav_48000"
	TextToDialogueAllowedOutputFormatsWav8000      TextToDialogueAllowedOutputFormats = "wav_8000"
)

func (e TextToDialogueAllowedOutputFormats) ToPointer() *TextToDialogueAllowedOutputFormats {
	return &e
}
func (e *TextToDialogueAllowedOutputFormats) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mp3_22050_32":
		fallthrough
	case "mp3_24000_48":
		fallthrough
	case "mp3_44100_32":
		fallthrough
	case "mp3_44100_64":
		fallthrough
	case "mp3_44100_96":
		fallthrough
	case "mp3_44100_128":
		fallthrough
	case "mp3_44100_192":
		fallthrough
	case "pcm_8000":
		fallthrough
	case "pcm_16000":
		fallthrough
	case "pcm_22050":
		fallthrough
	case "pcm_24000":
		fallthrough
	case "pcm_32000":
		fallthrough
	case "pcm_44100":
		fallthrough
	case "pcm_48000":
		fallthrough
	case "ulaw_8000":
		fallthrough
	case "alaw_8000":
		fallthrough
	case "opus_48000_32":
		fallthrough
	case "opus_48000_64":
		fallthrough
	case "opus_48000_96":
		fallthrough
	case "opus_48000_128":
		fallthrough
	case "opus_48000_192":
		fallthrough
	case "wav_16000":
		fallthrough
	case "wav_22050":
		fallthrough
	case "wav_24000":
		fallthrough
	case "wav_32000":
		fallthrough
	case "wav_44100":
		fallthrough
	case "wav_48000":
		fallthrough
	case "wav_8000":
		*e = TextToDialogueAllowedOutputFormats(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TextToDialogueAllowedOutputFormats: %v", v)
	}
}

type TextToDialogueNonStreamingOutputFormats string

const (
	TextToDialogueNonStreamingOutputFormatsWav8000      TextToDialogueNonStreamingOutputFormats = "wav_8000"
	TextToDialogueNonStreamingOutputFormatsWav16000     TextToDialogueNonStreamingOutputFormats = "wav_16000"
	TextToDialogueNonStreamingOutputFormatsWav22050     TextToDialogueNonStreamingOutputFormats = "wav_22050"
	TextToDialogueNonStreamingOutputFormatsWav24000     TextToDialogueNonStreamingOutputFormats = "wav_24000"
	TextToDialogueNonStreamingOutputFormatsWav32000     TextToDialogueNonStreamingOutputFormats = "wav_32000"
	TextToDialogueNonStreamingOutputFormatsWav44100     TextToDialogueNonStreamingOutputFormats = "wav_44100"
	TextToDialogueNonStreamingOutputFormatsWav48000     TextToDialogueNonStreamingOutputFormats = "wav_48000"
	TextToDialogueNonStreamingOutputFormatsAlaw8000     TextToDialogueNonStreamingOutputFormats = "alaw_8000"
	TextToDialogueNonStreamingOutputFormatsMp32205032   TextToDialogueNonStreamingOutputFormats = "mp3_22050_32"
	TextToDialogueNonStreamingOutputFormatsMp32400048   TextToDialogueNonStreamingOutputFormats = "mp3_24000_48"
	TextToDialogueNonStreamingOutputFormatsMp344100128  TextToDialogueNonStreamingOutputFormats = "mp3_44100_128"
	TextToDialogueNonStreamingOutputFormatsMp344100192  TextToDialogueNonStreamingOutputFormats = "mp3_44100_192"
	TextToDialogueNonStreamingOutputFormatsMp34410032   TextToDialogueNonStreamingOutputFormats = "mp3_44100_32"
	TextToDialogueNonStreamingOutputFormatsMp34410064   TextToDialogueNonStreamingOutputFormats = "mp3_44100_64"
	TextToDialogueNonStreamingOutputFormatsMp34410096   TextToDialogueNonStreamingOutputFormats = "mp3_44100_96"
	TextToDialogueNonStreamingOutputFormatsOpus48000128 TextToDialogueNonStreamingOutputFormats = "opus_48000_128"
	TextToDialogueNonStreamingOutputFormatsOpus48000192 TextToDialogueNonStreamingOutputFormats = "opus_48000_192"
	TextToDialogueNonStreamingOutputFormatsOpus4800032  TextToDialogueNonStreamingOutputFormats = "opus_48000_32"
	TextToDialogueNonStreamingOutputFormatsOpus4800064  TextToDialogueNonStreamingOutputFormats = "opus_48000_64"
	TextToDialogueNonStreamingOutputFormatsOpus4800096  TextToDialogueNonStreamingOutputFormats = "opus_48000_96"
	TextToDialogueNonStreamingOutputFormatsPcm16000     TextToDialogueNonStreamingOutputFormats = "pcm_16000"
	TextToDialogueNonStreamingOutputFormatsPcm22050     TextToDialogueNonStreamingOutputFormats = "pcm_22050"
	TextToDialogueNonStreamingOutputFormatsPcm24000     TextToDialogueNonStreamingOutputFormats = "pcm_24000"
	TextToDialogueNonStreamingOutputFormatsPcm32000     TextToDialogueNonStreamingOutputFormats = "pcm_32000"
	TextToDialogueNonStreamingOutputFormatsPcm44100     TextToDialogueNonStreamingOutputFormats = "pcm_44100"
	TextToDialogueNonStreamingOutputFormatsPcm48000     TextToDialogueNonStreamingOutputFormats = "pcm_48000"
	TextToDialogueNonStreamingOutputFormatsPcm8000      TextToDialogueNonStreamingOutputFormats = "pcm_8000"
	TextToDialogueNonStreamingOutputFormatsUlaw8000     TextToDialogueNonStreamingOutputFormats = "ulaw_8000"
)

func (e TextToDialogueNonStreamingOutputFormats) ToPointer() *TextToDialogueNonStreamingOutputFormats {
	return &e
}
func (e *TextToDialogueNonStreamingOutputFormats) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "wav_8000":
		fallthrough
	case "wav_16000":
		fallthrough
	case "wav_22050":
		fallthrough
	case "wav_24000":
		fallthrough
	case "wav_32000":
		fallthrough
	case "wav_44100":
		fallthrough
	case "wav_48000":
		fallthrough
	case "alaw_8000":
		fallthrough
	case "mp3_22050_32":
		fallthrough
	case "mp3_24000_48":
		fallthrough
	case "mp3_44100_128":
		fallthrough
	case "mp3_44100_192":
		fallthrough
	case "mp3_44100_32":
		fallthrough
	case "mp3_44100_64":
		fallthrough
	case "mp3_44100_96":
		fallthrough
	case "opus_48000_128":
		fallthrough
	case "opus_48000_192":
		fallthrough
	case "opus_48000_32":
		fallthrough
	case "opus_48000_64":
		fallthrough
	case "opus_48000_96":
		fallthrough
	case "pcm_16000":
		fallthrough
	case "pcm_22050":
		fallthrough
	case "pcm_24000":
		fallthrough
	case "pcm_32000":
		fallthrough
	case "pcm_44100":
		fallthrough
	case "pcm_48000":
		fallthrough
	case "pcm_8000":
		fallthrough
	case "ulaw_8000":
		*e = TextToDialogueNonStreamingOutputFormats(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TextToDialogueNonStreamingOutputFormats: %v", v)
	}
}

type TextToDialogueOutputFormatOfTheGeneratedAudioType string

const (
	TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueNonStreamingOutputFormats TextToDialogueOutputFormatOfTheGeneratedAudioType = "text_to_dialogue_NonStreamingOutputFormats"
	TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueAllowedOutputFormats      TextToDialogueOutputFormatOfTheGeneratedAudioType = "text_to_dialogue_AllowedOutputFormats"
)

// TextToDialogueOutputFormatOfTheGeneratedAudio - Output format of the generated audio. Formatted as codec_sample_rate_bitrate. So an mp3 with 22.05kHz sample rate at 32kbs is represented as mp3_22050_32. MP3 with 192kbps bitrate requires you to be subscribed to Creator tier or above. PCM and WAV formats with 44.1kHz sample rate requires you to be subscribed to Pro tier or above. Note that the μ-law format (sometimes written mu-law, often approximated as u-law) is commonly used for Twilio audio inputs.
type TextToDialogueOutputFormatOfTheGeneratedAudio struct {
	TextToDialogueNonStreamingOutputFormats *TextToDialogueNonStreamingOutputFormats `queryParam:"inline" union:"member"`
	TextToDialogueAllowedOutputFormats      *TextToDialogueAllowedOutputFormats      `queryParam:"inline" union:"member"`

	Type TextToDialogueOutputFormatOfTheGeneratedAudioType
}

func CreateTextToDialogueOutputFormatOfTheGeneratedAudioTextToDialogueNonStreamingOutputFormats(textToDialogueNonStreamingOutputFormats TextToDialogueNonStreamingOutputFormats) TextToDialogueOutputFormatOfTheGeneratedAudio {
	typ := TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueNonStreamingOutputFormats

	return TextToDialogueOutputFormatOfTheGeneratedAudio{
		TextToDialogueNonStreamingOutputFormats: &textToDialogueNonStreamingOutputFormats,
		Type:                                    typ,
	}
}

func CreateTextToDialogueOutputFormatOfTheGeneratedAudioTextToDialogueAllowedOutputFormats(textToDialogueAllowedOutputFormats TextToDialogueAllowedOutputFormats) TextToDialogueOutputFormatOfTheGeneratedAudio {
	typ := TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueAllowedOutputFormats

	return TextToDialogueOutputFormatOfTheGeneratedAudio{
		TextToDialogueAllowedOutputFormats: &textToDialogueAllowedOutputFormats,
		Type:                               typ,
	}
}

func (u *TextToDialogueOutputFormatOfTheGeneratedAudio) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var textToDialogueNonStreamingOutputFormats TextToDialogueNonStreamingOutputFormats = TextToDialogueNonStreamingOutputFormats("")
	if err := utils.UnmarshalJSON(data, &textToDialogueNonStreamingOutputFormats, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueNonStreamingOutputFormats,
			Value: &textToDialogueNonStreamingOutputFormats,
		})
	}

	var textToDialogueAllowedOutputFormats TextToDialogueAllowedOutputFormats = TextToDialogueAllowedOutputFormats("")
	if err := utils.UnmarshalJSON(data, &textToDialogueAllowedOutputFormats, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueAllowedOutputFormats,
			Value: &textToDialogueAllowedOutputFormats,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TextToDialogueOutputFormatOfTheGeneratedAudio", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TextToDialogueOutputFormatOfTheGeneratedAudio", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(TextToDialogueOutputFormatOfTheGeneratedAudioType)
	switch best.Type {
	case TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueNonStreamingOutputFormats:
		u.TextToDialogueNonStreamingOutputFormats = best.Value.(*TextToDialogueNonStreamingOutputFormats)
		return nil
	case TextToDialogueOutputFormatOfTheGeneratedAudioTypeTextToDialogueAllowedOutputFormats:
		u.TextToDialogueAllowedOutputFormats = best.Value.(*TextToDialogueAllowedOutputFormats)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TextToDialogueOutputFormatOfTheGeneratedAudio", string(data))
}

func (u TextToDialogueOutputFormatOfTheGeneratedAudio) MarshalJSON() ([]byte, error) {
	if u.TextToDialogueNonStreamingOutputFormats != nil {
		return utils.MarshalJSON(u.TextToDialogueNonStreamingOutputFormats, "", true)
	}

	if u.TextToDialogueAllowedOutputFormats != nil {
		return utils.MarshalJSON(u.TextToDialogueAllowedOutputFormats, "", true)
	}

	return nil, errors.New("could not marshal union type TextToDialogueOutputFormatOfTheGeneratedAudio: all fields are null")
}

type TextToDialogueRequest struct {
	// Output format of the generated audio. Formatted as codec_sample_rate_bitrate. So an mp3 with 22.05kHz sample rate at 32kbs is represented as mp3_22050_32. MP3 with 192kbps bitrate requires you to be subscribed to Creator tier or above. PCM and WAV formats with 44.1kHz sample rate requires you to be subscribed to Pro tier or above. Note that the μ-law format (sometimes written mu-law, often approximated as u-law) is commonly used for Twilio audio inputs.
	OutputFormat *TextToDialogueOutputFormatOfTheGeneratedAudio              `queryParam:"style=form,explode=true,name=output_format"`
	Body         components.BodyTextToDialogueMultiVoiceV1TextToDialoguePost `request:"mediaType=application/json"`
}

func (t *TextToDialogueRequest) GetOutputFormat() *TextToDialogueOutputFormatOfTheGeneratedAudio {
	if t == nil {
		return nil
	}
	return t.OutputFormat
}

func (t *TextToDialogueRequest) GetBody() components.BodyTextToDialogueMultiVoiceV1TextToDialoguePost {
	if t == nil {
		return components.BodyTextToDialogueMultiVoiceV1TextToDialoguePost{}
	}
	return t.Body
}

type TextToDialogueResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The generated audio file
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (t *TextToDialogueResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TextToDialogueResponse) GetResponseStream() io.ReadCloser {
	if t == nil {
		return nil
	}
	return t.ResponseStream
}
