// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type TranscribeRequest struct {
	// ID of the dubbing project.
	DubbingID string `pathParam:"style=simple,explode=false,name=dubbing_id"`
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string]                                  `header:"style=simple,explode=false,name=xi-api-key"`
	Body     components.BodyTranscribesSegmentsV1DubbingResourceDubbingIDTranscribePost `request:"mediaType=application/json"`
}

func (t *TranscribeRequest) GetDubbingID() string {
	if t == nil {
		return ""
	}
	return t.DubbingID
}

func (t *TranscribeRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.XiAPIKey
}

func (t *TranscribeRequest) GetBody() components.BodyTranscribesSegmentsV1DubbingResourceDubbingIDTranscribePost {
	if t == nil {
		return components.BodyTranscribesSegmentsV1DubbingResourceDubbingIDTranscribePost{}
	}
	return t.Body
}

type TranscribeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SegmentTranscriptionResponse *components.SegmentTranscriptionResponse
}

func (t TranscribeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TranscribeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TranscribeResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TranscribeResponse) GetSegmentTranscriptionResponse() *components.SegmentTranscriptionResponse {
	if t == nil {
		return nil
	}
	return t.SegmentTranscriptionResponse
}
