// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type UpdateSpeakerRequest struct {
	// ID of the dubbing project.
	DubbingID string `pathParam:"style=simple,explode=false,name=dubbing_id"`
	// ID of the speaker.
	SpeakerID string                                                                                   `pathParam:"style=simple,explode=false,name=speaker_id"`
	Body      *components.BodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIDSpeakerSpeakerIDPatch `request:"mediaType=application/json"`
}

func (u UpdateSpeakerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSpeakerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSpeakerRequest) GetDubbingID() string {
	if u == nil {
		return ""
	}
	return u.DubbingID
}

func (u *UpdateSpeakerRequest) GetSpeakerID() string {
	if u == nil {
		return ""
	}
	return u.SpeakerID
}

func (u *UpdateSpeakerRequest) GetBody() *components.BodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIDSpeakerSpeakerIDPatch {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdateSpeakerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SpeakerUpdatedResponse *components.SpeakerUpdatedResponse
}

func (u UpdateSpeakerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSpeakerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSpeakerResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSpeakerResponse) GetSpeakerUpdatedResponse() *components.SpeakerUpdatedResponse {
	if u == nil {
		return nil
	}
	return u.SpeakerUpdatedResponse
}
