// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/models/components"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type UpdateSettingsRouteRequest struct {
	// Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=xi-api-key"`
	Body     components.PatchConvAISettingsRequest     `request:"mediaType=application/json"`
}

func (u *UpdateSettingsRouteRequest) GetXiAPIKey() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.XiAPIKey
}

func (u *UpdateSettingsRouteRequest) GetBody() components.PatchConvAISettingsRequest {
	if u == nil {
		return components.PatchConvAISettingsRequest{}
	}
	return u.Body
}

type UpdateSettingsRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetConvAISettingsResponseModel *components.GetConvAISettingsResponseModel
}

func (u UpdateSettingsRouteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSettingsRouteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSettingsRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSettingsRouteResponse) GetGetConvAISettingsResponseModel() *components.GetConvAISettingsResponseModel {
	if u == nil {
		return nil
	}
	return u.GetConvAISettingsResponseModel
}
