// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bdlilley/elevenlabs-go/models/components"
)

type UpdateWhatsappAccountRequest struct {
	PhoneNumberID string                                  `pathParam:"style=simple,explode=false,name=phone_number_id"`
	Body          components.UpdateWhatsAppAccountRequest `request:"mediaType=application/json"`
}

func (u *UpdateWhatsappAccountRequest) GetPhoneNumberID() string {
	if u == nil {
		return ""
	}
	return u.PhoneNumberID
}

func (u *UpdateWhatsappAccountRequest) GetBody() components.UpdateWhatsAppAccountRequest {
	if u == nil {
		return components.UpdateWhatsAppAccountRequest{}
	}
	return u.Body
}

type UpdateWhatsappAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (u *UpdateWhatsappAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateWhatsappAccountResponse) GetAny() any {
	if u == nil {
		return nil
	}
	return u.Any
}
