// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type AgentPlatformSettingsResponseModel struct {
	// Settings to evaluate an agent's performance.
	// Agents are evaluated against a set of criteria, with success being defined as meeting some combination of those criteria.
	Evaluation *EvaluationSettingsOutput `json:"evaluation,omitzero"`
	Widget     *WidgetConfigOutput       `json:"widget,omitzero"`
	// Data collection settings
	DataCollection map[string]AnalysisProperty `json:"data_collection,omitzero"`
	// Scope per data collection item ID. Missing keys default to conversation scope.
	DataCollectionScopes map[string]AnalysisScope                      `json:"data_collection_scopes,omitzero"`
	Overrides            *ConversationInitiationClientDataConfigOutput `json:"overrides,omitzero"`
	WorkspaceOverrides   *AgentWorkspaceOverridesOutput                `json:"workspace_overrides,omitzero"`
	// Settings for agent testing configuration.
	Testing *AgentTestingSettings `json:"testing,omitzero"`
	// Whether the agent is archived
	Archived   *bool               `default:"false" json:"archived"`
	Guardrails *GuardrailsV1Output `json:"guardrails,omitzero"`
	// Language for all conversation analysis outputs (summaries, titles, evaluation rationales, data collection rationales). If not set, the language will be inferred from the conversation. Must be one of the supported conversation languages.
	SummaryLanguage *string              `json:"summary_language,omitzero"`
	Auth            *AuthSettings        `json:"auth,omitzero"`
	CallLimits      *AgentCallLimits     `json:"call_limits,omitzero"`
	Privacy         *PrivacyConfigOutput `json:"privacy,omitzero"`
	// The trust context in which the agent operates.
	//
	// UNKNOWN: not yet classified (existing agents created before this feature).
	// LOW: serves untrusted external participants (e.g. customer support, sales) —
	//      outputs should be vetted and tool access scoped.
	// HIGH: serves the owner (e.g. personal assistant) — full tool access is appropriate.
	TrustContext *AgentTrustContext `default:"unknown" json:"trust_context"`
	AnalysisLlm  *Llm               `default:"gemini-2.5-flash" json:"analysis_llm"`
	// Per-agent topic-discovery configuration. Cadence and analysis window are
	// managed internally; this only exposes the customer-facing on/off toggle.
	TopicDiscovery *TopicDiscoverySettings `json:"topic_discovery,omitzero"`
	Safety         *SafetyResponseModel    `json:"safety,omitzero"`
}

func (a AgentPlatformSettingsResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentPlatformSettingsResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentPlatformSettingsResponseModel) GetEvaluation() *EvaluationSettingsOutput {
	if a == nil {
		return nil
	}
	return a.Evaluation
}

func (a *AgentPlatformSettingsResponseModel) GetWidget() *WidgetConfigOutput {
	if a == nil {
		return nil
	}
	return a.Widget
}

func (a *AgentPlatformSettingsResponseModel) GetDataCollection() map[string]AnalysisProperty {
	if a == nil {
		return nil
	}
	return a.DataCollection
}

func (a *AgentPlatformSettingsResponseModel) GetDataCollectionScopes() map[string]AnalysisScope {
	if a == nil {
		return nil
	}
	return a.DataCollectionScopes
}

func (a *AgentPlatformSettingsResponseModel) GetOverrides() *ConversationInitiationClientDataConfigOutput {
	if a == nil {
		return nil
	}
	return a.Overrides
}

func (a *AgentPlatformSettingsResponseModel) GetWorkspaceOverrides() *AgentWorkspaceOverridesOutput {
	if a == nil {
		return nil
	}
	return a.WorkspaceOverrides
}

func (a *AgentPlatformSettingsResponseModel) GetTesting() *AgentTestingSettings {
	if a == nil {
		return nil
	}
	return a.Testing
}

func (a *AgentPlatformSettingsResponseModel) GetArchived() *bool {
	if a == nil {
		return nil
	}
	return a.Archived
}

func (a *AgentPlatformSettingsResponseModel) GetGuardrails() *GuardrailsV1Output {
	if a == nil {
		return nil
	}
	return a.Guardrails
}

func (a *AgentPlatformSettingsResponseModel) GetSummaryLanguage() *string {
	if a == nil {
		return nil
	}
	return a.SummaryLanguage
}

func (a *AgentPlatformSettingsResponseModel) GetAuth() *AuthSettings {
	if a == nil {
		return nil
	}
	return a.Auth
}

func (a *AgentPlatformSettingsResponseModel) GetCallLimits() *AgentCallLimits {
	if a == nil {
		return nil
	}
	return a.CallLimits
}

func (a *AgentPlatformSettingsResponseModel) GetPrivacy() *PrivacyConfigOutput {
	if a == nil {
		return nil
	}
	return a.Privacy
}

func (a *AgentPlatformSettingsResponseModel) GetTrustContext() *AgentTrustContext {
	if a == nil {
		return nil
	}
	return a.TrustContext
}

func (a *AgentPlatformSettingsResponseModel) GetAnalysisLlm() *Llm {
	if a == nil {
		return nil
	}
	return a.AnalysisLlm
}

func (a *AgentPlatformSettingsResponseModel) GetTopicDiscovery() *TopicDiscoverySettings {
	if a == nil {
		return nil
	}
	return a.TopicDiscovery
}

func (a *AgentPlatformSettingsResponseModel) GetSafety() *SafetyResponseModel {
	if a == nil {
		return nil
	}
	return a.Safety
}
