// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type AgentTestFolderPathSegmentResponseModel struct {
	ID   string  `json:"id"`
	Name *string `default:"" json:"name"`
}

func (a AgentTestFolderPathSegmentResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentTestFolderPathSegmentResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentTestFolderPathSegmentResponseModel) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AgentTestFolderPathSegmentResponseModel) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}
