// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type ArrayJSONSchemaPropertyInputItemsType string

const (
	ArrayJSONSchemaPropertyInputItemsTypeLiteralJSONSchemaProperty     ArrayJSONSchemaPropertyInputItemsType = "LiteralJsonSchemaProperty"
	ArrayJSONSchemaPropertyInputItemsTypeObjectJSONSchemaPropertyInput ArrayJSONSchemaPropertyInputItemsType = "ObjectJsonSchemaProperty-Input"
	ArrayJSONSchemaPropertyInputItemsTypeArrayJSONSchemaPropertyInput  ArrayJSONSchemaPropertyInputItemsType = "ArrayJsonSchemaProperty-Input"
)

type ArrayJSONSchemaPropertyInputItems struct {
	LiteralJSONSchemaProperty     *LiteralJSONSchemaProperty     `queryParam:"inline" union:"member"`
	ObjectJSONSchemaPropertyInput *ObjectJSONSchemaPropertyInput `queryParam:"inline" union:"member"`
	ArrayJSONSchemaPropertyInput  *ArrayJSONSchemaPropertyInput  `queryParam:"inline" union:"member"`

	Type ArrayJSONSchemaPropertyInputItemsType
}

func CreateArrayJSONSchemaPropertyInputItemsLiteralJSONSchemaProperty(literalJSONSchemaProperty LiteralJSONSchemaProperty) ArrayJSONSchemaPropertyInputItems {
	typ := ArrayJSONSchemaPropertyInputItemsTypeLiteralJSONSchemaProperty

	return ArrayJSONSchemaPropertyInputItems{
		LiteralJSONSchemaProperty: &literalJSONSchemaProperty,
		Type:                      typ,
	}
}

func CreateArrayJSONSchemaPropertyInputItemsObjectJSONSchemaPropertyInput(objectJSONSchemaPropertyInput ObjectJSONSchemaPropertyInput) ArrayJSONSchemaPropertyInputItems {
	typ := ArrayJSONSchemaPropertyInputItemsTypeObjectJSONSchemaPropertyInput

	return ArrayJSONSchemaPropertyInputItems{
		ObjectJSONSchemaPropertyInput: &objectJSONSchemaPropertyInput,
		Type:                          typ,
	}
}

func CreateArrayJSONSchemaPropertyInputItemsArrayJSONSchemaPropertyInput(arrayJSONSchemaPropertyInput ArrayJSONSchemaPropertyInput) ArrayJSONSchemaPropertyInputItems {
	typ := ArrayJSONSchemaPropertyInputItemsTypeArrayJSONSchemaPropertyInput

	return ArrayJSONSchemaPropertyInputItems{
		ArrayJSONSchemaPropertyInput: &arrayJSONSchemaPropertyInput,
		Type:                         typ,
	}
}

func (u *ArrayJSONSchemaPropertyInputItems) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var literalJSONSchemaProperty LiteralJSONSchemaProperty = LiteralJSONSchemaProperty{}
	if err := utils.UnmarshalJSON(data, &literalJSONSchemaProperty, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ArrayJSONSchemaPropertyInputItemsTypeLiteralJSONSchemaProperty,
			Value: &literalJSONSchemaProperty,
		})
	}

	var objectJSONSchemaPropertyInput ObjectJSONSchemaPropertyInput = ObjectJSONSchemaPropertyInput{}
	if err := utils.UnmarshalJSON(data, &objectJSONSchemaPropertyInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ArrayJSONSchemaPropertyInputItemsTypeObjectJSONSchemaPropertyInput,
			Value: &objectJSONSchemaPropertyInput,
		})
	}

	var arrayJSONSchemaPropertyInput ArrayJSONSchemaPropertyInput = ArrayJSONSchemaPropertyInput{}
	if err := utils.UnmarshalJSON(data, &arrayJSONSchemaPropertyInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ArrayJSONSchemaPropertyInputItemsTypeArrayJSONSchemaPropertyInput,
			Value: &arrayJSONSchemaPropertyInput,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ArrayJSONSchemaPropertyInputItems", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ArrayJSONSchemaPropertyInputItems", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ArrayJSONSchemaPropertyInputItemsType)
	switch best.Type {
	case ArrayJSONSchemaPropertyInputItemsTypeLiteralJSONSchemaProperty:
		u.LiteralJSONSchemaProperty = best.Value.(*LiteralJSONSchemaProperty)
		return nil
	case ArrayJSONSchemaPropertyInputItemsTypeObjectJSONSchemaPropertyInput:
		u.ObjectJSONSchemaPropertyInput = best.Value.(*ObjectJSONSchemaPropertyInput)
		return nil
	case ArrayJSONSchemaPropertyInputItemsTypeArrayJSONSchemaPropertyInput:
		u.ArrayJSONSchemaPropertyInput = best.Value.(*ArrayJSONSchemaPropertyInput)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ArrayJSONSchemaPropertyInputItems", string(data))
}

func (u ArrayJSONSchemaPropertyInputItems) MarshalJSON() ([]byte, error) {
	if u.LiteralJSONSchemaProperty != nil {
		return utils.MarshalJSON(u.LiteralJSONSchemaProperty, "", true)
	}

	if u.ObjectJSONSchemaPropertyInput != nil {
		return utils.MarshalJSON(u.ObjectJSONSchemaPropertyInput, "", true)
	}

	if u.ArrayJSONSchemaPropertyInput != nil {
		return utils.MarshalJSON(u.ArrayJSONSchemaPropertyInput, "", true)
	}

	return nil, errors.New("could not marshal union type ArrayJSONSchemaPropertyInputItems: all fields are null")
}

type ArrayJSONSchemaPropertyInput struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_       *string                           `const:"array" json:"type"`
	Description *string                           `default:"" json:"description"`
	Items       ArrayJSONSchemaPropertyInputItems `json:"items"`
}

func (a ArrayJSONSchemaPropertyInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArrayJSONSchemaPropertyInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArrayJSONSchemaPropertyInput) GetType() *string {
	return types.Pointer("array")
}

func (a *ArrayJSONSchemaPropertyInput) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *ArrayJSONSchemaPropertyInput) GetItems() ArrayJSONSchemaPropertyInputItems {
	if a == nil {
		return ArrayJSONSchemaPropertyInputItems{}
	}
	return a.Items
}
