// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ASRQuality string

const (
	ASRQualityHigh ASRQuality = "high"
)

func (e ASRQuality) ToPointer() *ASRQuality {
	return &e
}
func (e *ASRQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "high":
		*e = ASRQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ASRQuality: %v", v)
	}
}
