// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type ASTNotEqualsOperatorNodeInput1 struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string      `const:"neq_operator" json:"type"`
	Left  ASTNodeInput `json:"left"`
	Right ASTNodeInput `json:"right"`
}

func (a ASTNotEqualsOperatorNodeInput1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ASTNotEqualsOperatorNodeInput1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ASTNotEqualsOperatorNodeInput1) GetType() *string {
	return types.Pointer("neq_operator")
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeft() ASTNodeInput {
	if a == nil {
		return ASTNodeInput{}
	}
	return a.Left
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftAddOperator() *ASTAdditionOperatorNodeInput1 {
	return a.GetLeft().ASTAdditionOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftAndOperator() *ASTAndOperatorNodeInput1 {
	return a.GetLeft().ASTAndOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftBooleanLiteral() *ASTBooleanNodeInput {
	return a.GetLeft().ASTBooleanNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftConditionalOperator() *ASTConditionalOperatorNodeInput1 {
	return a.GetLeft().ASTConditionalOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftDivOperator() *ASTDivisionOperatorNodeInput1 {
	return a.GetLeft().ASTDivisionOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftDynamicVariable() *ASTDynamicVariableNodeInput {
	return a.GetLeft().ASTDynamicVariableNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftEqOperator() *ASTEqualsOperatorNodeInput1 {
	return a.GetLeft().ASTEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftGtOperator() *ASTGreaterThanOperatorNodeInput1 {
	return a.GetLeft().ASTGreaterThanOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftGteOperator() *ASTGreaterThanOrEqualsOperatorNodeInput1 {
	return a.GetLeft().ASTGreaterThanOrEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftLlm() *ASTLLMNodeInput {
	return a.GetLeft().ASTLLMNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftLtOperator() *ASTLessThanOperatorNodeInput1 {
	return a.GetLeft().ASTLessThanOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftLteOperator() *ASTLessThanOrEqualsOperatorNodeInput1 {
	return a.GetLeft().ASTLessThanOrEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftMulOperator() *ASTMultiplicationOperatorNodeInput1 {
	return a.GetLeft().ASTMultiplicationOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftNeqOperator() *ASTNotEqualsOperatorNodeInput1 {
	return a.GetLeft().ASTNotEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftNumberLiteral() *ASTNumberNodeInput {
	return a.GetLeft().ASTNumberNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftOrOperator() *ASTOrOperatorNodeInput1 {
	return a.GetLeft().ASTOrOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftStringLiteral() *ASTStringNodeInput {
	return a.GetLeft().ASTStringNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetLeftSubOperator() *ASTSubtractionOperatorNodeInput1 {
	return a.GetLeft().ASTSubtractionOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRight() ASTNodeInput {
	if a == nil {
		return ASTNodeInput{}
	}
	return a.Right
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightAddOperator() *ASTAdditionOperatorNodeInput1 {
	return a.GetRight().ASTAdditionOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightAndOperator() *ASTAndOperatorNodeInput1 {
	return a.GetRight().ASTAndOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightBooleanLiteral() *ASTBooleanNodeInput {
	return a.GetRight().ASTBooleanNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightConditionalOperator() *ASTConditionalOperatorNodeInput1 {
	return a.GetRight().ASTConditionalOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightDivOperator() *ASTDivisionOperatorNodeInput1 {
	return a.GetRight().ASTDivisionOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightDynamicVariable() *ASTDynamicVariableNodeInput {
	return a.GetRight().ASTDynamicVariableNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightEqOperator() *ASTEqualsOperatorNodeInput1 {
	return a.GetRight().ASTEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightGtOperator() *ASTGreaterThanOperatorNodeInput1 {
	return a.GetRight().ASTGreaterThanOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightGteOperator() *ASTGreaterThanOrEqualsOperatorNodeInput1 {
	return a.GetRight().ASTGreaterThanOrEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightLlm() *ASTLLMNodeInput {
	return a.GetRight().ASTLLMNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightLtOperator() *ASTLessThanOperatorNodeInput1 {
	return a.GetRight().ASTLessThanOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightLteOperator() *ASTLessThanOrEqualsOperatorNodeInput1 {
	return a.GetRight().ASTLessThanOrEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightMulOperator() *ASTMultiplicationOperatorNodeInput1 {
	return a.GetRight().ASTMultiplicationOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightNeqOperator() *ASTNotEqualsOperatorNodeInput1 {
	return a.GetRight().ASTNotEqualsOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightNumberLiteral() *ASTNumberNodeInput {
	return a.GetRight().ASTNumberNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightOrOperator() *ASTOrOperatorNodeInput1 {
	return a.GetRight().ASTOrOperatorNodeInput1
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightStringLiteral() *ASTStringNodeInput {
	return a.GetRight().ASTStringNodeInput
}

func (a *ASTNotEqualsOperatorNodeInput1) GetRightSubOperator() *ASTSubtractionOperatorNodeInput1 {
	return a.GetRight().ASTSubtractionOperatorNodeInput1
}

// #region class-body-astnotequalsoperatornodeinput1
// #endregion class-body-astnotequalsoperatornodeinput1
