// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ASTNodeOutputType string

const (
	ASTNodeOutputTypeAddOperator         ASTNodeOutputType = "add_operator"
	ASTNodeOutputTypeAndOperator         ASTNodeOutputType = "and_operator"
	ASTNodeOutputTypeBooleanLiteral      ASTNodeOutputType = "boolean_literal"
	ASTNodeOutputTypeConditionalOperator ASTNodeOutputType = "conditional_operator"
	ASTNodeOutputTypeDivOperator         ASTNodeOutputType = "div_operator"
	ASTNodeOutputTypeDynamicVariable     ASTNodeOutputType = "dynamic_variable"
	ASTNodeOutputTypeEqOperator          ASTNodeOutputType = "eq_operator"
	ASTNodeOutputTypeGtOperator          ASTNodeOutputType = "gt_operator"
	ASTNodeOutputTypeGteOperator         ASTNodeOutputType = "gte_operator"
	ASTNodeOutputTypeLlm                 ASTNodeOutputType = "llm"
	ASTNodeOutputTypeLtOperator          ASTNodeOutputType = "lt_operator"
	ASTNodeOutputTypeLteOperator         ASTNodeOutputType = "lte_operator"
	ASTNodeOutputTypeMulOperator         ASTNodeOutputType = "mul_operator"
	ASTNodeOutputTypeNeqOperator         ASTNodeOutputType = "neq_operator"
	ASTNodeOutputTypeNumberLiteral       ASTNodeOutputType = "number_literal"
	ASTNodeOutputTypeOrOperator          ASTNodeOutputType = "or_operator"
	ASTNodeOutputTypeStringLiteral       ASTNodeOutputType = "string_literal"
	ASTNodeOutputTypeSubOperator         ASTNodeOutputType = "sub_operator"
	ASTNodeOutputTypeUnknown             ASTNodeOutputType = "UNKNOWN"
)

type ASTNodeOutput struct {
	ASTStringNodeOutput                       *ASTStringNodeOutput                       `queryParam:"inline" union:"member"`
	ASTNumberNodeOutput                       *ASTNumberNodeOutput                       `queryParam:"inline" union:"member"`
	ASTBooleanNodeOutput                      *ASTBooleanNodeOutput                      `queryParam:"inline" union:"member"`
	ASTLLMNodeOutput                          *ASTLLMNodeOutput                          `queryParam:"inline" union:"member"`
	ASTDynamicVariableNodeOutput              *ASTDynamicVariableNodeOutput              `queryParam:"inline" union:"member"`
	ASTOrOperatorNodeOutput1                  *ASTOrOperatorNodeOutput1                  `queryParam:"inline" union:"member"`
	ASTAndOperatorNodeOutput1                 *ASTAndOperatorNodeOutput1                 `queryParam:"inline" union:"member"`
	ASTEqualsOperatorNodeOutput1              *ASTEqualsOperatorNodeOutput1              `queryParam:"inline" union:"member"`
	ASTNotEqualsOperatorNodeOutput1           *ASTNotEqualsOperatorNodeOutput1           `queryParam:"inline" union:"member"`
	ASTGreaterThanOperatorNodeOutput1         *ASTGreaterThanOperatorNodeOutput1         `queryParam:"inline" union:"member"`
	ASTLessThanOperatorNodeOutput1            *ASTLessThanOperatorNodeOutput1            `queryParam:"inline" union:"member"`
	ASTGreaterThanOrEqualsOperatorNodeOutput1 *ASTGreaterThanOrEqualsOperatorNodeOutput1 `queryParam:"inline" union:"member"`
	ASTLessThanOrEqualsOperatorNodeOutput1    *ASTLessThanOrEqualsOperatorNodeOutput1    `queryParam:"inline" union:"member"`
	ASTAdditionOperatorNodeOutput1            *ASTAdditionOperatorNodeOutput1            `queryParam:"inline" union:"member"`
	ASTSubtractionOperatorNodeOutput1         *ASTSubtractionOperatorNodeOutput1         `queryParam:"inline" union:"member"`
	ASTMultiplicationOperatorNodeOutput1      *ASTMultiplicationOperatorNodeOutput1      `queryParam:"inline" union:"member"`
	ASTDivisionOperatorNodeOutput1            *ASTDivisionOperatorNodeOutput1            `queryParam:"inline" union:"member"`
	ASTConditionalOperatorNodeOutput1         *ASTConditionalOperatorNodeOutput1         `queryParam:"inline" union:"member"`
	UnknownRaw                                json.RawMessage                            `json:"-" union:"unknown"`

	Type ASTNodeOutputType
}

func CreateASTNodeOutputAddOperator(addOperator ASTAdditionOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeAddOperator

	return ASTNodeOutput{
		ASTAdditionOperatorNodeOutput1: &addOperator,
		Type:                           typ,
	}
}

func CreateASTNodeOutputAndOperator(andOperator ASTAndOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeAndOperator

	return ASTNodeOutput{
		ASTAndOperatorNodeOutput1: &andOperator,
		Type:                      typ,
	}
}

func CreateASTNodeOutputBooleanLiteral(booleanLiteral ASTBooleanNodeOutput) ASTNodeOutput {
	typ := ASTNodeOutputTypeBooleanLiteral

	return ASTNodeOutput{
		ASTBooleanNodeOutput: &booleanLiteral,
		Type:                 typ,
	}
}

func CreateASTNodeOutputConditionalOperator(conditionalOperator ASTConditionalOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeConditionalOperator

	return ASTNodeOutput{
		ASTConditionalOperatorNodeOutput1: &conditionalOperator,
		Type:                              typ,
	}
}

func CreateASTNodeOutputDivOperator(divOperator ASTDivisionOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeDivOperator

	return ASTNodeOutput{
		ASTDivisionOperatorNodeOutput1: &divOperator,
		Type:                           typ,
	}
}

func CreateASTNodeOutputDynamicVariable(dynamicVariable ASTDynamicVariableNodeOutput) ASTNodeOutput {
	typ := ASTNodeOutputTypeDynamicVariable

	return ASTNodeOutput{
		ASTDynamicVariableNodeOutput: &dynamicVariable,
		Type:                         typ,
	}
}

func CreateASTNodeOutputEqOperator(eqOperator ASTEqualsOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeEqOperator

	return ASTNodeOutput{
		ASTEqualsOperatorNodeOutput1: &eqOperator,
		Type:                         typ,
	}
}

func CreateASTNodeOutputGtOperator(gtOperator ASTGreaterThanOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeGtOperator

	return ASTNodeOutput{
		ASTGreaterThanOperatorNodeOutput1: &gtOperator,
		Type:                              typ,
	}
}

func CreateASTNodeOutputGteOperator(gteOperator ASTGreaterThanOrEqualsOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeGteOperator

	return ASTNodeOutput{
		ASTGreaterThanOrEqualsOperatorNodeOutput1: &gteOperator,
		Type: typ,
	}
}

func CreateASTNodeOutputLlm(llm ASTLLMNodeOutput) ASTNodeOutput {
	typ := ASTNodeOutputTypeLlm

	return ASTNodeOutput{
		ASTLLMNodeOutput: &llm,
		Type:             typ,
	}
}

func CreateASTNodeOutputLtOperator(ltOperator ASTLessThanOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeLtOperator

	return ASTNodeOutput{
		ASTLessThanOperatorNodeOutput1: &ltOperator,
		Type:                           typ,
	}
}

func CreateASTNodeOutputLteOperator(lteOperator ASTLessThanOrEqualsOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeLteOperator

	return ASTNodeOutput{
		ASTLessThanOrEqualsOperatorNodeOutput1: &lteOperator,
		Type:                                   typ,
	}
}

func CreateASTNodeOutputMulOperator(mulOperator ASTMultiplicationOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeMulOperator

	return ASTNodeOutput{
		ASTMultiplicationOperatorNodeOutput1: &mulOperator,
		Type:                                 typ,
	}
}

func CreateASTNodeOutputNeqOperator(neqOperator ASTNotEqualsOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeNeqOperator

	return ASTNodeOutput{
		ASTNotEqualsOperatorNodeOutput1: &neqOperator,
		Type:                            typ,
	}
}

func CreateASTNodeOutputNumberLiteral(numberLiteral ASTNumberNodeOutput) ASTNodeOutput {
	typ := ASTNodeOutputTypeNumberLiteral

	return ASTNodeOutput{
		ASTNumberNodeOutput: &numberLiteral,
		Type:                typ,
	}
}

func CreateASTNodeOutputOrOperator(orOperator ASTOrOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeOrOperator

	return ASTNodeOutput{
		ASTOrOperatorNodeOutput1: &orOperator,
		Type:                     typ,
	}
}

func CreateASTNodeOutputStringLiteral(stringLiteral ASTStringNodeOutput) ASTNodeOutput {
	typ := ASTNodeOutputTypeStringLiteral

	return ASTNodeOutput{
		ASTStringNodeOutput: &stringLiteral,
		Type:                typ,
	}
}

func CreateASTNodeOutputSubOperator(subOperator ASTSubtractionOperatorNodeOutput1) ASTNodeOutput {
	typ := ASTNodeOutputTypeSubOperator

	return ASTNodeOutput{
		ASTSubtractionOperatorNodeOutput1: &subOperator,
		Type:                              typ,
	}
}

func CreateASTNodeOutputUnknown(raw json.RawMessage) ASTNodeOutput {
	return ASTNodeOutput{
		UnknownRaw: raw,
		Type:       ASTNodeOutputTypeUnknown,
	}
}

func (u ASTNodeOutput) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ASTNodeOutput) IsUnknown() bool {
	return u.Type == ASTNodeOutputTypeUnknown
}

func (u *ASTNodeOutput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ASTNodeOutputTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ASTNodeOutputTypeUnknown
		return nil
	}

	switch dis.Type {
	case "add_operator":
		astAdditionOperatorNodeOutput1 := new(ASTAdditionOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astAdditionOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == add_operator) type ASTAdditionOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTAdditionOperatorNodeOutput1 = astAdditionOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeAddOperator
		return nil
	case "and_operator":
		astAndOperatorNodeOutput1 := new(ASTAndOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astAndOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == and_operator) type ASTAndOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTAndOperatorNodeOutput1 = astAndOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeAndOperator
		return nil
	case "boolean_literal":
		astBooleanNodeOutput := new(ASTBooleanNodeOutput)
		if err := utils.UnmarshalJSON(data, &astBooleanNodeOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == boolean_literal) type ASTBooleanNodeOutput within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTBooleanNodeOutput = astBooleanNodeOutput
		u.Type = ASTNodeOutputTypeBooleanLiteral
		return nil
	case "conditional_operator":
		astConditionalOperatorNodeOutput1 := new(ASTConditionalOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astConditionalOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == conditional_operator) type ASTConditionalOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTConditionalOperatorNodeOutput1 = astConditionalOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeConditionalOperator
		return nil
	case "div_operator":
		astDivisionOperatorNodeOutput1 := new(ASTDivisionOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astDivisionOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == div_operator) type ASTDivisionOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTDivisionOperatorNodeOutput1 = astDivisionOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeDivOperator
		return nil
	case "dynamic_variable":
		astDynamicVariableNodeOutput := new(ASTDynamicVariableNodeOutput)
		if err := utils.UnmarshalJSON(data, &astDynamicVariableNodeOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == dynamic_variable) type ASTDynamicVariableNodeOutput within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTDynamicVariableNodeOutput = astDynamicVariableNodeOutput
		u.Type = ASTNodeOutputTypeDynamicVariable
		return nil
	case "eq_operator":
		astEqualsOperatorNodeOutput1 := new(ASTEqualsOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astEqualsOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == eq_operator) type ASTEqualsOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTEqualsOperatorNodeOutput1 = astEqualsOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeEqOperator
		return nil
	case "gt_operator":
		astGreaterThanOperatorNodeOutput1 := new(ASTGreaterThanOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astGreaterThanOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == gt_operator) type ASTGreaterThanOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTGreaterThanOperatorNodeOutput1 = astGreaterThanOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeGtOperator
		return nil
	case "gte_operator":
		astGreaterThanOrEqualsOperatorNodeOutput1 := new(ASTGreaterThanOrEqualsOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astGreaterThanOrEqualsOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == gte_operator) type ASTGreaterThanOrEqualsOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTGreaterThanOrEqualsOperatorNodeOutput1 = astGreaterThanOrEqualsOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeGteOperator
		return nil
	case "llm":
		astllmNodeOutput := new(ASTLLMNodeOutput)
		if err := utils.UnmarshalJSON(data, &astllmNodeOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == llm) type ASTLLMNodeOutput within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTLLMNodeOutput = astllmNodeOutput
		u.Type = ASTNodeOutputTypeLlm
		return nil
	case "lt_operator":
		astLessThanOperatorNodeOutput1 := new(ASTLessThanOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astLessThanOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == lt_operator) type ASTLessThanOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTLessThanOperatorNodeOutput1 = astLessThanOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeLtOperator
		return nil
	case "lte_operator":
		astLessThanOrEqualsOperatorNodeOutput1 := new(ASTLessThanOrEqualsOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astLessThanOrEqualsOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == lte_operator) type ASTLessThanOrEqualsOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTLessThanOrEqualsOperatorNodeOutput1 = astLessThanOrEqualsOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeLteOperator
		return nil
	case "mul_operator":
		astMultiplicationOperatorNodeOutput1 := new(ASTMultiplicationOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astMultiplicationOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mul_operator) type ASTMultiplicationOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTMultiplicationOperatorNodeOutput1 = astMultiplicationOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeMulOperator
		return nil
	case "neq_operator":
		astNotEqualsOperatorNodeOutput1 := new(ASTNotEqualsOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astNotEqualsOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == neq_operator) type ASTNotEqualsOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTNotEqualsOperatorNodeOutput1 = astNotEqualsOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeNeqOperator
		return nil
	case "number_literal":
		astNumberNodeOutput := new(ASTNumberNodeOutput)
		if err := utils.UnmarshalJSON(data, &astNumberNodeOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == number_literal) type ASTNumberNodeOutput within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTNumberNodeOutput = astNumberNodeOutput
		u.Type = ASTNodeOutputTypeNumberLiteral
		return nil
	case "or_operator":
		astOrOperatorNodeOutput1 := new(ASTOrOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astOrOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == or_operator) type ASTOrOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTOrOperatorNodeOutput1 = astOrOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeOrOperator
		return nil
	case "string_literal":
		astStringNodeOutput := new(ASTStringNodeOutput)
		if err := utils.UnmarshalJSON(data, &astStringNodeOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == string_literal) type ASTStringNodeOutput within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTStringNodeOutput = astStringNodeOutput
		u.Type = ASTNodeOutputTypeStringLiteral
		return nil
	case "sub_operator":
		astSubtractionOperatorNodeOutput1 := new(ASTSubtractionOperatorNodeOutput1)
		if err := utils.UnmarshalJSON(data, &astSubtractionOperatorNodeOutput1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == sub_operator) type ASTSubtractionOperatorNodeOutput1 within ASTNodeOutput: %w", string(data), err)
		}

		u.ASTSubtractionOperatorNodeOutput1 = astSubtractionOperatorNodeOutput1
		u.Type = ASTNodeOutputTypeSubOperator
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ASTNodeOutputTypeUnknown
		return nil
	}

}

func (u ASTNodeOutput) MarshalJSON() ([]byte, error) {
	if u.ASTStringNodeOutput != nil {
		return utils.MarshalJSON(u.ASTStringNodeOutput, "", true)
	}

	if u.ASTNumberNodeOutput != nil {
		return utils.MarshalJSON(u.ASTNumberNodeOutput, "", true)
	}

	if u.ASTBooleanNodeOutput != nil {
		return utils.MarshalJSON(u.ASTBooleanNodeOutput, "", true)
	}

	if u.ASTLLMNodeOutput != nil {
		return utils.MarshalJSON(u.ASTLLMNodeOutput, "", true)
	}

	if u.ASTDynamicVariableNodeOutput != nil {
		return utils.MarshalJSON(u.ASTDynamicVariableNodeOutput, "", true)
	}

	if u.ASTOrOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTOrOperatorNodeOutput1, "", true)
	}

	if u.ASTAndOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTAndOperatorNodeOutput1, "", true)
	}

	if u.ASTEqualsOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTEqualsOperatorNodeOutput1, "", true)
	}

	if u.ASTNotEqualsOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTNotEqualsOperatorNodeOutput1, "", true)
	}

	if u.ASTGreaterThanOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTGreaterThanOperatorNodeOutput1, "", true)
	}

	if u.ASTLessThanOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTLessThanOperatorNodeOutput1, "", true)
	}

	if u.ASTGreaterThanOrEqualsOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTGreaterThanOrEqualsOperatorNodeOutput1, "", true)
	}

	if u.ASTLessThanOrEqualsOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTLessThanOrEqualsOperatorNodeOutput1, "", true)
	}

	if u.ASTAdditionOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTAdditionOperatorNodeOutput1, "", true)
	}

	if u.ASTSubtractionOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTSubtractionOperatorNodeOutput1, "", true)
	}

	if u.ASTMultiplicationOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTMultiplicationOperatorNodeOutput1, "", true)
	}

	if u.ASTDivisionOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTDivisionOperatorNodeOutput1, "", true)
	}

	if u.ASTConditionalOperatorNodeOutput1 != nil {
		return utils.MarshalJSON(u.ASTConditionalOperatorNodeOutput1, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ASTNodeOutput: all fields are null")
}
