// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type ASTNumberNodeInput struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"number_literal" json:"type"`
	// Value of this literal.
	Value float64 `json:"value"`
}

func (a ASTNumberNodeInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ASTNumberNodeInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ASTNumberNodeInput) GetType() *string {
	return types.Pointer("number_literal")
}

func (a *ASTNumberNodeInput) GetValue() float64 {
	if a == nil {
		return 0.0
	}
	return a.Value
}
