// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type ASTOrOperatorNodeInput1 struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"or_operator" json:"type"`
	// Child nodes of the logical operator.
	Children []ASTNodeInput `json:"children"`
}

func (a ASTOrOperatorNodeInput1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ASTOrOperatorNodeInput1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ASTOrOperatorNodeInput1) GetType() *string {
	return types.Pointer("or_operator")
}

func (a *ASTOrOperatorNodeInput1) GetChildren() []ASTNodeInput {
	if a == nil {
		return []ASTNodeInput{}
	}
	return a.Children
}

// #region class-body-astoroperatornodeinput1
// #endregion class-body-astoroperatornodeinput1
