// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type AudioAnalysisResult struct {
	Title         string                                                `json:"title"`
	Description   string                                                `json:"description"`
	ContentType   optionalnullable.OptionalNullable[string]             `json:"content_type,omitzero"`
	OverallPacing optionalnullable.OptionalNullable[string]             `json:"overall_pacing,omitzero"`
	Segments      []AudioSegment                                        `json:"segments,omitzero"`
	KeyMoments    []AudioKeyMoment                                      `json:"key_moments,omitzero"`
	Transcription optionalnullable.OptionalNullable[AssetTranscription] `json:"transcription,omitzero"`
}

func (a AudioAnalysisResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioAnalysisResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudioAnalysisResult) GetTitle() string {
	if a == nil {
		return ""
	}
	return a.Title
}

func (a *AudioAnalysisResult) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *AudioAnalysisResult) GetContentType() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.ContentType
}

func (a *AudioAnalysisResult) GetOverallPacing() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.OverallPacing
}

func (a *AudioAnalysisResult) GetSegments() []AudioSegment {
	if a == nil {
		return nil
	}
	return a.Segments
}

func (a *AudioAnalysisResult) GetKeyMoments() []AudioKeyMoment {
	if a == nil {
		return nil
	}
	return a.KeyMoments
}

func (a *AudioAnalysisResult) GetTranscription() optionalnullable.OptionalNullable[AssetTranscription] {
	if a == nil {
		return nil
	}
	return a.Transcription
}
