// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// AuthConnectionLocator - Used to reference an auth connection from the workspace's auth connection store.
type AuthConnectionLocator struct {
	AuthConnectionID string `json:"auth_connection_id"`
}

func (a AuthConnectionLocator) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthConnectionLocator) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthConnectionLocator) GetAuthConnectionID() string {
	if a == nil {
		return ""
	}
	return a.AuthConnectionID
}
