// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchCallStatus string

const (
	BatchCallStatusPending    BatchCallStatus = "pending"
	BatchCallStatusInProgress BatchCallStatus = "in_progress"
	BatchCallStatusCompleted  BatchCallStatus = "completed"
	BatchCallStatusFailed     BatchCallStatus = "failed"
	BatchCallStatusCancelled  BatchCallStatus = "cancelled"
)

func (e BatchCallStatus) ToPointer() *BatchCallStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchCallStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "in_progress", "completed", "failed", "cancelled":
			return true
		}
	}
	return false
}
