// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type Sort string

const (
	SortAsc  Sort = "asc"
	SortDesc Sort = "desc"
)

func (e Sort) ToPointer() *Sort {
	return &e
}
func (e *Sort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = Sort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Sort: %v", v)
	}
}

type BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost struct {
	// Start of the time range as a Unix timestamp in milliseconds.
	StartTime *int64 `json:"start_time,omitzero"`
	// End of the time range as a Unix timestamp in milliseconds.
	EndTime *int64 `json:"end_time,omitzero"`
	Limit   *int64 `default:"100" json:"limit"`
	// Optional timestamp sort direction. If omitted, defaults to desc when end_time is provided, otherwise asc.
	Sort    *Sort          `json:"sort,omitzero"`
	Filters []ColumnFilter `json:"filters,omitzero"`
	Search  *string        `json:"search,omitzero"`
}

func (b BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetStartTime() *int64 {
	if b == nil {
		return nil
	}
	return b.StartTime
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetEndTime() *int64 {
	if b == nil {
		return nil
	}
	return b.EndTime
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetLimit() *int64 {
	if b == nil {
		return nil
	}
	return b.Limit
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetSort() *Sort {
	if b == nil {
		return nil
	}
	return b.Sort
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetFilters() []ColumnFilter {
	if b == nil {
		return nil
	}
	return b.Filters
}

func (b *BodyListAPIRequestsV1WorkspaceAnalyticsRequestsPost) GetSearch() *string {
	if b == nil {
		return nil
	}
	return b.Search
}

// #region class-body-bodylistapirequestsv1workspaceanalyticsrequestspost
// #endregion class-body-bodylistapirequestsv1workspaceanalyticsrequestspost
