// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostFile) GetFileName() string {
	if b == nil {
		return ""
	}
	return b.FileName
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostFile) GetContent() any {
	if b == nil {
		return nil
	}
	return b.Content
}

// #region class-body-bodyaddapronunciationdictionaryv1pronunciationdictionariesaddfromfilepostfile
// #endregion class-body-bodyaddapronunciationdictionaryv1pronunciationdictionariesaddfromfilepostfile

type BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess string

const (
	BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccessAdmin     BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess = "admin"
	BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccessEditor    BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess = "editor"
	BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccessCommenter BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess = "commenter"
	BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccessViewer    BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess = "viewer"
)

func (e BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess) ToPointer() *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess {
	return &e
}
func (e *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "admin":
		fallthrough
	case "editor":
		fallthrough
	case "commenter":
		fallthrough
	case "viewer":
		*e = BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess: %v", v)
	}
}

type BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost struct {
	// The name of the pronunciation dictionary, used for identification only.
	Name string `multipartForm:"name=name"`
	// A lexicon .pls file which we will use to initialize the project with.
	File *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostFile `multipartForm:"file,name=file"`
	// A description of the pronunciation dictionary, used for identification only.
	Description *string `multipartForm:"name=description"`
	// Should be one of 'admin', 'editor' or 'viewer'. If not provided, defaults to no access.
	WorkspaceAccess *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess `multipartForm:"name=workspace_access"`
}

func (b BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) GetFile() *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostFile {
	if b == nil {
		return nil
	}
	return b.File
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost) GetWorkspaceAccess() *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess {
	if b == nil {
		return nil
	}
	return b.WorkspaceAccess
}

// #region class-body-bodyaddapronunciationdictionaryv1pronunciationdictionariesaddfromfilepost
// #endregion class-body-bodyaddapronunciationdictionaryv1pronunciationdictionariesaddfromfilepost
