// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// BodySpeechToTextV1SpeechToTextPostModelID - The ID of the model to use for transcription.
type BodySpeechToTextV1SpeechToTextPostModelID string

const (
	BodySpeechToTextV1SpeechToTextPostModelIDScribeV1 BodySpeechToTextV1SpeechToTextPostModelID = "scribe_v1"
	BodySpeechToTextV1SpeechToTextPostModelIDScribeV2 BodySpeechToTextV1SpeechToTextPostModelID = "scribe_v2"
)

func (e BodySpeechToTextV1SpeechToTextPostModelID) ToPointer() *BodySpeechToTextV1SpeechToTextPostModelID {
	return &e
}
func (e *BodySpeechToTextV1SpeechToTextPostModelID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "scribe_v1":
		fallthrough
	case "scribe_v2":
		*e = BodySpeechToTextV1SpeechToTextPostModelID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BodySpeechToTextV1SpeechToTextPostModelID: %v", v)
	}
}

type BodySpeechToTextV1SpeechToTextPostFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (b *BodySpeechToTextV1SpeechToTextPostFile) GetFileName() string {
	if b == nil {
		return ""
	}
	return b.FileName
}

func (b *BodySpeechToTextV1SpeechToTextPostFile) GetContent() any {
	if b == nil {
		return nil
	}
	return b.Content
}

// #region class-body-bodyspeechtotextv1speechtotextpostfile
// #endregion class-body-bodyspeechtotextv1speechtotextpostfile

// TimestampsGranularity - The granularity of the timestamps in the transcription. 'word' provides word-level timestamps and 'character' provides character-level timestamps per word.
type TimestampsGranularity string

const (
	TimestampsGranularityNone      TimestampsGranularity = "none"
	TimestampsGranularityWord      TimestampsGranularity = "word"
	TimestampsGranularityCharacter TimestampsGranularity = "character"
)

func (e TimestampsGranularity) ToPointer() *TimestampsGranularity {
	return &e
}
func (e *TimestampsGranularity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "word":
		fallthrough
	case "character":
		*e = TimestampsGranularity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TimestampsGranularity: %v", v)
	}
}

// BodySpeechToTextV1SpeechToTextPostFileFormat - The format of input audio. Options are 'pcm_s16le_16' or 'other' For `pcm_s16le_16`, the input audio must be 16-bit PCM at a 16kHz sample rate, single channel (mono), and little-endian byte order. Latency will be lower than with passing an encoded waveform.
type BodySpeechToTextV1SpeechToTextPostFileFormat string

const (
	BodySpeechToTextV1SpeechToTextPostFileFormatPcmS16le16 BodySpeechToTextV1SpeechToTextPostFileFormat = "pcm_s16le_16"
	BodySpeechToTextV1SpeechToTextPostFileFormatOther      BodySpeechToTextV1SpeechToTextPostFileFormat = "other"
)

func (e BodySpeechToTextV1SpeechToTextPostFileFormat) ToPointer() *BodySpeechToTextV1SpeechToTextPostFileFormat {
	return &e
}
func (e *BodySpeechToTextV1SpeechToTextPostFileFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pcm_s16le_16":
		fallthrough
	case "other":
		*e = BodySpeechToTextV1SpeechToTextPostFileFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BodySpeechToTextV1SpeechToTextPostFileFormat: %v", v)
	}
}

type WebhookMetadataType string

const (
	WebhookMetadataTypeStr      WebhookMetadataType = "str"
	WebhookMetadataTypeMapOfAny WebhookMetadataType = "mapOfAny"
)

// WebhookMetadata - Optional metadata to be included in the webhook response. This should be a JSON string representing an object with a maximum depth of 2 levels and maximum size of 16KB. Useful for tracking internal IDs, job references, or other contextual information.
type WebhookMetadata struct {
	Str      *string        `queryParam:"inline" union:"member"`
	MapOfAny map[string]any `queryParam:"inline" union:"member"`

	Type WebhookMetadataType
}

func CreateWebhookMetadataStr(str string) WebhookMetadata {
	typ := WebhookMetadataTypeStr

	return WebhookMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateWebhookMetadataMapOfAny(mapOfAny map[string]any) WebhookMetadata {
	typ := WebhookMetadataTypeMapOfAny

	return WebhookMetadata{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *WebhookMetadata) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WebhookMetadataTypeStr,
			Value: &str,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WebhookMetadataTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for WebhookMetadata", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for WebhookMetadata", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(WebhookMetadataType)
	switch best.Type {
	case WebhookMetadataTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case WebhookMetadataTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for WebhookMetadata", string(data))
}

func (u WebhookMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type WebhookMetadata: all fields are null")
}

type EntityDetectionType string

const (
	EntityDetectionTypeStr        EntityDetectionType = "str"
	EntityDetectionTypeArrayOfStr EntityDetectionType = "arrayOfStr"
)

// EntityDetection - Detect entities in the transcript. Can be 'all' to detect all entities, a single entity type or category string, or a list of entity types/categories. Categories include 'pii', 'phi', 'pci', 'other', 'offensive_language'. When enabled, detected entities will be returned in the 'entities' field with their text, type, and character positions. Usage of this parameter will incur additional costs.
type EntityDetection struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type EntityDetectionType
}

func CreateEntityDetectionStr(str string) EntityDetection {
	typ := EntityDetectionTypeStr

	return EntityDetection{
		Str:  &str,
		Type: typ,
	}
}

func CreateEntityDetectionArrayOfStr(arrayOfStr []string) EntityDetection {
	typ := EntityDetectionTypeArrayOfStr

	return EntityDetection{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *EntityDetection) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntityDetectionTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntityDetectionTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityDetection", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityDetection", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EntityDetectionType)
	switch best.Type {
	case EntityDetectionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case EntityDetectionTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityDetection", string(data))
}

func (u EntityDetection) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type EntityDetection: all fields are null")
}

type EntityRedactionType string

const (
	EntityRedactionTypeStr        EntityRedactionType = "str"
	EntityRedactionTypeArrayOfStr EntityRedactionType = "arrayOfStr"
)

// EntityRedaction - Redact entities from the transcript text. Accepts the same format as entity_detection: 'all', a category ('pii', 'phi'), or specific entity types. Must be a subset of entity_detection. When redaction is enabled, the entities field will not be returned.
type EntityRedaction struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type EntityRedactionType
}

func CreateEntityRedactionStr(str string) EntityRedaction {
	typ := EntityRedactionTypeStr

	return EntityRedaction{
		Str:  &str,
		Type: typ,
	}
}

func CreateEntityRedactionArrayOfStr(arrayOfStr []string) EntityRedaction {
	typ := EntityRedactionTypeArrayOfStr

	return EntityRedaction{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *EntityRedaction) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntityRedactionTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EntityRedactionTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityRedaction", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityRedaction", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EntityRedactionType)
	switch best.Type {
	case EntityRedactionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case EntityRedactionTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityRedaction", string(data))
}

func (u EntityRedaction) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type EntityRedaction: all fields are null")
}

type BodySpeechToTextV1SpeechToTextPost struct {
	// The ID of the model to use for transcription.
	ModelID BodySpeechToTextV1SpeechToTextPostModelID `multipartForm:"name=model_id"`
	// The file to transcribe (100ms minimum audio length). All major audio and video formats are supported. Exactly one of the file or cloud_storage_url parameters must be provided. The file size must be less than 3.0GB.
	File *BodySpeechToTextV1SpeechToTextPostFile `multipartForm:"file,name=file"`
	// An ISO-639-1 or ISO-639-3 language_code corresponding to the language of the audio file. Can sometimes improve transcription performance if known beforehand. Defaults to null, in this case the language is predicted automatically.
	LanguageCode *string `multipartForm:"name=language_code"`
	// Whether to tag audio events like (laughter), (footsteps), etc. in the transcription.
	TagAudioEvents *bool `default:"true" multipartForm:"name=tag_audio_events"`
	// The maximum amount of speakers talking in the uploaded file. Can help with predicting who speaks when. The maximum amount of speakers that can be predicted is 32. Defaults to null, in this case the amount of speakers is set to the maximum value the model supports.
	NumSpeakers *int64 `multipartForm:"name=num_speakers"`
	// The granularity of the timestamps in the transcription. 'word' provides word-level timestamps and 'character' provides character-level timestamps per word.
	TimestampsGranularity *TimestampsGranularity `default:"word" multipartForm:"name=timestamps_granularity"`
	// Whether to annotate which speaker is currently talking in the uploaded file.
	Diarize *bool `default:"false" multipartForm:"name=diarize"`
	// Diarization threshold to apply during speaker diarization. A higher value means there will be a lower chance of one speaker being diarized as two different speakers but also a higher chance of two different speakers being diarized as one speaker (less total speakers predicted). A low value means there will be a higher chance of one speaker being diarized as two different speakers but also a lower chance of two different speakers being diarized as one speaker (more total speakers predicted). Can only be set when diarize=True and num_speakers=None. Defaults to None, in which case we will choose a threshold based on the model_id (0.22 usually).
	DiarizationThreshold *float64        `multipartForm:"name=diarization_threshold"`
	AdditionalFormats    []ExportOptions `multipartForm:"name=additional_formats,json"`
	// The format of input audio. Options are 'pcm_s16le_16' or 'other' For `pcm_s16le_16`, the input audio must be 16-bit PCM at a 16kHz sample rate, single channel (mono), and little-endian byte order. Latency will be lower than with passing an encoded waveform.
	FileFormat *BodySpeechToTextV1SpeechToTextPostFileFormat `default:"other" multipartForm:"name=file_format"`
	// The HTTPS URL of the file to transcribe. Exactly one of the file or cloud_storage_url parameters must be provided. The file must be accessible via HTTPS and the file size must be less than 2GB. Any valid HTTPS URL is accepted, including URLs from cloud storage providers (AWS S3, Google Cloud Storage, Cloudflare R2, etc.), CDNs, or any other HTTPS source. URLs can be pre-signed or include authentication tokens in query parameters.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	CloudStorageURL *string `multipartForm:"name=cloud_storage_url"`
	// The URL of an audio or video file to transcribe. Supports hosted video or audio files, YouTube video URLs, TikTok video URLs, and other video hosting services.
	SourceURL *string `multipartForm:"name=source_url"`
	// Whether to send the transcription result to configured speech-to-text webhooks.  If set the request will return early without the transcription, which will be delivered later via webhook.
	Webhook *bool `default:"false" multipartForm:"name=webhook"`
	// Optional specific webhook ID to send the transcription result to. Only valid when webhook is set to true. If not provided, transcription will be sent to all configured speech-to-text webhooks.
	WebhookID *string `multipartForm:"name=webhook_id"`
	// Controls the randomness of the transcription output. Accepts values between 0.0 and 2.0, where higher values result in more diverse and less deterministic results. If omitted, we will use a temperature based on the model you selected which is usually 0.
	Temperature *float64 `multipartForm:"name=temperature"`
	// If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed. Must be an integer between 0 and 2147483647.
	Seed *int64 `multipartForm:"name=seed"`
	// Whether the audio file contains multiple channels where each channel contains a single speaker. When enabled, each channel will be transcribed independently and the results will be combined. Each word in the response will include a 'channel_index' field indicating which channel it was spoken on. A maximum of 5 channels is supported.
	UseMultiChannel *bool `default:"false" multipartForm:"name=use_multi_channel"`
	// Optional metadata to be included in the webhook response. This should be a JSON string representing an object with a maximum depth of 2 levels and maximum size of 16KB. Useful for tracking internal IDs, job references, or other contextual information.
	WebhookMetadata *WebhookMetadata `multipartForm:"name=webhook_metadata,json"`
	// Detect entities in the transcript. Can be 'all' to detect all entities, a single entity type or category string, or a list of entity types/categories. Categories include 'pii', 'phi', 'pci', 'other', 'offensive_language'. When enabled, detected entities will be returned in the 'entities' field with their text, type, and character positions. Usage of this parameter will incur additional costs.
	EntityDetection *EntityDetection `multipartForm:"name=entity_detection"`
	// If true, the transcription will not have any filler words, false starts and non-speech sounds. Only supported with scribe_v2 model.
	NoVerbatim *bool `default:"false" multipartForm:"name=no_verbatim"`
	// Redact entities from the transcript text. Accepts the same format as entity_detection: 'all', a category ('pii', 'phi'), or specific entity types. Must be a subset of entity_detection. When redaction is enabled, the entities field will not be returned.
	EntityRedaction *EntityRedaction `multipartForm:"name=entity_redaction"`
	// How to format redacted entities. 'redacted' replaces with {REDACTED}, 'entity_type' replaces with {ENTITY_TYPE}, 'enumerated_entity_type' replaces with {ENTITY_TYPE_N} where N enumerates each occurrence. Only used when entity_redaction is set.
	EntityRedactionMode *string `default:"enumerated_entity_type" multipartForm:"name=entity_redaction_mode"`
	// A list of keyterms to bias the transcription towards.           The keyterms are words or phrases you want the model to recognise more accurately.           The number of keyterms cannot exceed 1000.           The length of each keyterm must be less than 50 characters.           Keyterms can contain at most 5 words (after normalisation).           For example ["hello", "world", "technical term"].           Usage of this parameter will incur additional costs.           When more than 100 keyterms are provided, a minimum billable duration of 20 seconds applies per request.
	Keyterms []string `multipartForm:"name=keyterms"`
}

func (b BodySpeechToTextV1SpeechToTextPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodySpeechToTextV1SpeechToTextPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetModelID() BodySpeechToTextV1SpeechToTextPostModelID {
	if b == nil {
		return BodySpeechToTextV1SpeechToTextPostModelID("")
	}
	return b.ModelID
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetFile() *BodySpeechToTextV1SpeechToTextPostFile {
	if b == nil {
		return nil
	}
	return b.File
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetLanguageCode() *string {
	if b == nil {
		return nil
	}
	return b.LanguageCode
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetTagAudioEvents() *bool {
	if b == nil {
		return nil
	}
	return b.TagAudioEvents
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetNumSpeakers() *int64 {
	if b == nil {
		return nil
	}
	return b.NumSpeakers
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetTimestampsGranularity() *TimestampsGranularity {
	if b == nil {
		return nil
	}
	return b.TimestampsGranularity
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetDiarize() *bool {
	if b == nil {
		return nil
	}
	return b.Diarize
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetDiarizationThreshold() *float64 {
	if b == nil {
		return nil
	}
	return b.DiarizationThreshold
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetAdditionalFormats() []ExportOptions {
	if b == nil {
		return nil
	}
	return b.AdditionalFormats
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetFileFormat() *BodySpeechToTextV1SpeechToTextPostFileFormat {
	if b == nil {
		return nil
	}
	return b.FileFormat
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetCloudStorageURL() *string {
	if b == nil {
		return nil
	}
	return b.CloudStorageURL
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetSourceURL() *string {
	if b == nil {
		return nil
	}
	return b.SourceURL
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetWebhook() *bool {
	if b == nil {
		return nil
	}
	return b.Webhook
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetWebhookID() *string {
	if b == nil {
		return nil
	}
	return b.WebhookID
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetTemperature() *float64 {
	if b == nil {
		return nil
	}
	return b.Temperature
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetSeed() *int64 {
	if b == nil {
		return nil
	}
	return b.Seed
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetUseMultiChannel() *bool {
	if b == nil {
		return nil
	}
	return b.UseMultiChannel
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetWebhookMetadata() *WebhookMetadata {
	if b == nil {
		return nil
	}
	return b.WebhookMetadata
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetEntityDetection() *EntityDetection {
	if b == nil {
		return nil
	}
	return b.EntityDetection
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetNoVerbatim() *bool {
	if b == nil {
		return nil
	}
	return b.NoVerbatim
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetEntityRedaction() *EntityRedaction {
	if b == nil {
		return nil
	}
	return b.EntityRedaction
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetEntityRedactionMode() *string {
	if b == nil {
		return nil
	}
	return b.EntityRedactionMode
}

func (b *BodySpeechToTextV1SpeechToTextPost) GetKeyterms() []string {
	if b == nil {
		return nil
	}
	return b.Keyterms
}

// #region class-body-bodyspeechtotextv1speechtotextpost
// #endregion class-body-bodyspeechtotextv1speechtotextpost
