// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type BodySoundGenerationV1SoundGenerationPost struct {
	// The text that will get converted into a sound effect.
	Text string `json:"text"`
	// Whether to create a sound effect that loops smoothly. Only available for the 'eleven_text_to_sound_v2 model'.
	Loop *bool `default:"false" json:"loop"`
	// The duration of the sound which will be generated in seconds. Must be at least 0.5 and at most 30. If set to None we will guess the optimal duration using the prompt. Defaults to None.
	DurationSeconds *float64 `json:"duration_seconds,omitzero"`
	// A higher prompt influence makes your generation follow the prompt more closely while also making generations less variable. Must be a value between 0 and 1. Defaults to 0.3.
	PromptInfluence *float64 `json:"prompt_influence,omitzero"`
	// The model ID to use for the sound generation.
	ModelID *string `default:"eleven_text_to_sound_v2" json:"model_id"`
}

func (b BodySoundGenerationV1SoundGenerationPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodySoundGenerationV1SoundGenerationPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodySoundGenerationV1SoundGenerationPost) GetText() string {
	if b == nil {
		return ""
	}
	return b.Text
}

func (b *BodySoundGenerationV1SoundGenerationPost) GetLoop() *bool {
	if b == nil {
		return nil
	}
	return b.Loop
}

func (b *BodySoundGenerationV1SoundGenerationPost) GetDurationSeconds() *float64 {
	if b == nil {
		return nil
	}
	return b.DurationSeconds
}

func (b *BodySoundGenerationV1SoundGenerationPost) GetPromptInfluence() *float64 {
	if b == nil {
		return nil
	}
	return b.PromptInfluence
}

func (b *BodySoundGenerationV1SoundGenerationPost) GetModelID() *string {
	if b == nil {
		return nil
	}
	return b.ModelID
}

// #region class-body-bodysoundgenerationv1soundgenerationpost
// #endregion class-body-bodysoundgenerationv1soundgenerationpost
