// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type BodyUpdateStudioProjectV1StudioProjectsProjectIDPost struct {
	// The name of the Studio project, used for identification only.
	Name string `json:"name"`
	// The voice_id that corresponds to the default voice used for new titles.
	DefaultTitleVoiceID string `json:"default_title_voice_id"`
	// The voice_id that corresponds to the default voice used for new paragraphs.
	DefaultParagraphVoiceID string `json:"default_paragraph_voice_id"`
	// An optional name of the author of the Studio project, this will be added as metadata to the mp3 file on Studio project or chapter download.
	Title optionalnullable.OptionalNullable[string] `json:"title,omitzero"`
	// An optional name of the author of the Studio project, this will be added as metadata to the mp3 file on Studio project or chapter download.
	Author optionalnullable.OptionalNullable[string] `json:"author,omitzero"`
	// An optional ISBN number of the Studio project you want to create, this will be added as metadata to the mp3 file on Studio project or chapter download.
	IsbnNumber optionalnullable.OptionalNullable[string] `json:"isbn_number,omitzero"`
	// When the Studio project is downloaded, should the returned audio have postprocessing in order to make it compliant with audiobook normalized volume requirements
	VolumeNormalization *bool `default:"false" json:"volume_normalization"`
}

func (b BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetDefaultTitleVoiceID() string {
	if b == nil {
		return ""
	}
	return b.DefaultTitleVoiceID
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetDefaultParagraphVoiceID() string {
	if b == nil {
		return ""
	}
	return b.DefaultParagraphVoiceID
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetTitle() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.Title
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetAuthor() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.Author
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetIsbnNumber() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.IsbnNumber
}

func (b *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) GetVolumeNormalization() *bool {
	if b == nil {
		return nil
	}
	return b.VolumeNormalization
}

// #region class-body-bodyupdatestudioprojectv1studioprojectsprojectidpost
// #endregion class-body-bodyupdatestudioprojectv1studioprojectsprojectidpost
