// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost struct {
	// ID of the version to branch from
	ParentVersionID string `json:"parent_version_id"`
	// Name of the branch. It is unique within the agent.
	Name string `json:"name"`
	// Description for the branch
	Description string `json:"description"`
	// Changes to apply to conversation config
	ConversationConfig optionalnullable.OptionalNullable[map[string]any] `json:"conversation_config,omitzero"`
	// Changes to apply to platform settings
	PlatformSettings optionalnullable.OptionalNullable[map[string]any] `json:"platform_settings,omitzero"`
	// Updated workflow definition
	Workflow optionalnullable.OptionalNullable[AgentWorkflowRequestModel] `json:"workflow,omitzero"`
}

func (b BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetParentVersionID() string {
	if b == nil {
		return ""
	}
	return b.ParentVersionID
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetConversationConfig() optionalnullable.OptionalNullable[map[string]any] {
	if b == nil {
		return nil
	}
	return b.ConversationConfig
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetPlatformSettings() optionalnullable.OptionalNullable[map[string]any] {
	if b == nil {
		return nil
	}
	return b.PlatformSettings
}

func (b *BodyCreateANewBranchV1ConvaiAgentsAgentIDBranchesPost) GetWorkflow() optionalnullable.OptionalNullable[AgentWorkflowRequestModel] {
	if b == nil {
		return nil
	}
	return b.Workflow
}

// #region class-body-bodycreateanewbranchv1convaiagentsagentidbranchespost
// #endregion class-body-bodycreateanewbranchv1convaiagentsagentidbranchespost
