// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostFile) GetFileName() string {
	if b == nil {
		return ""
	}
	return b.FileName
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostFile) GetContent() any {
	if b == nil {
		return nil
	}
	return b.Content
}

// #region class-body-bodyaddtoknowledgebasev1convaiknowledgebasepostfile
// #endregion class-body-bodyaddtoknowledgebasev1convaiknowledgebasepostfile

type BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost struct {
	// A custom, human-readable name for the document.
	Name *string `multipartForm:"name=name"`
	// URL to a page of documentation that the agent will have access to in order to interact with users.
	URL *string `multipartForm:"name=url"`
	// Documentation that the agent will have access to in order to interact with users.
	File *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostFile `multipartForm:"file,name=file"`
}

func (b BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost) GetURL() *string {
	if b == nil {
		return nil
	}
	return b.URL
}

func (b *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePost) GetFile() *BodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostFile {
	if b == nil {
		return nil
	}
	return b.File
}

// #region class-body-bodyaddtoknowledgebasev1convaiknowledgebasepost
// #endregion class-body-bodyaddtoknowledgebasev1convaiknowledgebasepost
