// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type BuiltInToolsInput struct {
	// The end call tool
	EndCall optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"end_call,omitzero"`
	// The language detection tool
	LanguageDetection optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"language_detection,omitzero"`
	// The transfer to agent tool
	TransferToAgent optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"transfer_to_agent,omitzero"`
	// The transfer to number tool
	TransferToNumber optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"transfer_to_number,omitzero"`
	// The skip turn tool
	SkipTurn optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"skip_turn,omitzero"`
	// The play DTMF tool
	PlayKeypadTouchTone optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"play_keypad_touch_tone,omitzero"`
	// The voicemail detection tool
	VoicemailDetection optionalnullable.OptionalNullable[SystemToolConfigInput] `json:"voicemail_detection,omitzero"`
}

func (b BuiltInToolsInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuiltInToolsInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuiltInToolsInput) GetEndCall() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.EndCall
}

func (b *BuiltInToolsInput) GetLanguageDetection() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.LanguageDetection
}

func (b *BuiltInToolsInput) GetTransferToAgent() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.TransferToAgent
}

func (b *BuiltInToolsInput) GetTransferToNumber() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.TransferToNumber
}

func (b *BuiltInToolsInput) GetSkipTurn() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.SkipTurn
}

func (b *BuiltInToolsInput) GetPlayKeypadTouchTone() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.PlayKeypadTouchTone
}

func (b *BuiltInToolsInput) GetVoicemailDetection() optionalnullable.OptionalNullable[SystemToolConfigInput] {
	if b == nil {
		return nil
	}
	return b.VoicemailDetection
}
