// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// CanvasPlacement - Defines asset positioning and transformation on canvas.
type CanvasPlacement struct {
	XRelative  *float64 `default:"0.5" json:"x_relative"`
	YRelative  *float64 `default:"0.5" json:"y_relative"`
	ScaleX     *float64 `default:"1" json:"scale_x"`
	ScaleY     *float64 `default:"1" json:"scale_y"`
	PivotX     *float64 `default:"0" json:"pivot_x"`
	PivotY     *float64 `default:"0" json:"pivot_y"`
	SkewX      *float64 `default:"0" json:"skew_x"`
	SkewY      *float64 `default:"0" json:"skew_y"`
	CropTop    *float64 `default:"0" json:"crop_top"`
	CropRight  *float64 `default:"0" json:"crop_right"`
	CropBottom *float64 `default:"0" json:"crop_bottom"`
	CropLeft   *float64 `default:"0" json:"crop_left"`
	FlipX      *bool    `default:"false" json:"flip_x"`
	FlipY      *bool    `default:"false" json:"flip_y"`
}

func (c CanvasPlacement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CanvasPlacement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CanvasPlacement) GetXRelative() *float64 {
	if c == nil {
		return nil
	}
	return c.XRelative
}

func (c *CanvasPlacement) GetYRelative() *float64 {
	if c == nil {
		return nil
	}
	return c.YRelative
}

func (c *CanvasPlacement) GetScaleX() *float64 {
	if c == nil {
		return nil
	}
	return c.ScaleX
}

func (c *CanvasPlacement) GetScaleY() *float64 {
	if c == nil {
		return nil
	}
	return c.ScaleY
}

func (c *CanvasPlacement) GetPivotX() *float64 {
	if c == nil {
		return nil
	}
	return c.PivotX
}

func (c *CanvasPlacement) GetPivotY() *float64 {
	if c == nil {
		return nil
	}
	return c.PivotY
}

func (c *CanvasPlacement) GetSkewX() *float64 {
	if c == nil {
		return nil
	}
	return c.SkewX
}

func (c *CanvasPlacement) GetSkewY() *float64 {
	if c == nil {
		return nil
	}
	return c.SkewY
}

func (c *CanvasPlacement) GetCropTop() *float64 {
	if c == nil {
		return nil
	}
	return c.CropTop
}

func (c *CanvasPlacement) GetCropRight() *float64 {
	if c == nil {
		return nil
	}
	return c.CropRight
}

func (c *CanvasPlacement) GetCropBottom() *float64 {
	if c == nil {
		return nil
	}
	return c.CropBottom
}

func (c *CanvasPlacement) GetCropLeft() *float64 {
	if c == nil {
		return nil
	}
	return c.CropLeft
}

func (c *CanvasPlacement) GetFlipX() *bool {
	if c == nil {
		return nil
	}
	return c.FlipX
}

func (c *CanvasPlacement) GetFlipY() *bool {
	if c == nil {
		return nil
	}
	return c.FlipY
}
