// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CaptionStyleSectionAnimationModelEnterType string

const (
	CaptionStyleSectionAnimationModelEnterTypeNone      CaptionStyleSectionAnimationModelEnterType = "none"
	CaptionStyleSectionAnimationModelEnterTypeFade      CaptionStyleSectionAnimationModelEnterType = "fade"
	CaptionStyleSectionAnimationModelEnterTypeScale     CaptionStyleSectionAnimationModelEnterType = "scale"
	CaptionStyleSectionAnimationModelEnterTypePop       CaptionStyleSectionAnimationModelEnterType = "pop"
	CaptionStyleSectionAnimationModelEnterTypeSlideUp   CaptionStyleSectionAnimationModelEnterType = "slide_up"
	CaptionStyleSectionAnimationModelEnterTypeSlideDown CaptionStyleSectionAnimationModelEnterType = "slide_down"
	CaptionStyleSectionAnimationModelEnterTypeSlam      CaptionStyleSectionAnimationModelEnterType = "slam"
	CaptionStyleSectionAnimationModelEnterTypeScaleDown CaptionStyleSectionAnimationModelEnterType = "scale_down"
	CaptionStyleSectionAnimationModelEnterTypeSlideIn   CaptionStyleSectionAnimationModelEnterType = "slide_in"
)

func (e CaptionStyleSectionAnimationModelEnterType) ToPointer() *CaptionStyleSectionAnimationModelEnterType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CaptionStyleSectionAnimationModelEnterType) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "fade", "scale", "pop", "slide_up", "slide_down", "slam", "scale_down", "slide_in":
			return true
		}
	}
	return false
}

type CaptionStyleSectionAnimationModelExitType string

const (
	CaptionStyleSectionAnimationModelExitTypeNone      CaptionStyleSectionAnimationModelExitType = "none"
	CaptionStyleSectionAnimationModelExitTypeFade      CaptionStyleSectionAnimationModelExitType = "fade"
	CaptionStyleSectionAnimationModelExitTypeScale     CaptionStyleSectionAnimationModelExitType = "scale"
	CaptionStyleSectionAnimationModelExitTypePop       CaptionStyleSectionAnimationModelExitType = "pop"
	CaptionStyleSectionAnimationModelExitTypeSlideUp   CaptionStyleSectionAnimationModelExitType = "slide_up"
	CaptionStyleSectionAnimationModelExitTypeSlideDown CaptionStyleSectionAnimationModelExitType = "slide_down"
	CaptionStyleSectionAnimationModelExitTypeSlam      CaptionStyleSectionAnimationModelExitType = "slam"
	CaptionStyleSectionAnimationModelExitTypeScaleDown CaptionStyleSectionAnimationModelExitType = "scale_down"
	CaptionStyleSectionAnimationModelExitTypeSlideIn   CaptionStyleSectionAnimationModelExitType = "slide_in"
)

func (e CaptionStyleSectionAnimationModelExitType) ToPointer() *CaptionStyleSectionAnimationModelExitType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CaptionStyleSectionAnimationModelExitType) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "fade", "scale", "pop", "slide_up", "slide_down", "slam", "scale_down", "slide_in":
			return true
		}
	}
	return false
}

type CaptionStyleSectionAnimationModel struct {
	EnterType CaptionStyleSectionAnimationModelEnterType `json:"enter_type"`
	ExitType  CaptionStyleSectionAnimationModelExitType  `json:"exit_type"`
}

func (c *CaptionStyleSectionAnimationModel) GetEnterType() CaptionStyleSectionAnimationModelEnterType {
	if c == nil {
		return CaptionStyleSectionAnimationModelEnterType("")
	}
	return c.EnterType
}

func (c *CaptionStyleSectionAnimationModel) GetExitType() CaptionStyleSectionAnimationModelExitType {
	if c == nil {
		return CaptionStyleSectionAnimationModelExitType("")
	}
	return c.ExitType
}
