// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// ChapterResponseModelState - The state of the chapter.
type ChapterResponseModelState string

const (
	ChapterResponseModelStateDefault    ChapterResponseModelState = "default"
	ChapterResponseModelStateConverting ChapterResponseModelState = "converting"
)

func (e ChapterResponseModelState) ToPointer() *ChapterResponseModelState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ChapterResponseModelState) IsExact() bool {
	if e != nil {
		switch *e {
		case "default", "converting":
			return true
		}
	}
	return false
}

type ChapterResponseModel struct {
	// The ID of the chapter.
	ChapterID string `json:"chapter_id"`
	// The name of the chapter.
	Name string `json:"name"`
	// The last conversion date of the chapter.
	LastConversionDateUnix *int64 `json:"last_conversion_date_unix,omitzero"`
	// The conversion progress of the chapter.
	ConversionProgress *float64 `json:"conversion_progress,omitzero"`
	// Whether the chapter can be downloaded.
	CanBeDownloaded bool `json:"can_be_downloaded"`
	// The state of the chapter.
	State ChapterResponseModelState `json:"state"`
	// Whether the chapter has a video.
	HasVideo *bool `json:"has_video,omitzero"`
	// Whether the chapter has any visual content (video, image, or text clips).
	HasVisualContent *bool `json:"has_visual_content,omitzero"`
	// List of voice ids used by the chapter
	VoiceIds []string `json:"voice_ids,omitzero"`
	// The statistics of the chapter.
	Statistics *ChapterStatisticsResponseModel `json:"statistics,omitzero"`
	// The last conversion error of the chapter.
	LastConversionError *string `json:"last_conversion_error,omitzero"`
}

func (c ChapterResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChapterResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChapterResponseModel) GetChapterID() string {
	if c == nil {
		return ""
	}
	return c.ChapterID
}

func (c *ChapterResponseModel) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ChapterResponseModel) GetLastConversionDateUnix() *int64 {
	if c == nil {
		return nil
	}
	return c.LastConversionDateUnix
}

func (c *ChapterResponseModel) GetConversionProgress() *float64 {
	if c == nil {
		return nil
	}
	return c.ConversionProgress
}

func (c *ChapterResponseModel) GetCanBeDownloaded() bool {
	if c == nil {
		return false
	}
	return c.CanBeDownloaded
}

func (c *ChapterResponseModel) GetState() ChapterResponseModelState {
	if c == nil {
		return ChapterResponseModelState("")
	}
	return c.State
}

func (c *ChapterResponseModel) GetHasVideo() *bool {
	if c == nil {
		return nil
	}
	return c.HasVideo
}

func (c *ChapterResponseModel) GetHasVisualContent() *bool {
	if c == nil {
		return nil
	}
	return c.HasVisualContent
}

func (c *ChapterResponseModel) GetVoiceIds() []string {
	if c == nil {
		return nil
	}
	return c.VoiceIds
}

func (c *ChapterResponseModel) GetStatistics() *ChapterStatisticsResponseModel {
	if c == nil {
		return nil
	}
	return c.Statistics
}

func (c *ChapterResponseModel) GetLastConversionError() *string {
	if c == nil {
		return nil
	}
	return c.LastConversionError
}
