// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ChunkType string

const (
	ChunkTypeGenerationChunkInput ChunkType = "GenerationChunk-Input"
	ChunkTypeAudioRefChunk        ChunkType = "AudioRefChunk"
)

type Chunk struct {
	GenerationChunkInput *GenerationChunkInput `queryParam:"inline" union:"member"`
	AudioRefChunk        *AudioRefChunk        `queryParam:"inline" union:"member"`

	Type ChunkType
}

func CreateChunkGenerationChunkInput(generationChunkInput GenerationChunkInput) Chunk {
	typ := ChunkTypeGenerationChunkInput

	return Chunk{
		GenerationChunkInput: &generationChunkInput,
		Type:                 typ,
	}
}

func CreateChunkAudioRefChunk(audioRefChunk AudioRefChunk) Chunk {
	typ := ChunkTypeAudioRefChunk

	return Chunk{
		AudioRefChunk: &audioRefChunk,
		Type:          typ,
	}
}

func (u *Chunk) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var generationChunkInput GenerationChunkInput = GenerationChunkInput{}
	if err := utils.UnmarshalJSON(data, &generationChunkInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChunkTypeGenerationChunkInput,
			Value: &generationChunkInput,
		})
	}

	var audioRefChunk AudioRefChunk = AudioRefChunk{}
	if err := utils.UnmarshalJSON(data, &audioRefChunk, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChunkTypeAudioRefChunk,
			Value: &audioRefChunk,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Chunk", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Chunk", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ChunkType)
	switch best.Type {
	case ChunkTypeGenerationChunkInput:
		u.GenerationChunkInput = best.Value.(*GenerationChunkInput)
		return nil
	case ChunkTypeAudioRefChunk:
		u.AudioRefChunk = best.Value.(*AudioRefChunk)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Chunk", string(data))
}

func (u Chunk) MarshalJSON() ([]byte, error) {
	if u.GenerationChunkInput != nil {
		return utils.MarshalJSON(u.GenerationChunkInput, "", true)
	}

	if u.AudioRefChunk != nil {
		return utils.MarshalJSON(u.AudioRefChunk, "", true)
	}

	return nil, errors.New("could not marshal union type Chunk: all fields are null")
}

// CompositionPlan - Composition plan for the `music_v2` model. Using this field with any other model will result in an error.
type CompositionPlan struct {
	// The chunks that make up the generation.
	Chunks []Chunk `json:"chunks"`
}

func (c CompositionPlan) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompositionPlan) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CompositionPlan) GetChunks() []Chunk {
	if c == nil {
		return []Chunk{}
	}
	return c.Chunks
}
