// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ConversationHistoryFeedbackCommonModel struct {
	Type         *ConversationFeedbackType `json:"type,omitzero"`
	OverallScore *UserFeedbackScore        `json:"overall_score,omitzero"`
	Likes        *int64                    `default:"0" json:"likes"`
	Dislikes     *int64                    `default:"0" json:"dislikes"`
	Rating       *int64                    `json:"rating,omitzero"`
	Comment      *string                   `json:"comment,omitzero"`
}

func (c ConversationHistoryFeedbackCommonModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationHistoryFeedbackCommonModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationHistoryFeedbackCommonModel) GetType() *ConversationFeedbackType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *ConversationHistoryFeedbackCommonModel) GetOverallScore() *UserFeedbackScore {
	if c == nil {
		return nil
	}
	return c.OverallScore
}

func (c *ConversationHistoryFeedbackCommonModel) GetLikes() *int64 {
	if c == nil {
		return nil
	}
	return c.Likes
}

func (c *ConversationHistoryFeedbackCommonModel) GetDislikes() *int64 {
	if c == nil {
		return nil
	}
	return c.Dislikes
}

func (c *ConversationHistoryFeedbackCommonModel) GetRating() *int64 {
	if c == nil {
		return nil
	}
	return c.Rating
}

func (c *ConversationHistoryFeedbackCommonModel) GetComment() *string {
	if c == nil {
		return nil
	}
	return c.Comment
}
