// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ConversationHistorySIPTrunkingPhoneCallModel struct {
	Direction      *TelephonyDirection `default:"inbound" json:"direction"`
	PhoneNumberID  string              `json:"phone_number_id"`
	AgentNumber    string              `json:"agent_number"`
	ExternalNumber string              `json:"external_number"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_                     string            `const:"sip_trunking" json:"type"`
	CallSid                   string            `json:"call_sid"`
	SipHeaderDynamicVariables map[string]string `json:"sip_header_dynamic_variables,omitzero"`
}

func (c ConversationHistorySIPTrunkingPhoneCallModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetDirection() *TelephonyDirection {
	if c == nil {
		return nil
	}
	return c.Direction
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetPhoneNumberID() string {
	if c == nil {
		return ""
	}
	return c.PhoneNumberID
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetAgentNumber() string {
	if c == nil {
		return ""
	}
	return c.AgentNumber
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetExternalNumber() string {
	if c == nil {
		return ""
	}
	return c.ExternalNumber
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetType() string {
	return "sip_trunking"
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetCallSid() string {
	if c == nil {
		return ""
	}
	return c.CallSid
}

func (c *ConversationHistorySIPTrunkingPhoneCallModel) GetSipHeaderDynamicVariables() map[string]string {
	if c == nil {
		return nil
	}
	return c.SipHeaderDynamicVariables
}
