// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ConversationHistoryTwilioPhoneCallModel struct {
	Direction      *TelephonyDirection `default:"inbound" json:"direction"`
	PhoneNumberID  string              `json:"phone_number_id"`
	AgentNumber    string              `json:"agent_number"`
	ExternalNumber string              `json:"external_number"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_     string `const:"twilio" json:"type"`
	StreamSid string `json:"stream_sid"`
	CallSid   string `json:"call_sid"`
}

func (c ConversationHistoryTwilioPhoneCallModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationHistoryTwilioPhoneCallModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetDirection() *TelephonyDirection {
	if c == nil {
		return nil
	}
	return c.Direction
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetPhoneNumberID() string {
	if c == nil {
		return ""
	}
	return c.PhoneNumberID
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetAgentNumber() string {
	if c == nil {
		return ""
	}
	return c.AgentNumber
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetExternalNumber() string {
	if c == nil {
		return ""
	}
	return c.ExternalNumber
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetType() string {
	return "twilio"
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetStreamSid() string {
	if c == nil {
		return ""
	}
	return c.StreamSid
}

func (c *ConversationHistoryTwilioPhoneCallModel) GetCallSid() string {
	if c == nil {
		return ""
	}
	return c.CallSid
}
