// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type ConversationDeletionSettings struct {
	DeletionTimeUnixSecs            optionalnullable.OptionalNullable[int64] `json:"deletion_time_unix_secs,omitzero"`
	DeletedLogsAtTimeUnixSecs       optionalnullable.OptionalNullable[int64] `json:"deleted_logs_at_time_unix_secs,omitzero"`
	DeletedAudioAtTimeUnixSecs      optionalnullable.OptionalNullable[int64] `json:"deleted_audio_at_time_unix_secs,omitzero"`
	DeletedTranscriptAtTimeUnixSecs optionalnullable.OptionalNullable[int64] `json:"deleted_transcript_at_time_unix_secs,omitzero"`
	DeleteTranscriptAndPii          *bool                                    `default:"false" json:"delete_transcript_and_pii"`
	DeleteAudio                     *bool                                    `default:"false" json:"delete_audio"`
}

func (c ConversationDeletionSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationDeletionSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationDeletionSettings) GetDeletionTimeUnixSecs() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.DeletionTimeUnixSecs
}

func (c *ConversationDeletionSettings) GetDeletedLogsAtTimeUnixSecs() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.DeletedLogsAtTimeUnixSecs
}

func (c *ConversationDeletionSettings) GetDeletedAudioAtTimeUnixSecs() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.DeletedAudioAtTimeUnixSecs
}

func (c *ConversationDeletionSettings) GetDeletedTranscriptAtTimeUnixSecs() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.DeletedTranscriptAtTimeUnixSecs
}

func (c *ConversationDeletionSettings) GetDeleteTranscriptAndPii() *bool {
	if c == nil {
		return nil
	}
	return c.DeleteTranscriptAndPii
}

func (c *ConversationDeletionSettings) GetDeleteAudio() *bool {
	if c == nil {
		return nil
	}
	return c.DeleteAudio
}
