// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ConversationConfigClientOverrideOutput struct {
	// Configuration for turn detection
	Turn *TurnConfigOverride `json:"turn,omitzero"`
	// Configuration for conversational text to speech
	Tts *TTSConversationalConfigOverride `json:"tts,omitzero"`
	// Configuration for conversational events
	Conversation *ConversationConfigOverride `json:"conversation,omitzero"`
	// Agent specific configuration
	Agent *AgentConfigOverrideOutput `json:"agent,omitzero"`
}

func (c ConversationConfigClientOverrideOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationConfigClientOverrideOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationConfigClientOverrideOutput) GetTurn() *TurnConfigOverride {
	if c == nil {
		return nil
	}
	return c.Turn
}

func (c *ConversationConfigClientOverrideOutput) GetTts() *TTSConversationalConfigOverride {
	if c == nil {
		return nil
	}
	return c.Tts
}

func (c *ConversationConfigClientOverrideOutput) GetConversation() *ConversationConfigOverride {
	if c == nil {
		return nil
	}
	return c.Conversation
}

func (c *ConversationConfigClientOverrideOutput) GetAgent() *AgentConfigOverrideOutput {
	if c == nil {
		return nil
	}
	return c.Agent
}
