// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type CreateToolCallUnitTestRequest struct {
	// Metadata of a conversation this test was created from (if applicable).
	FromConversationMetadata *TestFromConversationMetadataInput `json:"from_conversation_metadata,omitzero"`
	// Dynamic variables to replace in the agent config during testing
	DynamicVariables map[string]any                                  `json:"dynamic_variables,omitzero"`
	ChatHistory      []ConversationHistoryTranscriptCommonModelInput `json:"chat_history,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"tool" json:"type"`
	// How to evaluate the agent's tool call (if any). If empty, the tool call is not evaluated.
	ToolCallParameters *UnitTestToolCallEvaluationModelInput `json:"tool_call_parameters,omitzero"`
	// If set to True this test will pass if any tool call returned by the LLM matches the criteria. Otherwise it will fail if more than one tool is returned by the agent.
	CheckAnyToolMatches *bool  `json:"check_any_tool_matches,omitzero"`
	Name                string `json:"name"`
	// The ID of the parent folder. If not provided, the test will be created at the root level.
	ParentFolderID *string `json:"parent_folder_id,omitzero"`
}

func (c CreateToolCallUnitTestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateToolCallUnitTestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateToolCallUnitTestRequest) GetFromConversationMetadata() *TestFromConversationMetadataInput {
	if c == nil {
		return nil
	}
	return c.FromConversationMetadata
}

func (c *CreateToolCallUnitTestRequest) GetDynamicVariables() map[string]any {
	if c == nil {
		return nil
	}
	return c.DynamicVariables
}

func (c *CreateToolCallUnitTestRequest) GetChatHistory() []ConversationHistoryTranscriptCommonModelInput {
	if c == nil {
		return nil
	}
	return c.ChatHistory
}

func (c *CreateToolCallUnitTestRequest) GetType() *string {
	return types.Pointer("tool")
}

func (c *CreateToolCallUnitTestRequest) GetToolCallParameters() *UnitTestToolCallEvaluationModelInput {
	if c == nil {
		return nil
	}
	return c.ToolCallParameters
}

func (c *CreateToolCallUnitTestRequest) GetCheckAnyToolMatches() *bool {
	if c == nil {
		return nil
	}
	return c.CheckAnyToolMatches
}

func (c *CreateToolCallUnitTestRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateToolCallUnitTestRequest) GetParentFolderID() *string {
	if c == nil {
		return nil
	}
	return c.ParentFolderID
}
