// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

// CreateBearerAuthRequest - Request model for creating Bearer Auth connections - inherits common settings and includes sensitive fields
type CreateBearerAuthRequest struct {
	Name string `json:"name"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	authType *string `const:"bearer_auth" json:"auth_type"`
	Provider string  `json:"provider"`
	Token    string  `json:"token"`
}

func (c CreateBearerAuthRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBearerAuthRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateBearerAuthRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateBearerAuthRequest) GetAuthType() *string {
	return types.Pointer("bearer_auth")
}

func (c *CreateBearerAuthRequest) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CreateBearerAuthRequest) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}
