// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type DataCollectionResultCommonModel struct {
	DataCollectionID string                     `json:"data_collection_id"`
	Value            any                        `json:"value,omitzero"`
	JSONSchema       *LiteralJSONSchemaProperty `json:"json_schema,omitzero"`
	Rationale        string                     `json:"rationale"`
}

func (d DataCollectionResultCommonModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DataCollectionResultCommonModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DataCollectionResultCommonModel) GetDataCollectionID() string {
	if d == nil {
		return ""
	}
	return d.DataCollectionID
}

func (d *DataCollectionResultCommonModel) GetValue() any {
	if d == nil {
		return nil
	}
	return d.Value
}

func (d *DataCollectionResultCommonModel) GetJSONSchema() *LiteralJSONSchemaProperty {
	if d == nil {
		return nil
	}
	return d.JSONSchema
}

func (d *DataCollectionResultCommonModel) GetRationale() string {
	if d == nil {
		return ""
	}
	return d.Rationale
}
