// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteSampleResponseModel struct {
	// The status of the sample deletion request. If the request was successful, the status will be 'ok'. Otherwise an error message with status 500 will be returned.
	Status string `json:"status"`
}

func (d *DeleteSampleResponseModel) GetStatus() string {
	if d == nil {
		return ""
	}
	return d.Status
}
