// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// DependentIntegrationConnectionIdentifier - Identifier for an integration connection that depends on an auth connection
type DependentIntegrationConnectionIdentifier struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (d DependentIntegrationConnectionIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DependentIntegrationConnectionIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DependentIntegrationConnectionIdentifier) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DependentIntegrationConnectionIdentifier) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}
