// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type DynamicVariablesConfig struct {
	// A dictionary of dynamic variable placeholders and their values
	DynamicVariablePlaceholders map[string]any `json:"dynamic_variable_placeholders,omitzero"`
}

func (d DynamicVariablesConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DynamicVariablesConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DynamicVariablesConfig) GetDynamicVariablePlaceholders() map[string]any {
	if d == nil {
		return nil
	}
	return d.DynamicVariablePlaceholders
}
