// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type EndProcedureToolConfigInput struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	systemToolType *string                            `const:"end_procedure" json:"system_tool_type"`
	Procedures     map[string]ProcedureAtVersionInput `json:"procedures,omitzero"`
}

func (e EndProcedureToolConfigInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EndProcedureToolConfigInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EndProcedureToolConfigInput) GetSystemToolType() *string {
	return types.Pointer("end_procedure")
}

func (e *EndProcedureToolConfigInput) GetProcedures() map[string]ProcedureAtVersionInput {
	if e == nil {
		return nil
	}
	return e.Procedures
}
