// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ExtendedSubscriptionResponseModelCurrency string

const (
	ExtendedSubscriptionResponseModelCurrencyUsd ExtendedSubscriptionResponseModelCurrency = "usd"
	ExtendedSubscriptionResponseModelCurrencyEur ExtendedSubscriptionResponseModelCurrency = "eur"
	ExtendedSubscriptionResponseModelCurrencyInr ExtendedSubscriptionResponseModelCurrency = "inr"
)

func (e ExtendedSubscriptionResponseModelCurrency) ToPointer() *ExtendedSubscriptionResponseModelCurrency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ExtendedSubscriptionResponseModelCurrency) IsExact() bool {
	if e != nil {
		switch *e {
		case "usd", "eur", "inr":
			return true
		}
	}
	return false
}

type PendingChangeType string

const (
	PendingChangeTypePendingSubscriptionSwitchResponseModel PendingChangeType = "PendingSubscriptionSwitchResponseModel"
	PendingChangeTypePendingCancellationResponseModel       PendingChangeType = "PendingCancellationResponseModel"
)

// PendingChange - The pending change for the user.
type PendingChange struct {
	PendingSubscriptionSwitchResponseModel *PendingSubscriptionSwitchResponseModel `queryParam:"inline" union:"member"`
	PendingCancellationResponseModel       *PendingCancellationResponseModel       `queryParam:"inline" union:"member"`

	Type PendingChangeType
}

func CreatePendingChangePendingSubscriptionSwitchResponseModel(pendingSubscriptionSwitchResponseModel PendingSubscriptionSwitchResponseModel) PendingChange {
	typ := PendingChangeTypePendingSubscriptionSwitchResponseModel

	return PendingChange{
		PendingSubscriptionSwitchResponseModel: &pendingSubscriptionSwitchResponseModel,
		Type:                                   typ,
	}
}

func CreatePendingChangePendingCancellationResponseModel(pendingCancellationResponseModel PendingCancellationResponseModel) PendingChange {
	typ := PendingChangeTypePendingCancellationResponseModel

	return PendingChange{
		PendingCancellationResponseModel: &pendingCancellationResponseModel,
		Type:                             typ,
	}
}

func (u *PendingChange) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var pendingSubscriptionSwitchResponseModel PendingSubscriptionSwitchResponseModel = PendingSubscriptionSwitchResponseModel{}
	if err := utils.UnmarshalJSON(data, &pendingSubscriptionSwitchResponseModel, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PendingChangeTypePendingSubscriptionSwitchResponseModel,
			Value: &pendingSubscriptionSwitchResponseModel,
		})
	}

	var pendingCancellationResponseModel PendingCancellationResponseModel = PendingCancellationResponseModel{}
	if err := utils.UnmarshalJSON(data, &pendingCancellationResponseModel, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PendingChangeTypePendingCancellationResponseModel,
			Value: &pendingCancellationResponseModel,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PendingChange", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PendingChange", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PendingChangeType)
	switch best.Type {
	case PendingChangeTypePendingSubscriptionSwitchResponseModel:
		u.PendingSubscriptionSwitchResponseModel = best.Value.(*PendingSubscriptionSwitchResponseModel)
		return nil
	case PendingChangeTypePendingCancellationResponseModel:
		u.PendingCancellationResponseModel = best.Value.(*PendingCancellationResponseModel)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PendingChange", string(data))
}

func (u PendingChange) MarshalJSON() ([]byte, error) {
	if u.PendingSubscriptionSwitchResponseModel != nil {
		return utils.MarshalJSON(u.PendingSubscriptionSwitchResponseModel, "", true)
	}

	if u.PendingCancellationResponseModel != nil {
		return utils.MarshalJSON(u.PendingCancellationResponseModel, "", true)
	}

	return nil, errors.New("could not marshal union type PendingChange: all fields are null")
}

type ExtendedSubscriptionResponseModel struct {
	// The tier of the user's subscription.
	Tier string `json:"tier"`
	// The number of characters used by the user.
	CharacterCount int64 `json:"character_count"`
	// The maximum number of characters allowed in the current billing period.
	CharacterLimit int64 `json:"character_limit"`
	// Maximum number of characters that the character limit can be exceeded by. Managed by the workspace admin.
	MaxCharacterLimitExtension *int64 `json:"max_character_limit_extension"`
	// Whether the workspace is entitled to enter overages (usage-based billing).
	CanExtendCharacterLimit bool `json:"can_extend_character_limit"`
	// Whether the user is allowed to extend their character limit.
	AllowedToExtendCharacterLimit bool `json:"allowed_to_extend_character_limit"`
	// The Unix timestamp of the next character count reset.
	NextCharacterCountResetUnix *int64 `json:"next_character_count_reset_unix,omitzero"`
	// The number of voice slots used by the user.
	VoiceSlotsUsed int64 `json:"voice_slots_used"`
	// The number of professional voice slots used by the workspace/user if single seat.
	ProfessionalVoiceSlotsUsed int64 `json:"professional_voice_slots_used"`
	// The maximum number of voice slots allowed for the user.
	VoiceLimit int64 `json:"voice_limit"`
	// The maximum number of voice add/edits allowed for the user.
	MaxVoiceAddEdits *int64 `json:"max_voice_add_edits,omitzero"`
	// The number of voice add/edits used by the user.
	VoiceAddEditCounter int64 `json:"voice_add_edit_counter"`
	// The maximum number of professional voices allowed for the user.
	ProfessionalVoiceLimit int64 `json:"professional_voice_limit"`
	// Whether the user can extend their voice limit.
	CanExtendVoiceLimit bool `json:"can_extend_voice_limit"`
	// Whether the user can use instant voice cloning.
	CanUseInstantVoiceCloning bool `json:"can_use_instant_voice_cloning"`
	// Whether the user can use professional voice cloning.
	CanUseProfessionalVoiceCloning bool `json:"can_use_professional_voice_cloning"`
	// The currency of the user's subscription.
	Currency *ExtendedSubscriptionResponseModelCurrency `json:"currency,omitzero"`
	Status   SubscriptionStatusType                     `json:"status"`
	// The billing period of the user's subscription.
	BillingPeriod *BillingPeriod `json:"billing_period,omitzero"`
	// The character refresh period of the user's subscription.
	CharacterRefreshPeriod *CharacterRefreshPeriod `json:"character_refresh_period,omitzero"`
	// The next invoice for the user.
	NextInvoice *InvoiceResponseModel `json:"next_invoice,omitzero"`
	// The open invoices for the user.
	OpenInvoices []InvoiceResponseModel `json:"open_invoices"`
	// Whether the user has open invoices.
	HasOpenInvoices bool `json:"has_open_invoices"`
	// The pending change for the user.
	PendingChange *PendingChange `json:"pending_change,omitzero"`
	// True if any workspace owned by this user's auth account has redeemed the starter first-month discount coupon.
	HasUsedStarterCouponOnAccount *bool `default:"false" json:"has_used_starter_coupon_on_account"`
	// True if any workspace owned by this user's auth account has redeemed the creator first-month discount coupon.
	HasUsedCreatorCouponOnAccount *bool `default:"false" json:"has_used_creator_coupon_on_account"`
}

func (e ExtendedSubscriptionResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtendedSubscriptionResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtendedSubscriptionResponseModel) GetTier() string {
	if e == nil {
		return ""
	}
	return e.Tier
}

func (e *ExtendedSubscriptionResponseModel) GetCharacterCount() int64 {
	if e == nil {
		return 0
	}
	return e.CharacterCount
}

func (e *ExtendedSubscriptionResponseModel) GetCharacterLimit() int64 {
	if e == nil {
		return 0
	}
	return e.CharacterLimit
}

func (e *ExtendedSubscriptionResponseModel) GetMaxCharacterLimitExtension() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxCharacterLimitExtension
}

func (e *ExtendedSubscriptionResponseModel) GetCanExtendCharacterLimit() bool {
	if e == nil {
		return false
	}
	return e.CanExtendCharacterLimit
}

func (e *ExtendedSubscriptionResponseModel) GetAllowedToExtendCharacterLimit() bool {
	if e == nil {
		return false
	}
	return e.AllowedToExtendCharacterLimit
}

func (e *ExtendedSubscriptionResponseModel) GetNextCharacterCountResetUnix() *int64 {
	if e == nil {
		return nil
	}
	return e.NextCharacterCountResetUnix
}

func (e *ExtendedSubscriptionResponseModel) GetVoiceSlotsUsed() int64 {
	if e == nil {
		return 0
	}
	return e.VoiceSlotsUsed
}

func (e *ExtendedSubscriptionResponseModel) GetProfessionalVoiceSlotsUsed() int64 {
	if e == nil {
		return 0
	}
	return e.ProfessionalVoiceSlotsUsed
}

func (e *ExtendedSubscriptionResponseModel) GetVoiceLimit() int64 {
	if e == nil {
		return 0
	}
	return e.VoiceLimit
}

func (e *ExtendedSubscriptionResponseModel) GetMaxVoiceAddEdits() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxVoiceAddEdits
}

func (e *ExtendedSubscriptionResponseModel) GetVoiceAddEditCounter() int64 {
	if e == nil {
		return 0
	}
	return e.VoiceAddEditCounter
}

func (e *ExtendedSubscriptionResponseModel) GetProfessionalVoiceLimit() int64 {
	if e == nil {
		return 0
	}
	return e.ProfessionalVoiceLimit
}

func (e *ExtendedSubscriptionResponseModel) GetCanExtendVoiceLimit() bool {
	if e == nil {
		return false
	}
	return e.CanExtendVoiceLimit
}

func (e *ExtendedSubscriptionResponseModel) GetCanUseInstantVoiceCloning() bool {
	if e == nil {
		return false
	}
	return e.CanUseInstantVoiceCloning
}

func (e *ExtendedSubscriptionResponseModel) GetCanUseProfessionalVoiceCloning() bool {
	if e == nil {
		return false
	}
	return e.CanUseProfessionalVoiceCloning
}

func (e *ExtendedSubscriptionResponseModel) GetCurrency() *ExtendedSubscriptionResponseModelCurrency {
	if e == nil {
		return nil
	}
	return e.Currency
}

func (e *ExtendedSubscriptionResponseModel) GetStatus() SubscriptionStatusType {
	if e == nil {
		return SubscriptionStatusType("")
	}
	return e.Status
}

func (e *ExtendedSubscriptionResponseModel) GetBillingPeriod() *BillingPeriod {
	if e == nil {
		return nil
	}
	return e.BillingPeriod
}

func (e *ExtendedSubscriptionResponseModel) GetCharacterRefreshPeriod() *CharacterRefreshPeriod {
	if e == nil {
		return nil
	}
	return e.CharacterRefreshPeriod
}

func (e *ExtendedSubscriptionResponseModel) GetNextInvoice() *InvoiceResponseModel {
	if e == nil {
		return nil
	}
	return e.NextInvoice
}

func (e *ExtendedSubscriptionResponseModel) GetOpenInvoices() []InvoiceResponseModel {
	if e == nil {
		return []InvoiceResponseModel{}
	}
	return e.OpenInvoices
}

func (e *ExtendedSubscriptionResponseModel) GetHasOpenInvoices() bool {
	if e == nil {
		return false
	}
	return e.HasOpenInvoices
}

func (e *ExtendedSubscriptionResponseModel) GetPendingChange() *PendingChange {
	if e == nil {
		return nil
	}
	return e.PendingChange
}

func (e *ExtendedSubscriptionResponseModel) GetHasUsedStarterCouponOnAccount() *bool {
	if e == nil {
		return nil
	}
	return e.HasUsedStarterCouponOnAccount
}

func (e *ExtendedSubscriptionResponseModel) GetHasUsedCreatorCouponOnAccount() *bool {
	if e == nil {
		return nil
	}
	return e.HasUsedCreatorCouponOnAccount
}
