// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

// ExternalFolderSyncInfo - Metadata for a KB folder that mirrors an external source folder.
type ExternalFolderSyncInfo struct {
	Type ExternalSyncType `json:"type"`
	// Entity ID in the external system
	SourceEntityID string `json:"source_entity_id"`
	// Integration connection instance ID
	IntegrationConnectionID string `json:"integration_connection_id"`
	// KB folder ID of the sync root. None means this folder is the root.
	RootFolderID *string `json:"root_folder_id,omitzero"`
	// Opaque cursor for incremental sync, interpreted by the provider
	SyncCursor *string `json:"sync_cursor,omitzero"`
	// Unix timestamp of last completed sync
	LastSyncAt *int64 `json:"last_sync_at,omitzero"`
}

func (e ExternalFolderSyncInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExternalFolderSyncInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExternalFolderSyncInfo) GetType() ExternalSyncType {
	if e == nil {
		return ExternalSyncType("")
	}
	return e.Type
}

func (e *ExternalFolderSyncInfo) GetSourceEntityID() string {
	if e == nil {
		return ""
	}
	return e.SourceEntityID
}

func (e *ExternalFolderSyncInfo) GetIntegrationConnectionID() string {
	if e == nil {
		return ""
	}
	return e.IntegrationConnectionID
}

func (e *ExternalFolderSyncInfo) GetRootFolderID() *string {
	if e == nil {
		return nil
	}
	return e.RootFolderID
}

func (e *ExternalFolderSyncInfo) GetSyncCursor() *string {
	if e == nil {
		return nil
	}
	return e.SyncCursor
}

func (e *ExternalFolderSyncInfo) GetLastSyncAt() *int64 {
	if e == nil {
		return nil
	}
	return e.LastSyncAt
}
