// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"time"
)

// ExternalFileSyncInfo - Tracks the link back to the original file in an external source.
type ExternalFileSyncInfo struct {
	Type ExternalSyncType `json:"type"`
	// Entity ID in the external system
	SourceEntityID string `json:"source_entity_id"`
	// Integration connection instance ID
	IntegrationConnectionID string `json:"integration_connection_id"`
	// Folder ID in the external system this file was synced from
	SourceParentEntityID string `json:"source_parent_entity_id"`
	// Original MIME type in the external system
	SourceMimeType string `json:"source_mime_type"`
	// Last modified time from the external system
	SourceModifiedTime time.Time `json:"source_modified_time"`
	// KB folder ID of the sync root, used to query all entities under a sync tree
	RootFolderID *string `json:"root_folder_id,omitzero"`
}

func (e ExternalFileSyncInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExternalFileSyncInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExternalFileSyncInfo) GetType() ExternalSyncType {
	if e == nil {
		return ExternalSyncType("")
	}
	return e.Type
}

func (e *ExternalFileSyncInfo) GetSourceEntityID() string {
	if e == nil {
		return ""
	}
	return e.SourceEntityID
}

func (e *ExternalFileSyncInfo) GetIntegrationConnectionID() string {
	if e == nil {
		return ""
	}
	return e.IntegrationConnectionID
}

func (e *ExternalFileSyncInfo) GetSourceParentEntityID() string {
	if e == nil {
		return ""
	}
	return e.SourceParentEntityID
}

func (e *ExternalFileSyncInfo) GetSourceMimeType() string {
	if e == nil {
		return ""
	}
	return e.SourceMimeType
}

func (e *ExternalFileSyncInfo) GetSourceModifiedTime() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.SourceModifiedTime
}

func (e *ExternalFileSyncInfo) GetRootFolderID() *string {
	if e == nil {
		return nil
	}
	return e.RootFolderID
}
