// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetAgentTopicsResponseModel struct {
	Topics              []AgentTopicResponseModel `json:"topics"`
	WindowStartUnixSecs int64                     `json:"window_start_unix_secs"`
	WindowEndUnixSecs   int64                     `json:"window_end_unix_secs"`
}

func (g *GetAgentTopicsResponseModel) GetTopics() []AgentTopicResponseModel {
	if g == nil {
		return []AgentTopicResponseModel{}
	}
	return g.Topics
}

func (g *GetAgentTopicsResponseModel) GetWindowStartUnixSecs() int64 {
	if g == nil {
		return 0
	}
	return g.WindowStartUnixSecs
}

func (g *GetAgentTopicsResponseModel) GetWindowEndUnixSecs() int64 {
	if g == nil {
		return 0
	}
	return g.WindowEndUnixSecs
}
