// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
	"github.com/bdlilley/elevenlabs-go/types"
)

type GuardrailsV1Input struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	version         *string                                                     `const:"1" json:"version"`
	Focus           *FocusGuardrail                                             `json:"focus,omitzero"`
	PromptInjection *PromptInjectionGuardrail                                   `json:"prompt_injection,omitzero"`
	Content         *ContentGuardrailInput                                      `json:"content,omitzero"`
	Moderation      optionalnullable.OptionalNullable[ModerationGuardrailInput] `json:"moderation,omitzero"`
	// Container for custom guardrails, matching ModerationGuardrail pattern
	Custom *CustomGuardrailInput `json:"custom,omitzero"`
}

func (g GuardrailsV1Input) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GuardrailsV1Input) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GuardrailsV1Input) GetVersion() *string {
	return types.Pointer("1")
}

func (g *GuardrailsV1Input) GetFocus() *FocusGuardrail {
	if g == nil {
		return nil
	}
	return g.Focus
}

func (g *GuardrailsV1Input) GetPromptInjection() *PromptInjectionGuardrail {
	if g == nil {
		return nil
	}
	return g.PromptInjection
}

func (g *GuardrailsV1Input) GetContent() *ContentGuardrailInput {
	if g == nil {
		return nil
	}
	return g.Content
}

func (g *GuardrailsV1Input) GetModeration() optionalnullable.OptionalNullable[ModerationGuardrailInput] {
	if g == nil {
		return nil
	}
	return g.Moderation
}

func (g *GuardrailsV1Input) GetCustom() *CustomGuardrailInput {
	if g == nil {
		return nil
	}
	return g.Custom
}

// #region class-body-guardrailsv1input
// #endregion class-body-guardrailsv1input
