// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentIntentStatus string

const (
	PaymentIntentStatusCanceled              PaymentIntentStatus = "canceled"
	PaymentIntentStatusProcessing            PaymentIntentStatus = "processing"
	PaymentIntentStatusRequiresAction        PaymentIntentStatus = "requires_action"
	PaymentIntentStatusRequiresCapture       PaymentIntentStatus = "requires_capture"
	PaymentIntentStatusRequiresConfirmation  PaymentIntentStatus = "requires_confirmation"
	PaymentIntentStatusRequiresPaymentMethod PaymentIntentStatus = "requires_payment_method"
	PaymentIntentStatusSucceeded             PaymentIntentStatus = "succeeded"
)

func (e PaymentIntentStatus) ToPointer() *PaymentIntentStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentIntentStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "canceled", "processing", "requires_action", "requires_capture", "requires_confirmation", "requires_payment_method", "succeeded":
			return true
		}
	}
	return false
}

type PaymentIntentStatuss string

const (
	PaymentIntentStatussCanceled              PaymentIntentStatuss = "canceled"
	PaymentIntentStatussProcessing            PaymentIntentStatuss = "processing"
	PaymentIntentStatussRequiresAction        PaymentIntentStatuss = "requires_action"
	PaymentIntentStatussRequiresCapture       PaymentIntentStatuss = "requires_capture"
	PaymentIntentStatussRequiresConfirmation  PaymentIntentStatuss = "requires_confirmation"
	PaymentIntentStatussRequiresPaymentMethod PaymentIntentStatuss = "requires_payment_method"
	PaymentIntentStatussSucceeded             PaymentIntentStatuss = "succeeded"
)

func (e PaymentIntentStatuss) ToPointer() *PaymentIntentStatuss {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentIntentStatuss) IsExact() bool {
	if e != nil {
		switch *e {
		case "canceled", "processing", "requires_action", "requires_capture", "requires_confirmation", "requires_payment_method", "succeeded":
			return true
		}
	}
	return false
}

type InvoiceResponseModel struct {
	// The amount due in cents.
	AmountDueCents int64 `json:"amount_due_cents"`
	// The subtotal amount in cents before tax (exclusive of tax and discounts).
	SubtotalCents *int64 `json:"subtotal_cents,omitzero"`
	// The tax amount in cents.
	TaxCents *int64 `json:"tax_cents,omitzero"`
	// Deprecated. Use [discounts] instead. The discount applied to the invoice. E.g. [20.0f] for 20% off.
	DiscountPercentOff *float64 `json:"discount_percent_off,omitzero"`
	// Deprecated. Use [discounts] instead. The discount applied to the invoice. E.g. [20.0f] for 20 cents off.
	DiscountAmountOff *float64 `json:"discount_amount_off,omitzero"`
	// The discounts applied to the invoice.
	Discounts []DiscountResponseModel `json:"discounts"`
	// The Unix timestamp of the next payment attempt. -1 when there is no next payment attempt.
	NextPaymentAttemptUnix int64 `json:"next_payment_attempt_unix"`
	// Deprecated. Use [payment_intent_statusses] instead. The status of this invoice's first payment intent. None when there is no payment intent.
	PaymentIntentStatus *PaymentIntentStatus `json:"payment_intent_status"`
	// The statuses of this invoice's payment intents. Empty list when there are no payment intents.
	PaymentIntentStatusses []PaymentIntentStatuss `json:"payment_intent_statusses"`
}

func (i *InvoiceResponseModel) GetAmountDueCents() int64 {
	if i == nil {
		return 0
	}
	return i.AmountDueCents
}

func (i *InvoiceResponseModel) GetSubtotalCents() *int64 {
	if i == nil {
		return nil
	}
	return i.SubtotalCents
}

func (i *InvoiceResponseModel) GetTaxCents() *int64 {
	if i == nil {
		return nil
	}
	return i.TaxCents
}

func (i *InvoiceResponseModel) GetDiscountPercentOff() *float64 {
	if i == nil {
		return nil
	}
	return i.DiscountPercentOff
}

func (i *InvoiceResponseModel) GetDiscountAmountOff() *float64 {
	if i == nil {
		return nil
	}
	return i.DiscountAmountOff
}

func (i *InvoiceResponseModel) GetDiscounts() []DiscountResponseModel {
	if i == nil {
		return []DiscountResponseModel{}
	}
	return i.Discounts
}

func (i *InvoiceResponseModel) GetNextPaymentAttemptUnix() int64 {
	if i == nil {
		return 0
	}
	return i.NextPaymentAttemptUnix
}

func (i *InvoiceResponseModel) GetPaymentIntentStatus() *PaymentIntentStatus {
	if i == nil {
		return nil
	}
	return i.PaymentIntentStatus
}

func (i *InvoiceResponseModel) GetPaymentIntentStatusses() []PaymentIntentStatuss {
	if i == nil {
		return []PaymentIntentStatuss{}
	}
	return i.PaymentIntentStatusses
}
