// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KnowledgeBaseContentSearchResponseModel struct {
	Results    []KnowledgeBaseContentSearchResult `json:"results"`
	NextCursor *string                            `json:"next_cursor,omitzero"`
}

func (k *KnowledgeBaseContentSearchResponseModel) GetResults() []KnowledgeBaseContentSearchResult {
	if k == nil {
		return []KnowledgeBaseContentSearchResult{}
	}
	return k.Results
}

func (k *KnowledgeBaseContentSearchResponseModel) GetNextCursor() *string {
	if k == nil {
		return nil
	}
	return k.NextCursor
}
