// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LanguageAddedResponse struct {
	Version int64 `json:"version"`
}

func (l *LanguageAddedResponse) GetVersion() int64 {
	if l == nil {
		return 0
	}
	return l.Version
}
