// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListWhatsAppAccountsResponse struct {
	Items []GetWhatsAppAccountResponse `json:"items"`
}

func (l *ListWhatsAppAccountsResponse) GetItems() []GetWhatsAppAccountResponse {
	if l == nil {
		return []GetWhatsAppAccountResponse{}
	}
	return l.Items
}
