// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResponseMeta struct {
	Total    *int64 `json:"total,omitzero"`
	Page     *int64 `json:"page,omitzero"`
	PageSize *int64 `json:"page_size,omitzero"`
}

func (l *ListResponseMeta) GetTotal() *int64 {
	if l == nil {
		return nil
	}
	return l.Total
}

func (l *ListResponseMeta) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListResponseMeta) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}
