// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LLMListResponseModelInput struct {
	// List of all available LLM models that can be used with agents.
	Llms                     []LLMInfoModelInput       `json:"llms"`
	DefaultDeprecationConfig LLMDeprecationConfigModel `json:"default_deprecation_config"`
}

func (l *LLMListResponseModelInput) GetLlms() []LLMInfoModelInput {
	if l == nil {
		return []LLMInfoModelInput{}
	}
	return l.Llms
}

func (l *LLMListResponseModelInput) GetDefaultDeprecationConfig() LLMDeprecationConfigModel {
	if l == nil {
		return LLMDeprecationConfigModel{}
	}
	return l.DefaultDeprecationConfig
}
