// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type LLMUsageCalculatorLLMResponseModel struct {
	Llm            *Llm    `default:"gemini-2.5-flash" json:"llm"`
	PricePerMinute float64 `json:"price_per_minute"`
}

func (l LLMUsageCalculatorLLMResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LLMUsageCalculatorLLMResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LLMUsageCalculatorLLMResponseModel) GetLlm() *Llm {
	if l == nil {
		return nil
	}
	return l.Llm
}

func (l *LLMUsageCalculatorLLMResponseModel) GetPricePerMinute() float64 {
	if l == nil {
		return 0.0
	}
	return l.PricePerMinute
}
