// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LockReason string

const (
	LockReasonTrialEnded            LockReason = "trial_ended"
	LockReasonSubscriptionDowngrade LockReason = "subscription_downgrade"
	LockReasonExposedPublicly       LockReason = "exposed_publicly"
	LockReasonSelfDisabled          LockReason = "self_disabled"
)

func (e LockReason) ToPointer() *LockReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LockReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "trial_ended", "subscription_downgrade", "exposed_publicly", "self_disabled":
			return true
		}
	}
	return false
}
