// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
	"github.com/bdlilley/elevenlabs-go/types"
)

type MusicExploreSongSourceContext struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	sourceType         *string                                   `const:"music_explore_song" json:"source_type"`
	MusicExploreSongID string                                    `json:"music_explore_song_id"`
	Title              optionalnullable.OptionalNullable[string] `json:"title,omitzero"`
	Description        optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	Bpm                optionalnullable.OptionalNullable[int64]  `json:"bpm,omitzero"`
	Vocals             optionalnullable.OptionalNullable[string] `json:"vocals,omitzero"`
	Lyrics             optionalnullable.OptionalNullable[string] `json:"lyrics,omitzero"`
}

func (m MusicExploreSongSourceContext) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MusicExploreSongSourceContext) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MusicExploreSongSourceContext) GetSourceType() *string {
	return types.Pointer("music_explore_song")
}

func (m *MusicExploreSongSourceContext) GetMusicExploreSongID() string {
	if m == nil {
		return ""
	}
	return m.MusicExploreSongID
}

func (m *MusicExploreSongSourceContext) GetTitle() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.Title
}

func (m *MusicExploreSongSourceContext) GetDescription() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *MusicExploreSongSourceContext) GetBpm() optionalnullable.OptionalNullable[int64] {
	if m == nil {
		return nil
	}
	return m.Bpm
}

func (m *MusicExploreSongSourceContext) GetVocals() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.Vocals
}

func (m *MusicExploreSongSourceContext) GetLyrics() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.Lyrics
}
