// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderDeliverablesResponse struct {
	// The list of delivered files for the order. Empty if the order is not yet completed.
	Deliverables []DeliverableInfo `json:"deliverables"`
}

func (o *OrderDeliverablesResponse) GetDeliverables() []DeliverableInfo {
	if o == nil {
		return []DeliverableInfo{}
	}
	return o.Deliverables
}
