// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type OutboundSIPTrunkConfigRequestModel struct {
	// Hostname or IP the SIP INVITE is sent to.
	Address         string                  `json:"address"`
	Transport       *SIPTrunkTransportEnum  `default:"auto" json:"transport"`
	MediaEncryption *SIPMediaEncryptionEnum `default:"allowed" json:"media_encryption"`
	// SIP X-* headers for INVITE request. These headers are sent as-is and may help identify this call.
	Headers map[string]string `json:"headers,omitzero"`
	// Optional digest authentication credentials (username/password). If not provided, ACL authentication is assumed.
	Credentials optionalnullable.OptionalNullable[SIPTrunkCredentialsRequestModel] `json:"credentials,omitzero"`
}

func (o OutboundSIPTrunkConfigRequestModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundSIPTrunkConfigRequestModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundSIPTrunkConfigRequestModel) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *OutboundSIPTrunkConfigRequestModel) GetTransport() *SIPTrunkTransportEnum {
	if o == nil {
		return nil
	}
	return o.Transport
}

func (o *OutboundSIPTrunkConfigRequestModel) GetMediaEncryption() *SIPMediaEncryptionEnum {
	if o == nil {
		return nil
	}
	return o.MediaEncryption
}

func (o *OutboundSIPTrunkConfigRequestModel) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *OutboundSIPTrunkConfigRequestModel) GetCredentials() optionalnullable.OptionalNullable[SIPTrunkCredentialsRequestModel] {
	if o == nil {
		return nil
	}
	return o.Credentials
}
