// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type PendingBlocksMetadataModel struct {
	TargetGlobalOffsetMs *int64   `json:"target_global_offset_ms"`
	BlockIds             []string `json:"block_ids"`
}

func (p PendingBlocksMetadataModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendingBlocksMetadataModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendingBlocksMetadataModel) GetTargetGlobalOffsetMs() *int64 {
	if p == nil {
		return nil
	}
	return p.TargetGlobalOffsetMs
}

func (p *PendingBlocksMetadataModel) GetBlockIds() []string {
	if p == nil {
		return []string{}
	}
	return p.BlockIds
}
