// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

// NextTier - The tier to change to.
type NextTier string

const (
	NextTierFree               NextTier = "free"
	NextTierStarter            NextTier = "starter"
	NextTierCreator            NextTier = "creator"
	NextTierPro                NextTier = "pro"
	NextTierGrowingBusiness    NextTier = "growing_business"
	NextTierScale20240810      NextTier = "scale_2024_08_10"
	NextTierGrantTier120250723 NextTier = "grant_tier_1_2025_07_23"
	NextTierGrantTier220250723 NextTier = "grant_tier_2_2025_07_23"
	NextTierTrial              NextTier = "trial"
	NextTierEnterprise         NextTier = "enterprise"
)

func (e NextTier) ToPointer() *NextTier {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NextTier) IsExact() bool {
	if e != nil {
		switch *e {
		case "free", "starter", "creator", "pro", "growing_business", "scale_2024_08_10", "grant_tier_1_2025_07_23", "grant_tier_2_2025_07_23", "trial", "enterprise":
			return true
		}
	}
	return false
}

type PendingSubscriptionSwitchResponseModel struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	kind *string `const:"change" json:"kind"`
	// The tier to change to.
	NextTier          NextTier      `json:"next_tier"`
	NextBillingPeriod BillingPeriod `json:"next_billing_period"`
	// The timestamp of the change.
	TimestampSeconds int64 `json:"timestamp_seconds"`
}

func (p PendingSubscriptionSwitchResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendingSubscriptionSwitchResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendingSubscriptionSwitchResponseModel) GetKind() *string {
	return types.Pointer("change")
}

func (p *PendingSubscriptionSwitchResponseModel) GetNextTier() NextTier {
	if p == nil {
		return NextTier("")
	}
	return p.NextTier
}

func (p *PendingSubscriptionSwitchResponseModel) GetNextBillingPeriod() BillingPeriod {
	if p == nil {
		return BillingPeriod("")
	}
	return p.NextBillingPeriod
}

func (p *PendingSubscriptionSwitchResponseModel) GetTimestampSeconds() int64 {
	if p == nil {
		return 0
	}
	return p.TimestampSeconds
}
