// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type PhoneNumberDynamicVariableTransferDestination struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_       *string `const:"phone_dynamic_variable" json:"type"`
	PhoneNumber string  `json:"phone_number"`
}

func (p PhoneNumberDynamicVariableTransferDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PhoneNumberDynamicVariableTransferDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PhoneNumberDynamicVariableTransferDestination) GetType() *string {
	return types.Pointer("phone_dynamic_variable")
}

func (p *PhoneNumberDynamicVariableTransferDestination) GetPhoneNumber() string {
	if p == nil {
		return ""
	}
	return p.PhoneNumber
}
