// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type PodcastTextSource struct {
	// The type of source to create.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"text" json:"type"`
	// The text to create the podcast from.
	Text string `json:"text"`
}

func (p PodcastTextSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodcastTextSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodcastTextSource) GetType() string {
	return "text"
}

func (p *PodcastTextSource) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}
