// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type PrivacyConfigOutput struct {
	// Whether to record the conversation
	RecordVoice *bool `default:"true" json:"record_voice"`
	// The number of days to retain the conversation. -1 indicates there is no retention limit
	RetentionDays *int64 `default:"-1" json:"retention_days"`
	// Whether to delete the transcript and PII
	DeleteTranscriptAndPii *bool `default:"false" json:"delete_transcript_and_pii"`
	// Whether to delete the audio
	DeleteAudio *bool `default:"false" json:"delete_audio"`
	// Whether to apply the privacy settings to existing conversations
	ApplyToExistingConversations *bool `default:"false" json:"apply_to_existing_conversations"`
	// Whether to enable zero retention mode - no PII data is stored
	ZeroRetentionMode            *bool                               `default:"false" json:"zero_retention_mode"`
	ConversationHistoryRedaction *ConversationHistoryRedactionConfig `json:"conversation_history_redaction,omitzero"`
}

func (p PrivacyConfigOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrivacyConfigOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrivacyConfigOutput) GetRecordVoice() *bool {
	if p == nil {
		return nil
	}
	return p.RecordVoice
}

func (p *PrivacyConfigOutput) GetRetentionDays() *int64 {
	if p == nil {
		return nil
	}
	return p.RetentionDays
}

func (p *PrivacyConfigOutput) GetDeleteTranscriptAndPii() *bool {
	if p == nil {
		return nil
	}
	return p.DeleteTranscriptAndPii
}

func (p *PrivacyConfigOutput) GetDeleteAudio() *bool {
	if p == nil {
		return nil
	}
	return p.DeleteAudio
}

func (p *PrivacyConfigOutput) GetApplyToExistingConversations() *bool {
	if p == nil {
		return nil
	}
	return p.ApplyToExistingConversations
}

func (p *PrivacyConfigOutput) GetZeroRetentionMode() *bool {
	if p == nil {
		return nil
	}
	return p.ZeroRetentionMode
}

func (p *PrivacyConfigOutput) GetConversationHistoryRedaction() *ConversationHistoryRedactionConfig {
	if p == nil {
		return nil
	}
	return p.ConversationHistoryRedaction
}
