// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ProjectVideoThumbnailSheetResponseModel struct {
	StartThumbnailIndex int64  `json:"start_thumbnail_index"`
	ThumbnailCount      int64  `json:"thumbnail_count"`
	SignedCloudURL      string `json:"signed_cloud_url"`
}

func (p ProjectVideoThumbnailSheetResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectVideoThumbnailSheetResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProjectVideoThumbnailSheetResponseModel) GetStartThumbnailIndex() int64 {
	if p == nil {
		return 0
	}
	return p.StartThumbnailIndex
}

func (p *ProjectVideoThumbnailSheetResponseModel) GetThumbnailCount() int64 {
	if p == nil {
		return 0
	}
	return p.ThumbnailCount
}

func (p *ProjectVideoThumbnailSheetResponseModel) GetSignedCloudURL() string {
	if p == nil {
		return ""
	}
	return p.SignedCloudURL
}
