// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProjectCreationMetaResponseModelStatus - The status of the project creation action.
type ProjectCreationMetaResponseModelStatus string

const (
	ProjectCreationMetaResponseModelStatusPending  ProjectCreationMetaResponseModelStatus = "pending"
	ProjectCreationMetaResponseModelStatusCreating ProjectCreationMetaResponseModelStatus = "creating"
	ProjectCreationMetaResponseModelStatusFinished ProjectCreationMetaResponseModelStatus = "finished"
	ProjectCreationMetaResponseModelStatusFailed   ProjectCreationMetaResponseModelStatus = "failed"
)

func (e ProjectCreationMetaResponseModelStatus) ToPointer() *ProjectCreationMetaResponseModelStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProjectCreationMetaResponseModelStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "creating", "finished", "failed":
			return true
		}
	}
	return false
}

// ProjectCreationMetaResponseModelType - The type of the project creation action.
type ProjectCreationMetaResponseModelType string

const (
	ProjectCreationMetaResponseModelTypeBlank            ProjectCreationMetaResponseModelType = "blank"
	ProjectCreationMetaResponseModelTypeGeneratePodcast  ProjectCreationMetaResponseModelType = "generate_podcast"
	ProjectCreationMetaResponseModelTypeAutoAssignVoices ProjectCreationMetaResponseModelType = "auto_assign_voices"
	ProjectCreationMetaResponseModelTypeDubVideo         ProjectCreationMetaResponseModelType = "dub_video"
	ProjectCreationMetaResponseModelTypeImportSpeech     ProjectCreationMetaResponseModelType = "import_speech"
)

func (e ProjectCreationMetaResponseModelType) ToPointer() *ProjectCreationMetaResponseModelType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProjectCreationMetaResponseModelType) IsExact() bool {
	if e != nil {
		switch *e {
		case "blank", "generate_podcast", "auto_assign_voices", "dub_video", "import_speech":
			return true
		}
	}
	return false
}

type ProjectCreationMetaResponseModel struct {
	// The progress of the project creation.
	CreationProgress float64 `json:"creation_progress"`
	// The status of the project creation action.
	Status ProjectCreationMetaResponseModelStatus `json:"status"`
	// The type of the project creation action.
	Type ProjectCreationMetaResponseModelType `json:"type"`
}

func (p *ProjectCreationMetaResponseModel) GetCreationProgress() float64 {
	if p == nil {
		return 0.0
	}
	return p.CreationProgress
}

func (p *ProjectCreationMetaResponseModel) GetStatus() ProjectCreationMetaResponseModelStatus {
	if p == nil {
		return ProjectCreationMetaResponseModelStatus("")
	}
	return p.Status
}

func (p *ProjectCreationMetaResponseModel) GetType() ProjectCreationMetaResponseModelType {
	if p == nil {
		return ProjectCreationMetaResponseModelType("")
	}
	return p.Type
}
