// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type PronunciationDictionaryPhonemeRuleRequestModel struct {
	// The string to replace. Must be a non-empty string.
	StringToReplace string `json:"string_to_replace"`
	// Whether the rule should match case-sensitively.
	CaseSensitive *bool `default:"true" json:"case_sensitive"`
	// Whether the rule should only match at word boundaries.
	WordBoundaries *bool `default:"true" json:"word_boundaries"`
	// The type of the rule.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"phoneme" json:"type"`
	// The phoneme rule.
	Phoneme string `json:"phoneme"`
	// The alphabet to use with the phoneme rule.
	Alphabet string `json:"alphabet"`
}

func (p PronunciationDictionaryPhonemeRuleRequestModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetStringToReplace() string {
	if p == nil {
		return ""
	}
	return p.StringToReplace
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetCaseSensitive() *bool {
	if p == nil {
		return nil
	}
	return p.CaseSensitive
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetWordBoundaries() *bool {
	if p == nil {
		return nil
	}
	return p.WordBoundaries
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetType() string {
	return "phoneme"
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetPhoneme() string {
	if p == nil {
		return ""
	}
	return p.Phoneme
}

func (p *PronunciationDictionaryPhonemeRuleRequestModel) GetAlphabet() string {
	if p == nil {
		return ""
	}
	return p.Alphabet
}
