// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type RagConfigWorkflowOverride struct {
	Enabled        *bool               `json:"enabled,omitzero"`
	EmbeddingModel *EmbeddingModelEnum `default:"e5_mistral_7b_instruct" json:"embedding_model"`
	// Maximum vector distance of retrieved chunks.
	MaxVectorDistance *float64 `json:"max_vector_distance,omitzero"`
	// Maximum total length of document chunks retrieved from RAG.
	MaxDocumentsLength *int64 `json:"max_documents_length,omitzero"`
	// Maximum number of RAG document chunks to initially retrieve from the vector store. These are then further filtered by vector distance and total length.
	MaxRetrievedRagChunksCount *int64 `json:"max_retrieved_rag_chunks_count,omitzero"`
	// Number of candidates evaluated in ANN vector search. Higher number means better results, but higher latency. Minimum recommended value is 100. If disabled, the default value is used.
	NumCandidates *int64 `json:"num_candidates,omitzero"`
	// Custom prompt for rewriting user queries before RAG retrieval. The conversation history will be automatically appended at the end. If not set, the default prompt will be used.
	QueryRewritePromptOverride *string `json:"query_rewrite_prompt_override,omitzero"`
}

func (r RagConfigWorkflowOverride) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RagConfigWorkflowOverride) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RagConfigWorkflowOverride) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}

func (r *RagConfigWorkflowOverride) GetEmbeddingModel() *EmbeddingModelEnum {
	if r == nil {
		return nil
	}
	return r.EmbeddingModel
}

func (r *RagConfigWorkflowOverride) GetMaxVectorDistance() *float64 {
	if r == nil {
		return nil
	}
	return r.MaxVectorDistance
}

func (r *RagConfigWorkflowOverride) GetMaxDocumentsLength() *int64 {
	if r == nil {
		return nil
	}
	return r.MaxDocumentsLength
}

func (r *RagConfigWorkflowOverride) GetMaxRetrievedRagChunksCount() *int64 {
	if r == nil {
		return nil
	}
	return r.MaxRetrievedRagChunksCount
}

func (r *RagConfigWorkflowOverride) GetNumCandidates() *int64 {
	if r == nil {
		return nil
	}
	return r.NumCandidates
}

func (r *RagConfigWorkflowOverride) GetQueryRewritePromptOverride() *string {
	if r == nil {
		return nil
	}
	return r.QueryRewritePromptOverride
}
