// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type RestoreCalendarEventParams struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	smbToolType *string `const:"restore_calendar_event" json:"smb_tool_type"`
}

func (r RestoreCalendarEventParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RestoreCalendarEventParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RestoreCalendarEventParams) GetSmbToolType() *string {
	return types.Pointer("restore_calendar_event")
}
