// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SeverityID - OCSF Severity levels.
//
// Spec: https://schema.ocsf.io/1.6.0/objects/severity_id
type SeverityID int64

const (
	SeverityIDZero       SeverityID = 0
	SeverityIDOne        SeverityID = 1
	SeverityIDTwo        SeverityID = 2
	SeverityIDThree      SeverityID = 3
	SeverityIDFour       SeverityID = 4
	SeverityIDFive       SeverityID = 5
	SeverityIDSix        SeverityID = 6
	SeverityIDNinetyNine SeverityID = 99
)

func (e SeverityID) ToPointer() *SeverityID {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SeverityID) IsExact() bool {
	if e != nil {
		switch *e {
		case 0, 1, 2, 3, 4, 5, 6, 99:
			return true
		}
	}
	return false
}
