// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ShareOptionResponseModelType - The type of the principal: user, group, or service account (under 'key').
type ShareOptionResponseModelType string

const (
	ShareOptionResponseModelTypeUser  ShareOptionResponseModelType = "user"
	ShareOptionResponseModelTypeGroup ShareOptionResponseModelType = "group"
	ShareOptionResponseModelTypeKey   ShareOptionResponseModelType = "key"
)

func (e ShareOptionResponseModelType) ToPointer() *ShareOptionResponseModelType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ShareOptionResponseModelType) IsExact() bool {
	if e != nil {
		switch *e {
		case "user", "group", "key":
			return true
		}
	}
	return false
}

type ShareOptionResponseModel struct {
	// The name of the principal.
	Name string `json:"name"`
	// The ID of the principal.
	ID string `json:"id"`
	// The type of the principal: user, group, or service account (under 'key').
	Type ShareOptionResponseModelType `json:"type"`
}

func (s *ShareOptionResponseModel) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *ShareOptionResponseModel) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ShareOptionResponseModel) GetType() ShareOptionResponseModelType {
	if s == nil {
		return ShareOptionResponseModelType("")
	}
	return s.Type
}
