// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type SpeechEngineConversationInitiationClientDataConfig struct {
	// Whether the first message can be overridden by the client
	FirstMessage *bool `default:"false" json:"first_message"`
}

func (s SpeechEngineConversationInitiationClientDataConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpeechEngineConversationInitiationClientDataConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpeechEngineConversationInitiationClientDataConfig) GetFirstMessage() *bool {
	if s == nil {
		return nil
	}
	return s.FirstMessage
}
