// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

// SpeechToTextChunkResponseModel - Chunk-level detail of the transcription with timing information.
type SpeechToTextChunkResponseModel struct {
	// The detected language code (e.g. 'eng' for English).
	LanguageCode string `json:"language_code"`
	// The confidence score of the language detection (0 to 1).
	LanguageProbability float64 `json:"language_probability"`
	// The raw text of the transcription.
	Text string `json:"text"`
	// List of words with their timing information.
	Words []SpeechToTextWordResponseModel `json:"words"`
	// The channel index this transcript belongs to (for multichannel audio).
	ChannelIndex optionalnullable.OptionalNullable[int64] `json:"channel_index,omitzero"`
	// Requested additional formats of the transcript.
	AdditionalFormats optionalnullable.OptionalNullable[[]*AdditionalFormatResponseModel] `json:"additional_formats,omitzero"`
	// The transcription ID of the response.
	TranscriptionID optionalnullable.OptionalNullable[string] `json:"transcription_id,omitzero"`
	// List of detected entities with their text, type, and character positions in the transcript.
	Entities optionalnullable.OptionalNullable[[]DetectedEntity] `json:"entities,omitzero"`
	// The duration of the audio that was transcribed in seconds.
	AudioDurationSecs optionalnullable.OptionalNullable[float64] `json:"audio_duration_secs,omitzero"`
}

func (s SpeechToTextChunkResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpeechToTextChunkResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpeechToTextChunkResponseModel) GetLanguageCode() string {
	if s == nil {
		return ""
	}
	return s.LanguageCode
}

func (s *SpeechToTextChunkResponseModel) GetLanguageProbability() float64 {
	if s == nil {
		return 0.0
	}
	return s.LanguageProbability
}

func (s *SpeechToTextChunkResponseModel) GetText() string {
	if s == nil {
		return ""
	}
	return s.Text
}

func (s *SpeechToTextChunkResponseModel) GetWords() []SpeechToTextWordResponseModel {
	if s == nil {
		return []SpeechToTextWordResponseModel{}
	}
	return s.Words
}

func (s *SpeechToTextChunkResponseModel) GetChannelIndex() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.ChannelIndex
}

func (s *SpeechToTextChunkResponseModel) GetAdditionalFormats() optionalnullable.OptionalNullable[[]*AdditionalFormatResponseModel] {
	if s == nil {
		return nil
	}
	return s.AdditionalFormats
}

func (s *SpeechToTextChunkResponseModel) GetTranscriptionID() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.TranscriptionID
}

func (s *SpeechToTextChunkResponseModel) GetEntities() optionalnullable.OptionalNullable[[]DetectedEntity] {
	if s == nil {
		return nil
	}
	return s.Entities
}

func (s *SpeechToTextChunkResponseModel) GetAudioDurationSecs() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.AudioDurationSecs
}
