// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type SubtitleOrderItemRequest struct {
	// The type of order item.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	kind *string `const:"subtitles" json:"kind"`
	// The IDs of the uploaded media files to generate subtitles for.
	MediaIds []string `json:"media_ids"`
	// The language code of the source media (e.g. 'en', 'es').
	SourceLanguage string `json:"source_language"`
	// List of target language codes. Subtitles will be generated for each media file in each destination language.
	DestinationLanguages []string           `json:"destination_languages"`
	CueOptions           *CueOptionsRequest `json:"cue_options,omitzero"`
	// Whether subtitles should use SDH format, which includes descriptions for deaf and hard-of-hearing viewers.
	Sdh *bool `default:"false" json:"sdh"`
	// Optional free-text instructions for the subtitling team.
	Instructions *string `json:"instructions,omitzero"`
}

func (s SubtitleOrderItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubtitleOrderItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubtitleOrderItemRequest) GetKind() *string {
	return types.Pointer("subtitles")
}

func (s *SubtitleOrderItemRequest) GetMediaIds() []string {
	if s == nil {
		return []string{}
	}
	return s.MediaIds
}

func (s *SubtitleOrderItemRequest) GetSourceLanguage() string {
	if s == nil {
		return ""
	}
	return s.SourceLanguage
}

func (s *SubtitleOrderItemRequest) GetDestinationLanguages() []string {
	if s == nil {
		return []string{}
	}
	return s.DestinationLanguages
}

func (s *SubtitleOrderItemRequest) GetCueOptions() *CueOptionsRequest {
	if s == nil {
		return nil
	}
	return s.CueOptions
}

func (s *SubtitleOrderItemRequest) GetSdh() *bool {
	if s == nil {
		return nil
	}
	return s.Sdh
}

func (s *SubtitleOrderItemRequest) GetInstructions() *string {
	if s == nil {
		return nil
	}
	return s.Instructions
}
