// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type ToolUsageStatsResponseModel struct {
	// The total number of calls to the tool
	TotalCalls     *int64  `default:"0" json:"total_calls"`
	AvgLatencySecs float64 `json:"avg_latency_secs"`
}

func (t ToolUsageStatsResponseModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolUsageStatsResponseModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolUsageStatsResponseModel) GetTotalCalls() *int64 {
	if t == nil {
		return nil
	}
	return t.TotalCalls
}

func (t *ToolUsageStatsResponseModel) GetAvgLatencySecs() float64 {
	if t == nil {
		return 0.0
	}
	return t.AvgLatencySecs
}
