// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ToolCallSoundType - Predefined tool call sound types.
type ToolCallSoundType string

const (
	ToolCallSoundTypeTyping    ToolCallSoundType = "typing"
	ToolCallSoundTypeElevator1 ToolCallSoundType = "elevator1"
	ToolCallSoundTypeElevator2 ToolCallSoundType = "elevator2"
	ToolCallSoundTypeElevator3 ToolCallSoundType = "elevator3"
	ToolCallSoundTypeElevator4 ToolCallSoundType = "elevator4"
)

func (e ToolCallSoundType) ToPointer() *ToolCallSoundType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ToolCallSoundType) IsExact() bool {
	if e != nil {
		switch *e {
		case "typing", "elevator1", "elevator2", "elevator3", "elevator4":
			return true
		}
	}
	return false
}
