// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

// Tool - Definition for a tool the client can call.
type Tool struct {
	Name                 string                                             `json:"name"`
	Title                optionalnullable.OptionalNullable[string]          `json:"title,omitzero"`
	Description          optionalnullable.OptionalNullable[string]          `json:"description,omitzero"`
	InputSchema          map[string]any                                     `json:"inputSchema"`
	OutputSchema         optionalnullable.OptionalNullable[map[string]any]  `json:"outputSchema,omitzero"`
	Annotations          optionalnullable.OptionalNullable[ToolAnnotations] `json:"annotations,omitzero"`
	Meta                 optionalnullable.OptionalNullable[map[string]any]  `json:"_meta,omitzero"`
	AdditionalProperties map[string]any                                     `additionalProperties:"true" json:"-"`
}

func (t Tool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Tool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Tool) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Tool) GetTitle() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Title
}

func (t *Tool) GetDescription() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Tool) GetInputSchema() map[string]any {
	if t == nil {
		return map[string]any{}
	}
	return t.InputSchema
}

func (t *Tool) GetOutputSchema() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.OutputSchema
}

func (t *Tool) GetAnnotations() optionalnullable.OptionalNullable[ToolAnnotations] {
	if t == nil {
		return nil
	}
	return t.Annotations
}

func (t *Tool) GetMeta() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Meta
}

func (t *Tool) GetAdditionalProperties() map[string]any {
	if t == nil {
		return nil
	}
	return t.AdditionalProperties
}
