// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ToolCallSoundBehavior - Determines how the tool call sound should be played.
type ToolCallSoundBehavior string

const (
	ToolCallSoundBehaviorAuto   ToolCallSoundBehavior = "auto"
	ToolCallSoundBehaviorAlways ToolCallSoundBehavior = "always"
)

func (e ToolCallSoundBehavior) ToPointer() *ToolCallSoundBehavior {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ToolCallSoundBehavior) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "always":
			return true
		}
	}
	return false
}
