// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type TransferToNumberResultTwilioSuccessModel struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resultType *string `const:"transfer_to_number_twilio_success" json:"result_type"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	status         *string `const:"success" json:"status"`
	TransferNumber string  `json:"transfer_number"`
	Reason         *string `json:"reason,omitzero"`
	ClientMessage  *string `json:"client_message,omitzero"`
	AgentMessage   string  `json:"agent_message"`
	ConferenceName string  `json:"conference_name"`
	PostDialDigits *string `json:"post_dial_digits,omitzero"`
	Note           *string `json:"note,omitzero"`
}

func (t TransferToNumberResultTwilioSuccessModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferToNumberResultTwilioSuccessModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransferToNumberResultTwilioSuccessModel) GetResultType() *string {
	return types.Pointer("transfer_to_number_twilio_success")
}

func (t *TransferToNumberResultTwilioSuccessModel) GetStatus() *string {
	return types.Pointer("success")
}

func (t *TransferToNumberResultTwilioSuccessModel) GetTransferNumber() string {
	if t == nil {
		return ""
	}
	return t.TransferNumber
}

func (t *TransferToNumberResultTwilioSuccessModel) GetReason() *string {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TransferToNumberResultTwilioSuccessModel) GetClientMessage() *string {
	if t == nil {
		return nil
	}
	return t.ClientMessage
}

func (t *TransferToNumberResultTwilioSuccessModel) GetAgentMessage() string {
	if t == nil {
		return ""
	}
	return t.AgentMessage
}

func (t *TransferToNumberResultTwilioSuccessModel) GetConferenceName() string {
	if t == nil {
		return ""
	}
	return t.ConferenceName
}

func (t *TransferToNumberResultTwilioSuccessModel) GetPostDialDigits() *string {
	if t == nil {
		return nil
	}
	return t.PostDialDigits
}

func (t *TransferToNumberResultTwilioSuccessModel) GetNote() *string {
	if t == nil {
		return nil
	}
	return t.Note
}
