// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type BranchInfoType string

const (
	BranchInfoTypeDefaultingToMain BranchInfoType = "defaulting_to_main"
	BranchInfoTypeTrafficSplit     BranchInfoType = "traffic_split"
)

type BranchInfo struct {
	TransferBranchInfoTrafficSplit     *TransferBranchInfoTrafficSplit     `queryParam:"inline" union:"member"`
	TransferBranchInfoDefaultingToMain *TransferBranchInfoDefaultingToMain `queryParam:"inline" union:"member"`

	Type BranchInfoType
}

func CreateBranchInfoDefaultingToMain(defaultingToMain TransferBranchInfoDefaultingToMain) BranchInfo {
	typ := BranchInfoTypeDefaultingToMain

	return BranchInfo{
		TransferBranchInfoDefaultingToMain: &defaultingToMain,
		Type:                               typ,
	}
}

func CreateBranchInfoTrafficSplit(trafficSplit TransferBranchInfoTrafficSplit) BranchInfo {
	typ := BranchInfoTypeTrafficSplit

	return BranchInfo{
		TransferBranchInfoTrafficSplit: &trafficSplit,
		Type:                           typ,
	}
}

func (u *BranchInfo) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		BranchReason string `json:"branch_reason"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.BranchReason {
	case "defaulting_to_main":
		transferBranchInfoDefaultingToMain := new(TransferBranchInfoDefaultingToMain)
		if err := utils.UnmarshalJSON(data, &transferBranchInfoDefaultingToMain, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (BranchReason == defaulting_to_main) type TransferBranchInfoDefaultingToMain within BranchInfo: %w", string(data), err)
		}

		u.TransferBranchInfoDefaultingToMain = transferBranchInfoDefaultingToMain
		u.Type = BranchInfoTypeDefaultingToMain
		return nil
	case "traffic_split":
		transferBranchInfoTrafficSplit := new(TransferBranchInfoTrafficSplit)
		if err := utils.UnmarshalJSON(data, &transferBranchInfoTrafficSplit, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (BranchReason == traffic_split) type TransferBranchInfoTrafficSplit within BranchInfo: %w", string(data), err)
		}

		u.TransferBranchInfoTrafficSplit = transferBranchInfoTrafficSplit
		u.Type = BranchInfoTypeTrafficSplit
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BranchInfo", string(data))
}

func (u BranchInfo) MarshalJSON() ([]byte, error) {
	if u.TransferBranchInfoTrafficSplit != nil {
		return utils.MarshalJSON(u.TransferBranchInfoTrafficSplit, "", true)
	}

	if u.TransferBranchInfoDefaultingToMain != nil {
		return utils.MarshalJSON(u.TransferBranchInfoDefaultingToMain, "", true)
	}

	return nil, errors.New("could not marshal union type BranchInfo: all fields are null")
}

type TransferToAgentToolResultSuccessModel struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resultType *string `const:"transfer_to_agent_success" json:"result_type"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	status                             *string     `const:"success" json:"status"`
	FromAgent                          string      `json:"from_agent"`
	ToAgent                            string      `json:"to_agent"`
	Condition                          string      `json:"condition"`
	DelayMs                            *int64      `default:"0" json:"delay_ms"`
	TransferMessage                    *string     `json:"transfer_message,omitzero"`
	EnableTransferredAgentFirstMessage *bool       `default:"false" json:"enable_transferred_agent_first_message"`
	BranchInfo                         *BranchInfo `json:"branch_info,omitzero"`
}

func (t TransferToAgentToolResultSuccessModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferToAgentToolResultSuccessModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransferToAgentToolResultSuccessModel) GetResultType() *string {
	return types.Pointer("transfer_to_agent_success")
}

func (t *TransferToAgentToolResultSuccessModel) GetStatus() *string {
	return types.Pointer("success")
}

func (t *TransferToAgentToolResultSuccessModel) GetFromAgent() string {
	if t == nil {
		return ""
	}
	return t.FromAgent
}

func (t *TransferToAgentToolResultSuccessModel) GetToAgent() string {
	if t == nil {
		return ""
	}
	return t.ToAgent
}

func (t *TransferToAgentToolResultSuccessModel) GetCondition() string {
	if t == nil {
		return ""
	}
	return t.Condition
}

func (t *TransferToAgentToolResultSuccessModel) GetDelayMs() *int64 {
	if t == nil {
		return nil
	}
	return t.DelayMs
}

func (t *TransferToAgentToolResultSuccessModel) GetTransferMessage() *string {
	if t == nil {
		return nil
	}
	return t.TransferMessage
}

func (t *TransferToAgentToolResultSuccessModel) GetEnableTransferredAgentFirstMessage() *bool {
	if t == nil {
		return nil
	}
	return t.EnableTransferredAgentFirstMessage
}

func (t *TransferToAgentToolResultSuccessModel) GetBranchInfo() *BranchInfo {
	if t == nil {
		return nil
	}
	return t.BranchInfo
}

func (t *TransferToAgentToolResultSuccessModel) GetBranchInfoDefaultingToMain() *TransferBranchInfoDefaultingToMain {
	if v := t.GetBranchInfo(); v != nil {
		return v.TransferBranchInfoDefaultingToMain
	}
	return nil
}

func (t *TransferToAgentToolResultSuccessModel) GetBranchInfoTrafficSplit() *TransferBranchInfoTrafficSplit {
	if v := t.GetBranchInfo(); v != nil {
		return v.TransferBranchInfoTrafficSplit
	}
	return nil
}
