// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TTSOptimizeStreamingLatency int64

const (
	TTSOptimizeStreamingLatencyZero  TTSOptimizeStreamingLatency = 0
	TTSOptimizeStreamingLatencyOne   TTSOptimizeStreamingLatency = 1
	TTSOptimizeStreamingLatencyTwo   TTSOptimizeStreamingLatency = 2
	TTSOptimizeStreamingLatencyThree TTSOptimizeStreamingLatency = 3
	TTSOptimizeStreamingLatencyFour  TTSOptimizeStreamingLatency = 4
)

func (e TTSOptimizeStreamingLatency) ToPointer() *TTSOptimizeStreamingLatency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TTSOptimizeStreamingLatency) IsExact() bool {
	if e != nil {
		switch *e {
		case 0, 1, 2, 3, 4:
			return true
		}
	}
	return false
}
