// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type TurnConfigOverrideConfig struct {
	SoftTimeoutConfig *SoftTimeoutConfigOverrideConfig `json:"soft_timeout_config,omitzero"`
}

func (t TurnConfigOverrideConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TurnConfigOverrideConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TurnConfigOverrideConfig) GetSoftTimeoutConfig() *SoftTimeoutConfigOverrideConfig {
	if t == nil {
		return nil
	}
	return t.SoftTimeoutConfig
}
