// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type UnitTestToolCallEvaluationModelInput struct {
	// Parameters to evaluate for the agent's tool call. If empty, the tool call parameters are not evaluated.
	Parameters []UnitTestToolCallParameter `json:"parameters,omitzero"`
	// The tool to evaluate a call against.
	ReferencedTool *ReferencedToolCommonModel `json:"referenced_tool,omitzero"`
	// Whether to verify that the tool was NOT called.
	VerifyAbsence *bool `default:"false" json:"verify_absence"`
	// Configuration for testing workflow node transitions. When set, the test will verify the agent transitions to the specified workflow node.
	WorkflowNodeTransition *UnitTestWorkflowNodeTransitionEvaluationNodeID `json:"workflow_node_transition,omitzero"`
}

func (u UnitTestToolCallEvaluationModelInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnitTestToolCallEvaluationModelInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UnitTestToolCallEvaluationModelInput) GetParameters() []UnitTestToolCallParameter {
	if u == nil {
		return nil
	}
	return u.Parameters
}

func (u *UnitTestToolCallEvaluationModelInput) GetReferencedTool() *ReferencedToolCommonModel {
	if u == nil {
		return nil
	}
	return u.ReferencedTool
}

func (u *UnitTestToolCallEvaluationModelInput) GetVerifyAbsence() *bool {
	if u == nil {
		return nil
	}
	return u.VerifyAbsence
}

func (u *UnitTestToolCallEvaluationModelInput) GetWorkflowNodeTransition() *UnitTestWorkflowNodeTransitionEvaluationNodeID {
	if u == nil {
		return nil
	}
	return u.WorkflowNodeTransition
}
