// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type UpdateSimulationTestRequest struct {
	// Metadata of a conversation this test was created from (if applicable).
	FromConversationMetadata *TestFromConversationMetadataInput `json:"from_conversation_metadata,omitzero"`
	// Dynamic variables to replace in the agent config during testing
	DynamicVariables map[string]any                                  `json:"dynamic_variables,omitzero"`
	ChatHistory      []ConversationHistoryTranscriptCommonModelInput `json:"chat_history,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"simulation" json:"type"`
	// A prompt that evaluates whether the agent's response is successful. Should return True or False.
	SuccessCondition *string `default:"" json:"success_condition"`
	// Description of the simulation scenario and user persona for simulation tests.
	SimulationScenario *string `default:"" json:"simulation_scenario"`
	// Maximum number of conversation turns for simulation tests.
	SimulationMaxTurns *int64 `default:"5" json:"simulation_max_turns"`
	// The environment to use when running this simulation test. If not provided, defaults to 'production'.
	SimulationEnvironment *string `json:"simulation_environment,omitzero"`
	// Simulation/preview-side config: tools are identified by IDs, resolved to names at runtime.
	ToolMockConfig *SimulationToolMockBehaviorConfig `json:"tool_mock_config,omitzero"`
	Name           string                            `json:"name"`
	// The ID of the parent folder. If not provided, the test will be moved to the root level.
	ParentFolderID *string `json:"parent_folder_id,omitzero"`
}

func (u UpdateSimulationTestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSimulationTestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSimulationTestRequest) GetFromConversationMetadata() *TestFromConversationMetadataInput {
	if u == nil {
		return nil
	}
	return u.FromConversationMetadata
}

func (u *UpdateSimulationTestRequest) GetDynamicVariables() map[string]any {
	if u == nil {
		return nil
	}
	return u.DynamicVariables
}

func (u *UpdateSimulationTestRequest) GetChatHistory() []ConversationHistoryTranscriptCommonModelInput {
	if u == nil {
		return nil
	}
	return u.ChatHistory
}

func (u *UpdateSimulationTestRequest) GetType() *string {
	return types.Pointer("simulation")
}

func (u *UpdateSimulationTestRequest) GetSuccessCondition() *string {
	if u == nil {
		return nil
	}
	return u.SuccessCondition
}

func (u *UpdateSimulationTestRequest) GetSimulationScenario() *string {
	if u == nil {
		return nil
	}
	return u.SimulationScenario
}

func (u *UpdateSimulationTestRequest) GetSimulationMaxTurns() *int64 {
	if u == nil {
		return nil
	}
	return u.SimulationMaxTurns
}

func (u *UpdateSimulationTestRequest) GetSimulationEnvironment() *string {
	if u == nil {
		return nil
	}
	return u.SimulationEnvironment
}

func (u *UpdateSimulationTestRequest) GetToolMockConfig() *SimulationToolMockBehaviorConfig {
	if u == nil {
		return nil
	}
	return u.ToolMockConfig
}

func (u *UpdateSimulationTestRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateSimulationTestRequest) GetParentFolderID() *string {
	if u == nil {
		return nil
	}
	return u.ParentFolderID
}
