// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/optionalnullable"
)

type UpdatePhoneNumberRequest struct {
	AgentID             optionalnullable.OptionalNullable[string]                             `json:"agent_id,omitzero"`
	Label               optionalnullable.OptionalNullable[string]                             `json:"label,omitzero"`
	InboundTrunkConfig  optionalnullable.OptionalNullable[InboundSIPTrunkConfigRequestModel]  `json:"inbound_trunk_config,omitzero"`
	OutboundTrunkConfig optionalnullable.OptionalNullable[OutboundSIPTrunkConfigRequestModel] `json:"outbound_trunk_config,omitzero"`
	LivekitStack        optionalnullable.OptionalNullable[LivekitStackType]                   `default:"standard" json:"livekit_stack"`
}

func (u UpdatePhoneNumberRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePhoneNumberRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePhoneNumberRequest) GetAgentID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.AgentID
}

func (u *UpdatePhoneNumberRequest) GetLabel() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdatePhoneNumberRequest) GetInboundTrunkConfig() optionalnullable.OptionalNullable[InboundSIPTrunkConfigRequestModel] {
	if u == nil {
		return nil
	}
	return u.InboundTrunkConfig
}

func (u *UpdatePhoneNumberRequest) GetOutboundTrunkConfig() optionalnullable.OptionalNullable[OutboundSIPTrunkConfigRequestModel] {
	if u == nil {
		return nil
	}
	return u.OutboundTrunkConfig
}

func (u *UpdatePhoneNumberRequest) GetLivekitStack() optionalnullable.OptionalNullable[LivekitStackType] {
	if u == nil {
		return nil
	}
	return u.LivekitStack
}
