// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
	"github.com/bdlilley/elevenlabs-go/types"
)

type URLAvatar struct {
	// The type of the avatar
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"url" json:"type"`
	// The custom URL of the avatar
	CustomURL *string `default:"" json:"custom_url"`
}

func (u URLAvatar) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *URLAvatar) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *URLAvatar) GetType() *string {
	return types.Pointer("url")
}

func (u *URLAvatar) GetCustomURL() *string {
	if u == nil {
		return nil
	}
	return u.CustomURL
}
