// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UserTypeID - OCSF User type IDs.
//
// Spec: https://schema.ocsf.io/1.6.0/objects/user
type UserTypeID int64

const (
	UserTypeIDZero       UserTypeID = 0
	UserTypeIDOne        UserTypeID = 1
	UserTypeIDTwo        UserTypeID = 2
	UserTypeIDThree      UserTypeID = 3
	UserTypeIDFour       UserTypeID = 4
	UserTypeIDNinetyNine UserTypeID = 99
)

func (e UserTypeID) ToPointer() *UserTypeID {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserTypeID) IsExact() bool {
	if e != nil {
		switch *e {
		case 0, 1, 2, 3, 4, 99:
			return true
		}
	}
	return false
}
