// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerifiedVoiceLanguageResponseModel struct {
	// The language of the voice.
	Language string `json:"language"`
	// The voice's model ID.
	ModelID string `json:"model_id"`
	// The voice's accent, if applicable.
	Accent *string `json:"accent,omitzero"`
	// The voice's locale, if applicable.
	Locale *string `json:"locale,omitzero"`
	// The voice's preview URL, if applicable.
	PreviewURL *string `json:"preview_url,omitzero"`
}

func (v *VerifiedVoiceLanguageResponseModel) GetLanguage() string {
	if v == nil {
		return ""
	}
	return v.Language
}

func (v *VerifiedVoiceLanguageResponseModel) GetModelID() string {
	if v == nil {
		return ""
	}
	return v.ModelID
}

func (v *VerifiedVoiceLanguageResponseModel) GetAccent() *string {
	if v == nil {
		return nil
	}
	return v.Accent
}

func (v *VerifiedVoiceLanguageResponseModel) GetLocale() *string {
	if v == nil {
		return nil
	}
	return v.Locale
}

func (v *VerifiedVoiceLanguageResponseModel) GetPreviewURL() *string {
	if v == nil {
		return nil
	}
	return v.PreviewURL
}
