// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VoicePreviewsResponseModel struct {
	// The previews of the generated voices.
	Previews []VoicePreviewResponseModel `json:"previews"`
	// The text used to preview the voices.
	Text string `json:"text"`
}

func (v *VoicePreviewsResponseModel) GetPreviews() []VoicePreviewResponseModel {
	if v == nil {
		return []VoicePreviewResponseModel{}
	}
	return v.Previews
}

func (v *VoicePreviewsResponseModel) GetText() string {
	if v == nil {
		return ""
	}
	return v.Text
}
