// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookAuthMethodType string

const (
	WebhookAuthMethodTypeHmac   WebhookAuthMethodType = "hmac"
	WebhookAuthMethodTypeOauth2 WebhookAuthMethodType = "oauth2"
	WebhookAuthMethodTypeMtls   WebhookAuthMethodType = "mtls"
)

func (e WebhookAuthMethodType) ToPointer() *WebhookAuthMethodType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WebhookAuthMethodType) IsExact() bool {
	if e != nil {
		switch *e {
		case "hmac", "oauth2", "mtls":
			return true
		}
	}
	return false
}
