// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type WhatsAppConversationInfoDirection string

const (
	WhatsAppConversationInfoDirectionInbound  WhatsAppConversationInfoDirection = "inbound"
	WhatsAppConversationInfoDirectionOutbound WhatsAppConversationInfoDirection = "outbound"
	WhatsAppConversationInfoDirectionUnknown  WhatsAppConversationInfoDirection = "unknown"
)

func (e WhatsAppConversationInfoDirection) ToPointer() *WhatsAppConversationInfoDirection {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WhatsAppConversationInfoDirection) IsExact() bool {
	if e != nil {
		switch *e {
		case "inbound", "outbound", "unknown":
			return true
		}
	}
	return false
}

type WhatsAppConversationInfo struct {
	Direction                *WhatsAppConversationInfoDirection `default:"unknown" json:"direction"`
	WhatsappPhoneNumberID    *string                            `json:"whatsapp_phone_number_id,omitzero"`
	WhatsappUserID           string                             `json:"whatsapp_user_id"`
	AwaitingFirstUserMessage *bool                              `json:"awaiting_first_user_message,omitzero"`
}

func (w WhatsAppConversationInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WhatsAppConversationInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WhatsAppConversationInfo) GetDirection() *WhatsAppConversationInfoDirection {
	if w == nil {
		return nil
	}
	return w.Direction
}

func (w *WhatsAppConversationInfo) GetWhatsappPhoneNumberID() *string {
	if w == nil {
		return nil
	}
	return w.WhatsappPhoneNumberID
}

func (w *WhatsAppConversationInfo) GetWhatsappUserID() string {
	if w == nil {
		return ""
	}
	return w.WhatsappUserID
}

func (w *WhatsAppConversationInfo) GetAwaitingFirstUserMessage() *bool {
	if w == nil {
		return nil
	}
	return w.AwaitingFirstUserMessage
}
