// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/bdlilley/elevenlabs-go/internal/utils"
)

type WidgetLanguagePreset struct {
	// The text contents for the selected language
	TextContents *WidgetTextContents `json:"text_contents,omitzero"`
	// The text to display for terms and conditions in this language
	TermsText *string `json:"terms_text,omitzero"`
	// The HTML to display for terms and conditions in this language
	TermsHTML *string `json:"terms_html,omitzero"`
	// The key to display for terms and conditions in this language
	TermsKey *string `json:"terms_key,omitzero"`
	// The translation cache for the terms
	TermsTranslation *WidgetTermsTranslation `json:"terms_translation,omitzero"`
}

func (w WidgetLanguagePreset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WidgetLanguagePreset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WidgetLanguagePreset) GetTextContents() *WidgetTextContents {
	if w == nil {
		return nil
	}
	return w.TextContents
}

func (w *WidgetLanguagePreset) GetTermsText() *string {
	if w == nil {
		return nil
	}
	return w.TermsText
}

func (w *WidgetLanguagePreset) GetTermsHTML() *string {
	if w == nil {
		return nil
	}
	return w.TermsHTML
}

func (w *WidgetLanguagePreset) GetTermsKey() *string {
	if w == nil {
		return nil
	}
	return w.TermsKey
}

func (w *WidgetLanguagePreset) GetTermsTranslation() *WidgetTermsTranslation {
	if w == nil {
		return nil
	}
	return w.TermsTranslation
}
