// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkspaceCreateWebhookResponseModel struct {
	WebhookID     string  `json:"webhook_id"`
	WebhookSecret *string `json:"webhook_secret,omitzero"`
}

func (w *WorkspaceCreateWebhookResponseModel) GetWebhookID() string {
	if w == nil {
		return ""
	}
	return w.WebhookID
}

func (w *WorkspaceCreateWebhookResponseModel) GetWebhookSecret() *string {
	if w == nil {
		return nil
	}
	return w.WebhookSecret
}
