workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    elevenlabs-go:
        inputs:
            - location: https://api.elevenlabs.io/openapi.json
        registry:
            location: registry.speakeasyapi.dev/kudos/elevenlabs-go/elevenlabs-go
targets:
    elevenlabs-go:
        target: go
        source: elevenlabs-go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kudos/elevenlabs-go/elevenlabs-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
